Repository hashicorp/terraform, pull requests merged in 2018-12, with the labels that each got.

#19529 vendor: update kardianos/osext to support android
  vendor/github.com/kardianos/osext/README.md
  vendor/github.com/kardianos/osext/osext_go18.go
  vendor/github.com/kardianos/osext/osext_plan9.go
  vendor/github.com/kardianos/osext/osext_procfs.go
  vendor/github.com/kardianos/osext/osext_sysctl.go
  vendor/github.com/kardianos/osext/osext_windows.go
Labels: dependencies

#19548 helper/schema: Always propagate NewComputed for previously zero value primitive type attributes
  helper/schema/resource_diff_test.go
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: bug, provider-sdk

#19562 [Website] Skytap provider links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/cloud-index.html.markdown
Labels: documentation

#19563 [Website] Skytap cherry-pick
  website/docs/providers/index.html.markdown
  website/docs/providers/type/cloud-index.html.markdown
Labels: documentation

#19569 states/statemgr: use -mod=vendor to run the state locking helper
  states/statemgr/filesystem_test.go
Labels: bug, build

#19555 backend/remote: use entitlements to select backends
  backend/remote/backend.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan_test.go
  backend/remote/testing.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/modules.txt
Labels: backend/remote, enhancement

#19570 helper/resource: Don't share provider instances between test steps
  helper/resource/testing.go
  helper/resource/testing_config.go
  helper/resource/testing_import_state.go
Labels: enhancement, provider-sdk

#19610 backend/local: Fix incorrect destroy/update count on apply
  backend/local/hook_count.go
  backend/local/hook_count_test.go
Labels: bug

#19611 command/format: Fix rendering of nested blocks during update
  command/format/diff.go
  command/format/diff_test.go
Labels: bug

#19609 command/format: Fix rendering of force-new updates
  command/format/diff.go
  command/format/diff_test.go
Labels: bug

#19613 backend/local: Avoid rendering data sources on destroy
  backend/local/backend_plan.go
  backend/local/backend_plan_test.go
  backend/local/test-fixtures/destroy-with-ds/main.tf
  backend/local/testing.go
Labels: bug

#19649 build: Use Go 1.11.3 in Travis-CI and in environments using "goenv"
  .go-version
  .travis.yml
Labels: build

#19642 backend/local: Render CBD replacement (+/-) correctly
  backend/local/backend_plan.go
  backend/local/backend_plan_test.go
  backend/local/test-fixtures/plan-cbd/main.tf
  command/format/plan.go
Labels: bug, cli

#19664 vendor: upgrade github.com/hashicorp/hcl2
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser_template.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.rl
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/spec.md
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/token.go
  vendor/github.com/hashicorp/hcl2/hcl/json/structure.go
  vendor/github.com/hashicorp/hcl2/hcl/merged.go
  vendor/github.com/hashicorp/hcl2/hclwrite/format.go
  vendor/github.com/hashicorp/hcl2/hclwrite/tokens.go
  vendor/modules.txt
Labels: config, dependencies, enhancement

#19668 backend/remote: fix an error that prevents checking constraints
  backend/remote/backend.go
Labels: backend/remote, bug

#19671 fix error that prevents --no-color flag on providers command
  command/providers.go
Labels: bug, cli

#19667 backend/remote: fix an error that prevents checking constraints
  backend/remote/backend.go
  backend/remote/backend_test.go
  backend/remote/testing.go
Labels: backend/remote, bug

#19687 json output of terraform plan
  command/jsonconfig/config.go
  command/jsonconfig/doc.go
  command/jsonconfig/expression.go
  command/jsonplan/doc.go
  command/jsonplan/module.go
  command/jsonplan/plan.go
  command/jsonplan/resource.go
  command/jsonplan/values.go
  command/jsonstate/expression.go
  command/jsonstate/state.go
  command/show.go
  command/show_test.go
  command/test-fixtures/show/main.tf
Labels: cli, enhancement

#19706 core: Detect and reject self-referencing local values
  terraform/eval_local.go
  terraform/eval_local_test.go
Labels: bug, config

#19715 vendor: upgrade github.com/hashicorp/hcl2
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.rl
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/token.go
  vendor/modules.txt
Labels: config, enhancement

#19727 core: Specialized errors for incorrect indexes in resource reference
  builtin/providers/test/data_source_test.go
  terraform/evaluate_valid.go
  terraform/evaluate_valid_test.go
  terraform/test-fixtures/static-validate-refs/static-validate-refs.tf
Labels: config, enhancement

#19735 lang/funcs: templatefile function
  lang/funcs/filesystem.go
  lang/funcs/filesystem_test.go
  lang/funcs/testdata/bare.tmpl
  lang/funcs/testdata/func.tmpl
  lang/funcs/testdata/hello.tmpl
  lang/funcs/testdata/list.tmpl
  lang/funcs/testdata/recursive.tmpl
  lang/functions.go
  website/docs/configuration/functions/file.html.md
  website/docs/configuration/functions/templatefile.html.md
  website/layouts/functions.erb
Labels: config, enhancement
