Repository hashicorp/terraform, pull requests merged in 2018-08, with the labels that each got.

#18125 helper/resource: Add ability to pre-taint resources
  helper/resource/testing.go
  helper/resource/testing_config.go
  helper/resource/testing_test.go
Labels: enhancement, provider-sdk

#18582 update provider links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/cloud-index.html.markdown
  website/docs/providers/type/infra-index.html.markdown
Labels: documentation

#18604 backend/remote: use schema max/min items options
  backend/remote/backend.go
  backend/remote/backend_test.go
Labels: backend/remote

#18642 backend/remote: do not use the TFE_TOKEN env variable
  backend/remote/backend.go
  website/docs/backends/types/remote.html.md
Labels: backend/remote

#18687 providers: Resolver and Factory types
  providers/resolver.go
Labels: core, enhancement
