Repository hashicorp/terraform, pull requests merged in 2018-07, with the labels that each got.

#18371 Adding TelefonicaOpenCloud Documentation Links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/cloud-index.html.markdown
Labels: documentation

#18344 README: install stringer before running make
  README.md
Labels: documentation, enhancement

#18394 Fix a few mentions of "environment" vs "workspace"
  website/docs/state/workspaces.html.md
Labels: documentation

#18400 Update resource_provisioner.go
  builtin/provisioners/habitat/resource_provisioner.go
Labels: bug, provisioner/habitat

#17853 fix(workspace): add list feature for workspace
  command/workspace_command.go
Labels: cli, enhancement

#18451 statemgr: Backup file support for statemgr.Filesystem
  states/statemgr/filesystem.go
  states/statemgr/filesystem_test.go
Labels: core, enhancement

#18446 builtin/providers: terraform remote state datasource
  builtin/providers/terraform/data_source_state.go
  builtin/providers/terraform/data_source_state_test.go
  builtin/providers/terraform/provider.go
  builtin/providers/terraform/provider_test.go
Labels: enhancement, hashibot/ignore, provider/terraform

#18484 add Config to the PlanResourceChangeRequest
  providers/provider.go
Labels: core

#18536 Removed additional and undesirable 'the' from the automation guide
  website/guides/running-terraform-in-automation.html.md
Labels: documentation

#18526 Fixes `curl` example call in API docs
  website/docs/registry/api.html.md
Labels: documentation, registry

#18538 Link to info on constraining module versions
  website/docs/modules/create.html.markdown
Labels: documentation

#18571 website: Revise the "Module Sources" page
  website/docs/modules/sources.html.markdown
Labels: documentation, modules
