Repository hashicorp/terraform, pull requests merged in 2018-03, with the labels that each got.

#17472 Website: Update Community Providers
  website/docs/providers/type/community-index.html.markdown
Labels: documentation

#17466 minor typos
  website/intro/getting-started/destroy.html.md
  website/intro/getting-started/modules.html.md
  website/intro/getting-started/provision.html.md
Labels: documentation

#17488 Website: add two community providers
  website/docs/providers/type/community-index.html.markdown
Labels: documentation

#13880 provisioner/local-exec: Allow passing env vars to commands
  builtin/provisioners/local-exec/resource_provisioner.go
  builtin/provisioners/local-exec/resource_provisioner_test.go
  website/docs/provisioners/local-exec.html.markdown
Labels: enhancement, provisioner/local-exec

#17531 filter null output values from state
  builtin/providers/terraform/data_source_state.go
  builtin/providers/terraform/data_source_state_test.go
  builtin/providers/terraform/test-fixtures/null_outputs.tfstate
Labels: crash, provider/terraform

#17533 vendor: update "HCL2" and cty packages
  configs/parser_values_test.go
  vendor/github.com/hashicorp/hcl2/ext/typeexpr/README.md
  vendor/github.com/hashicorp/hcl2/ext/typeexpr/doc.go
  vendor/github.com/hashicorp/hcl2/ext/typeexpr/get_type.go
  vendor/github.com/hashicorp/hcl2/ext/typeexpr/public.go
  vendor/github.com/hashicorp/hcl2/gohcl/schema.go
  vendor/github.com/hashicorp/hcl2/hcl/expr_call.go
  vendor/github.com/hashicorp/hcl2/hcl/expr_map.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/peeker.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/public.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/scan_tokens.rl
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/spec.md
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/token.go
  vendor/github.com/hashicorp/hcl2/hcl/json/ast.go
  vendor/github.com/hashicorp/hcl2/hcl/json/navigation.go
  vendor/github.com/hashicorp/hcl2/hcl/json/parser.go
  vendor/github.com/hashicorp/hcl2/hcl/json/public.go
  vendor/github.com/hashicorp/hcl2/hcl/json/spec.md
  vendor/github.com/hashicorp/hcl2/hcl/json/structure.go
  vendor/github.com/hashicorp/hcl2/hcl/json/tokentype_string.go
  vendor/github.com/hashicorp/hcl2/hcl/spec.md
  vendor/github.com/zclconf/go-cty/LICENSE
  vendor/github.com/zclconf/go-cty/cty/convert/conversion.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion_primitive.go
  vendor/github.com/zclconf/go-cty/cty/function/doc.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/csv.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/format_fsm.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/format_fsm.rl
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/json.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/set.go
  vendor/github.com/zclconf/go-cty/cty/function/unpredictable.go
  vendor/github.com/zclconf/go-cty/cty/object_type.go
  vendor/github.com/zclconf/go-cty/cty/path.go
  vendor/github.com/zclconf/go-cty/cty/set/ops.go
  vendor/github.com/zclconf/go-cty/cty/set_helper.go
  vendor/github.com/zclconf/go-cty/cty/value.go
  vendor/github.com/zclconf/go-cty/cty/value_init.go
  vendor/github.com/zclconf/go-cty/cty/value_ops.go
  vendor/github.com/zclconf/go-cty/cty/walk.go
  vendor/vendor.json
Labels: dependencies

#17513 Check for nil config in node_resource_refresh
  terraform/node_resource_refresh.go
Labels: crash

#17536 configs: highlight resource name in diags when invalid
  configs/resource.go
Labels: bug, config

#17537 configs: Disable deprecation warning for quoted keywords/references
  configs/compat_shim.go
  configs/parser_config_test.go
Labels: config, enhancement

#17538 configs: allow full type constraints for variables
  configs/module_merge.go
  configs/module_merge_test.go
  configs/named_values.go
  configs/parser_config.go
  configs/parser_config_test.go
  configs/test-fixtures/invalid-files/variable-bad-default.tf
  configs/test-fixtures/invalid-modules/override-variable-causes-bad-default/base.tf
  configs/test-fixtures/invalid-modules/override-variable-causes-bad-default/override.tf
  configs/test-fixtures/valid-files/variables.tf
Labels: config, enhancement

#17218 Change -force to -auto-approve when destroying
  backend/local/backend_apply.go
  command/apply.go
  command/apply_destroy_test.go
  command/e2etest/primary_test.go
  website/docs/commands/destroy.html.markdown
Labels: cli, enhancement

#17545 don't let default workspace override environment
  builtin/providers/terraform/data_source_state.go
  builtin/providers/terraform/data_source_state_test.go
Labels: bug, provider/terraform

#17550 Grammar Improvement
  website/docs/modules/usage.html.markdown
Labels: documentation

#17551 Export a const for validation methods
  helper/resource/id.go
  helper/resource/id_test.go
Labels: enhancement, provider-sdk

#17561 backend/manta: Manta Backend was not dealing with a ResourceNotFound
  backend/remote-state/manta/client.go
Labels: backend/manta, bug

#17571 docs/internal: Fix sidebar navigation for Remote Service Discovery page
  website/docs/internals/remote-service-discovery.html.md
  website/layouts/docs.erb
Labels: documentation

#17572 docs/getting-started: Replace underscores in aws_s3_bucket name in dependencies example
  website/intro/getting-started/dependencies.html.md
Labels: documentation

#17463 helper/schema: Allow ResourceDiff.ForceNew on nested fields (avoid crash)
  helper/schema/resource_diff.go
  helper/schema/resource_diff_test.go
Labels: bug

#17097 Move towards consistently specifying the type of a Map in a nested *Schema elemnt
  helper/schema/field_reader.go
  helper/schema/field_reader_config.go
  helper/schema/field_reader_config_test.go
  helper/schema/field_reader_diff.go
  helper/schema/field_reader_diff_test.go
  helper/schema/field_reader_map.go
  helper/schema/field_reader_map_test.go
  helper/schema/field_reader_test.go
  helper/schema/schema.go
  helper/schema/schema_test.go
Labels: bug, provider-sdk

#17484 validation: Add ValidateRFC3339TimeString
  helper/validation/validation.go
  helper/validation/validation_test.go
Labels: enhancement

#17586 Allow terraform-bundle to include custom plugins
  tools/terraform-bundle/README.md
  tools/terraform-bundle/package.go
Labels: enhancement

#17616 Typo Correction
  website/docs/backends/config.html.md
Labels: documentation

#17636 Don't open a new file descriptor for a locked state.
  state/local.go
  state/local_test.go
  terraform/state.go
Labels: bug, core, regression

#17355 Updates the chef provisioner to allow specifying a channel
  builtin/provisioners/chef/linux_provisioner.go
  builtin/provisioners/chef/linux_provisioner_test.go
  builtin/provisioners/chef/resource_provisioner.go
  builtin/provisioners/chef/windows_provisioner.go
  builtin/provisioners/chef/windows_provisioner_test.go
Labels: enhancement, provisioner/chef

#17642 remove more unneeded partial outputs
  terraform/context_plan_test.go
  terraform/test-fixtures/plan-untargeted-resource-output/main.tf
  terraform/test-fixtures/plan-untargeted-resource-output/mod/main.tf
  terraform/transform_targets.go
Labels: bug, core

#17646 use correct context for communicator.Retry
  builtin/provisioners/chef/resource_provisioner.go
  builtin/provisioners/file/resource_provisioner.go
  builtin/provisioners/habitat/resource_provisioner.go
  builtin/provisioners/remote-exec/resource_provisioner.go
  builtin/provisioners/remote-exec/resource_provisioner_test.go
  builtin/provisioners/salt-masterless/resource_provisioner.go
  communicator/communicator_mock.go
Labels: bug, core, regression

#17602 Fix providers categories descriptions in documentation
  website/docs/providers/type/community-index.html.markdown
  website/docs/providers/type/infra-index.html.markdown
  website/docs/providers/type/misc-index.html.markdown
  website/docs/providers/type/network-index.html.markdown
Labels: documentation

#17645 unlock state in console, import, graph, and push
  command/console.go
  command/graph.go
  command/import.go
  command/import_test.go
  command/push.go
Labels: bug, regression

#17674 make sure ResourceData timeouts are always set
  helper/schema/resource.go
  helper/schema/resource_data.go
  helper/schema/resource_data_test.go
  helper/schema/resource_test.go
Labels: bug, provider-sdk

#17658 Use built-in method to get user homedir instead of eval on sh
  config_unix.go
Labels: core, enhancement

#17682 add oracle pass links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/major-index.html.markdown
Labels: documentation

#17609 clean up remote.Cmd api
  builtin/provisioners/chef/resource_provisioner.go
  builtin/provisioners/habitat/resource_provisioner.go
  builtin/provisioners/remote-exec/resource_provisioner.go
  builtin/provisioners/salt-masterless/resource_provisioner.go
  communicator/remote/command.go
  communicator/ssh/communicator.go
  communicator/ssh/communicator_test.go
Labels: core, enhancement

#17677 website: Stronger statements on when to use named workspaces
  website/docs/state/workspaces.html.md
Labels: documentation

#17710 command: remove "terraform push"
  command/hcl_printer.go
  command/hcl_printer_test.go
  command/push.go
  command/push_test.go
  commands.go
Labels: cli

#17714 repl: fix formatting of list and map values
  repl/format.go
Labels: bug, cli

#17687 Adding single IP & IP range validations
  helper/validation/validation.go
  helper/validation/validation_test.go
Labels: enhancement, provider-sdk

#17744 retry ssh authentication failures
  communicator/ssh/communicator.go
Labels: provisioner/remote-exec, regression
