Repository hashicorp/terraform, pull requests merged in 2018-06, with the labels that each got.

#18161 add flexibleengine provider documentation links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/cloud-index.html.markdown
Labels: documentation

#18247 Fix broken links to /docs/enterprise/run/api.html
  website/docs/commands/push.html.markdown
  website/docs/configuration/terraform-enterprise.html.md
Labels: documentation

#18268 configload: Configuration snapshots
  configs/configload/loader_snapshot.go
  configs/configload/loader_snapshot_test.go
  configs/parser_config_dir.go
Labels: config, enhancement

#18279 Add AzureStack documentation links[Cherry-pick]
  website/docs/providers/index.html.markdown
  website/docs/providers/type/major-index.html.markdown
Labels: documentation

#11721 Remove error on empty outputs when `-json` is set
  command/output.go
  command/output_test.go
Labels: cli, enhancement

#18286 Export resource deprecation.
  helper/schema/data_source_resource_shim.go
  helper/schema/resource.go
  helper/schema/resource_test.go
Labels: enhancement, provider-sdk

#18297 v0.12 plugin interface packages
  providers/doc.go
  providers/provider.go
  provisioners/doc.go
  provisioners/provisioner.go
Labels: core

#18278 Add AzureStack documentation links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/major-index.html.markdown
Labels: documentation

#18309 configload: Don't download the same module source multiple times
  configs/configload/getter.go
  configs/configload/loader_init_from_module.go
  configs/configload/loader_install.go
Labels: cli, enhancement

#18287 Using demo.consul.io requires `scheme = "https"`
  website/docs/backends/config.html.md
  website/docs/backends/types/consul.html.md
  website/intro/examples/consul.html.markdown
  website/intro/getting-started/remote.html.markdown
  website/upgrade-guides/0-9.html.markdown
Labels: backend/consul, documentation

#18326 website: Tweak the language we use to describe remote state
  website/docs/state/purpose.html.md
  website/docs/state/remote.html.md
Labels: documentation

#18338 Remove aws_region param from Consul example in docs
  website/intro/getting-started/modules.html.md
Labels: documentation

#18352 configupgrade: Analysis of input configuration
  command/012_config_upgrade.go
  configs/configupgrade/analysis.go
  configs/configupgrade/upgrade.go
  configs/configupgrade/upgrade_expr.go
  configs/configupgrade/upgrade_native.go
  configs/configupgrade/upgrade_test.go
  configs/configupgrade/upgrader.go
Labels: config, enhancement

#18362 website: v0.12 preview upgrade guide tweaks
  website/upgrade-guides/0-12.html.markdown
Labels: documentation
