Repository hashicorp/terraform, pull requests merged in 2019-09, with the labels that each got.

#22597 Ensure for_each values wholly known for sets
  terraform/context_apply_test.go
  terraform/context_plan_test.go
  terraform/eval_for_each.go
  terraform/node_data_refresh.go
  terraform/terraform_test.go
  terraform/testdata/plan-for-each-unknown-value/main.tf
Labels: bug, config

#22621 lang/funcs: Various fileset() function updates for usability and consistency
  go.mod
  go.sum
  lang/funcs/filesystem.go
  lang/funcs/filesystem_test.go
  lang/functions_test.go
  lang/testdata/functions-test/subdirectory/hello.tmpl
  lang/testdata/functions-test/subdirectory/hello.txt
  vendor/github.com/bmatcuk/doublestar/.gitignore
  vendor/github.com/bmatcuk/doublestar/.travis.yml
  vendor/github.com/bmatcuk/doublestar/LICENSE
  vendor/github.com/bmatcuk/doublestar/README.md
  vendor/github.com/bmatcuk/doublestar/doublestar.go
  vendor/github.com/bmatcuk/doublestar/go.mod
  vendor/modules.txt
  website/docs/configuration/functions/fileset.html.md
Labels: config, enhancement

#22690 prevent panics when encountering nil diffs
  builtin/providers/test/diff_apply_test.go
  terraform/diff.go
Labels: bug, crash, provider-sdk, v0.12

#22710 website: Warn against using provisioners, and suggest alternatives
  website/docs/provisioners/chef.html.markdown
  website/docs/provisioners/connection.html.markdown
  website/docs/provisioners/file.html.markdown
  website/docs/provisioners/habitat.html.markdown
  website/docs/provisioners/index.html.markdown
  website/docs/provisioners/local-exec.html.markdown
  website/docs/provisioners/puppet.html.markdown
  website/docs/provisioners/remote-exec.html.markdown
  website/docs/provisioners/salt-masterless.html.md
Labels: documentation, enhancement

#22698 Regenerate protobuf files under latest versions
  go.mod
  go.sum
  internal/tfplugin5/tfplugin5.pb.go
  plans/internal/planproto/planfile.pb.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/modules.txt
Labels: core, enhancement

#22697 make: Add check for protobuf dependencies
  Makefile
  scripts/protobuf-check.sh
Labels: build, enhancement

#19097 Improve the method to find out go files in Makefile
  Makefile
Labels: build, enhancement

#22591 Clarification for type of primary key
  website/docs/backends/types/oss.html.md
Labels: backend/oss, bug, documentation

#22145 fix, use extended flags for terraform console
  command/console.go
Labels: cli, enhancement

#22707 docs: Minor spelling and typo fixes
  lang/funcs/collection.go
  lang/funcs/string.go
  website/docs/commands/providers/schema.html.md
  website/docs/configuration-0-11/terraform.html.md
  website/docs/configuration/functions/setintersection.html.md
  website/docs/configuration/functions/setproduct.html.md
  website/docs/configuration/functions/setunion.html.md
  website/docs/configuration/functions/timestamp.html.md
  website/docs/configuration/functions/uuidv5.html.md
Labels: bug, documentation

#22711 build: Use the official Go module proxy for Travis-CI runs
  .travis.yml
Labels: build, enhancement

#22726 command/e2etest: Fix TestInitProviders
  command/e2etest/init_test.go
Labels: bug, build

#22729 don't send an invalid config to a provisioner
  terraform/context_apply_test.go
  terraform/eval_apply.go
  terraform/testdata/apply-provisioner-each/main.tf
Labels: bug, config, crash, v0.12

#22728 command: Stubbed-out (for now) terraform login command
  command/login.go
  command/login_test.go
  command/meta.go
  command/testdata/login-oauth-server/main.go
  command/testdata/login-oauth-server/oauthserver.go
  command/webbrowser/mock.go
  command/webbrowser/mock_test.go
  command/webbrowser/native.go
  command/webbrowser/webbrowser.go
  commands.go
  go.mod
  go.sum
  main.go
  vendor/github.com/pkg/browser/LICENSE
  vendor/github.com/pkg/browser/README.md
  vendor/github.com/pkg/browser/browser.go
  vendor/github.com/pkg/browser/browser_darwin.go
  vendor/github.com/pkg/browser/browser_linux.go
  vendor/github.com/pkg/browser/browser_openbsd.go
  vendor/github.com/pkg/browser/browser_unsupported.go
  vendor/github.com/pkg/browser/browser_windows.go
  vendor/modules.txt
Labels: cli, enhancement

#22724 discovery: use `addrs.ProviderConfig` in place of a `typeName` string
  addrs/provider_type.go
  command/init.go
  command/plugins_test.go
  plugin/discovery/get.go
  plugin/discovery/get_test.go
  tools/terraform-bundle/package.go
Labels: sdkv1

#22505 Bump github.com/apparentlymart/go-cidr
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/modules.txt
Labels: bug, config, dependencies

#22756 Cover empty sets in for_each
  terraform/eval_for_each.go
  terraform/graph_builder_plan_test.go
  terraform/testdata/plan-for-each/main.tf
Labels: bug, config, sdkv1, v0.12

#22760 Add source addressing to make error more useful
  terraform/eval_for_each.go
Labels: sdkv1

#22691 Evaluate ignore changes before sending plan to CustomizeDiff
  builtin/providers/test/resource_test.go
  terraform/eval_diff.go
Labels: config, enhancement, sdkv1

#22772 command: Fix dropped errors
  command/show.go
Labels: bug, cli, v0.12

#22777 Fixed typo in documentation about expressions
  website/docs/configuration/expressions.html.md
Labels: bug, config, documentation

#22755 Fix typo in variables.html
  website/docs/configuration/variables.html.md
Labels: bug, documentation

#22783 core: Warn when creating and applying with -target
  backend/local/backend_apply.go
  terraform/context.go
  terraform/context_apply_test.go
  terraform/context_plan_test.go
Labels: cli, core, enhancement, sdkv1

#22747 lang/funcs: added parseint function
  lang/funcs/number.go
  lang/funcs/number_test.go
  lang/functions.go
  lang/functions_test.go
  website/docs/configuration/functions/parseint.html.md
  website/layouts/functions.erb
Labels: config, enhancement, sdkv1

#22848 [Website] Add Pureport provider links
  website/docs/providers/index.html.markdown
  website/docs/providers/type/network-index.html.markdown
Labels: documentation

#22849 [Website] cherry-pick from master
  website/docs/providers/index.html.markdown
  website/docs/providers/type/network-index.html.markdown
Labels: documentation

#22855 command/import: fix error when given/configured provider != implied provider type name
  command/import.go
  command/import_test.go
  command/testdata/import-provider-mismatch/main.tf
  terraform/graph_builder_import.go
  website/docs/commands/import.html.md
Labels: bug, cli, core, sdkv1, v0.12

#22858 lang/funcs: cidrsubnets function
  lang/funcs/cidr.go
  lang/funcs/cidr_test.go
  lang/functions.go
  lang/functions_test.go
  website/docs/configuration/functions/cidrsubnet.html.md
  website/docs/configuration/functions/cidrsubnets.html.md
Labels: config, enhancement, sdkv1

#22865 website: Link to hashicorp/subnets/cidr for cidrsubnets docs
  website/docs/configuration/functions/cidrsubnets.html.md
Labels: config, documentation, enhancement

#22883 website/contributing: update contribution documentation
  .github/CONTRIBUTING.md
  README.md
Labels: build, documentation

#22895 ensure data sources are always written to state
  terraform/context_refresh_test.go
  terraform/node_data_refresh.go
  terraform/testdata/plan-data-depends-on/main.tf
Labels: sdkv1

#22837 don't lose track of private data in the ACC tests
  builtin/providers/test/resource_nested_set_test.go
  builtin/providers/test/resource_timeout.go
  helper/resource/state_shim.go
Labels: bug, provider-sdk, sdkv1

#21772 Add OAuth2 token support for GCS backend
  backend/remote-state/gcs/backend.go
  website/docs/backends/types/gcs.html.md
Labels: backend/gcs, enhancement

#22918 to e2e, or not e2e, that is the question
  backend/remote-state/etcdv3/backend_test.go
  backend/remote-state/manta/backend.go
  backend/remote-state/manta/backend_test.go
  backend/remote-state/oss/backend_test.go
  internal/initwd/from_module_test.go
  internal/initwd/module_install_test.go
  tools/terraform-bundle/e2etest/package_test.go
  tools/terraform-bundle/e2etest/testdata/empty/terraform-bundle.hcl
  tools/terraform-bundle/e2etest/testdata/many-providers/terraform-bundle.hcl
Labels: sdkv1

#22882 [Website] Add CDA community provider
  website/docs/providers/type/community-index.html.markdown
Labels: documentation, new-provider

#22761 Remote Backend: Support latest cost-estimate API
  backend/remote/backend_common.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan.go
  backend/remote/backend_plan_test.go
  backend/remote/testdata/plan-cost-estimation/cost-estimate.log
  backend/remote/testdata/plan-cost-estimation/plan.log
  backend/remote/testing.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/cost_estimate.go
  vendor/github.com/hashicorp/go-tfe/cost_estimation.go
  vendor/github.com/hashicorp/go-tfe/plan.go
  vendor/github.com/hashicorp/go-tfe/plan_export.go
  vendor/github.com/hashicorp/go-tfe/policy_set.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/type_helpers.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
Labels: backend, backend/remote, terraform-cloud
