Repository hashicorp/terraform, pull requests merged in 2019-02, with the labels that each got.

#19736 Improve section-to-section navigation via sidebar navs
  website/docs/backends/types/etcd.html.md
  website/docs/commands/env.html.markdown
  website/docs/commands/state/addressing.html.md
  website/docs/commands/state/index.html.md
  website/docs/commands/state/list.html.md
  website/docs/commands/state/mv.html.md
  website/docs/commands/state/pull.html.md
  website/docs/commands/state/push.html.md
  website/docs/commands/state/rm.html.md
  website/docs/commands/state/show.html.md
  website/docs/commands/workspace/delete.html.md
  website/docs/commands/workspace/index.html.md
  website/docs/commands/workspace/list.html.md
  website/docs/commands/workspace/new.html.md
  website/docs/commands/workspace/select.html.md
  website/guides/terraform-provider-development-program.html.md
  website/layouts/backend-types.erb
  website/layouts/commands-state.erb
  website/layouts/commands-workspace.erb
  website/layouts/docs.erb
  website/layouts/downloads.erb
  website/layouts/functions.erb
  website/layouts/guides.erb
  website/layouts/intro.erb
  website/layouts/registry.erb
  website/upgrade-guides/0-10.html.markdown
  website/upgrade-guides/0-11.html.markdown
  website/upgrade-guides/0-12.html.markdown
  website/upgrade-guides/0-7.html.markdown
  website/upgrade-guides/0-8.html.markdown
  website/upgrade-guides/0-9.html.markdown
  website/upgrade-guides/index.html.markdown
Labels: documentation

#20178 change copyMissingValues to normalizeNullValues
  helper/plugin/grpc_provider.go
  helper/plugin/grpc_provider_test.go
Labels: provider-sdk

#20194 helper/resource: TestCheckResourceAttrPair allow nonexist
  helper/resource/testing.go
  helper/resource/testing_test.go
Labels: bug, provider-sdk

#20192 make: Make test-compile module-aware
  Makefile
Labels: build

#20205 build: Periodic refresh of our go.googlesource.com cookie
  scripts/gogetcookie.sh
Labels: build

#20226 plans/objchange: Improve precision of AssertObjectCompatible with sets
  plans/objchange/compatible.go
  plans/objchange/compatible_test.go
Labels: core, enhancement

#20224 SDK set fixes
  builtin/providers/test/provider.go
  builtin/providers/test/resource_computed_set.go
  builtin/providers/test/resource_computed_set_test.go
  builtin/providers/test/resource_list_set.go
  builtin/providers/test/resource_list_set_test.go
  builtin/providers/test/resource_nested_set_test.go
  helper/plugin/grpc_provider.go
  helper/schema/schema.go
  helper/schema/set.go
Labels: provider-sdk

#20235 only force top-level id's back to unknown
  builtin/providers/test/provider.go
  builtin/providers/test/resource_nested_id.go
  builtin/providers/test/resource_nested_id_test.go
  terraform/diff.go
Labels: provider-sdk

#20238 build.sh: only set git commit info for dev builds
  scripts/build.sh
Labels: bug, core

#20249 build: Run "go generate" in modules mode
  Makefile
  plugin/mock_proto/generate.go
  plugin/mock_proto/generate.sh
Labels: bug, build

#20239 build.sh: only set git commit info for dev builds
  scripts/build.sh
Labels: bug, core

#20246 core: always use slashes in modules.json
  config/module/storage.go
  configs/configload/module_manifest.go
Labels: backend/remote, bug, core

#20237 backend/remote: cleanup test connections
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan_test.go
  backend/remote/backend_state_test.go
  backend/remote/backend_test.go
  backend/remote/testing.go
  svchost/disco/host.go
Labels: backend/remote, bug

#20241 backend/remote: fix bufio.Scanner: token too long
  backend/remote/backend_apply.go
  backend/remote/backend_common.go
  backend/remote/backend_plan.go
  backend/remote/backend_plan_test.go
  backend/remote/test-fixtures/plan-long-line/main.tf
  backend/remote/test-fixtures/plan-long-line/plan.log
Labels: backend/remote, bug

#20240 backend/remote: cleanup test connections
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan_test.go
  backend/remote/backend_state_test.go
  backend/remote/backend_test.go
  backend/remote/testing.go
  svchost/disco/host.go
Labels: backend/remote, bug

#20242 backend/remote: fix bufio.Scanner: token too long
  backend/remote/backend_apply.go
  backend/remote/backend_common.go
  backend/remote/backend_plan.go
  backend/remote/backend_plan_test.go
  backend/remote/test-fixtures/plan-long-line/main.tf
  backend/remote/test-fixtures/plan-long-line/plan.log
Labels: backend/remote, bug

#20265 plans/objchange: Don't presume unknown for values unset in config
  backend/local/backend_apply_test.go
  backend/local/testing.go
  builtin/providers/test/resource_list_test.go
  builtin/providers/test/resource_nested_set_test.go
  command/show_test.go
  command/test-fixtures/show-json/basic-delete/output.json
  command/test-fixtures/show-json/basic-delete/terraform.tfstate
  command/test-fixtures/show-json/basic-update/output.json
  command/test-fixtures/show-json/basic-update/terraform.tfstate
  configs/configschema/coerce_value.go
  configs/configschema/coerce_value_test.go
  helper/plugin/grpc_provider.go
  helper/plugin/unknown.go
  helper/plugin/unknown_test.go
  lang/funcs/string.go
  plans/objchange/all_null.go
  plans/objchange/objchange.go
  plans/objchange/objchange_test.go
  terraform/context_plan_test.go
  terraform/eval_read_data.go
Labels: bug, provider-sdk

#20295 process state even after provider.Apply errors
  builtin/providers/test/resource.go
  builtin/providers/test/resource_test.go
  helper/plugin/grpc_provider.go
Labels: provider-sdk

#20292 allow 0 and unset to be equal in count tests
  helper/resource/testing.go
  helper/resource/testing_test.go
Labels: bug, provider-sdk

#20300 allow implicit empty strings in lists
  builtin/providers/test/resource_test.go
  terraform/diff.go
Labels: provider-sdk

#20302 vendor: Bump more dependencies to go-mod-aware versions
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/hashicorp/logutils/go.mod
  vendor/github.com/mitchellh/copystructure/go.mod
  vendor/github.com/mitchellh/copystructure/go.sum
  vendor/github.com/mitchellh/hashstructure/README.md
  vendor/github.com/mitchellh/hashstructure/go.mod
  vendor/github.com/mitchellh/hashstructure/hashstructure.go
  vendor/github.com/mitchellh/reflectwalk/go.mod
  vendor/modules.txt
Labels: dependencies

#20290 vendor: github.com/hashicorp/hil@latest
  go.mod
  go.sum
  vendor/github.com/hashicorp/hil/convert.go
  vendor/github.com/hashicorp/hil/go.mod
  vendor/github.com/hashicorp/hil/go.sum
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/CHANGELOG.md
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/modules.txt
Labels: dependencies

#20282 plans/objchange: AssertPlanValid function
  command/apply_test.go
  configs/configschema/implied_type.go
  helper/plugin/grpc_provider.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin5/tfplugin5.proto
  plans/objchange/compatible.go
  plans/objchange/compatible_test.go
  plans/objchange/plan_valid.go
  plans/objchange/plan_valid_test.go
  plugin/grpc_provider.go
  providers/provider.go
  terraform/context_apply_test.go
  terraform/context_plan_test.go
  terraform/context_test.go
  terraform/eval_apply.go
  terraform/eval_diff.go
  terraform/terraform_test.go
  terraform/test-fixtures/apply-idattr/main.tf
  terraform/test-fixtures/plan-diffvar/main.tf
Labels: core, enhancement, provider-sdk

#20310 vendor: github.com/hashicorp/go-tfe@v0.3.8
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/README.md
  vendor/github.com/hashicorp/go-tfe/configuration_version.go
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/policy_check.go
  vendor/github.com/hashicorp/go-tfe/team.go
  vendor/github.com/hashicorp/go-tfe/team_access.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
Labels: dependencies

#20308 Requires replace should not error on missing index steps
  builtin/providers/test/resource_list.go
  builtin/providers/test/resource_list_test.go
  terraform/eval_diff.go
Labels: bug, core, provider-sdk

#20243 docs/upgrade-guide: Document changes in remote state referencing
  website/upgrade-guides/0-12.html.markdown
Labels: documentation

#20319 update go-plugin
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-plugin/grpc_broker.go
  vendor/github.com/hashicorp/go-plugin/grpc_client.go
  vendor/github.com/hashicorp/go-plugin/grpc_controller.go
  vendor/github.com/hashicorp/go-plugin/grpc_server.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/gen.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_broker.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_broker.proto
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_controller.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_controller.proto
  vendor/github.com/hashicorp/go-plugin/testing.go
  vendor/modules.txt
Labels: provider-sdk

#20320 core: Better handle providers failing updates with no new value
  terraform/context_apply_test.go
  terraform/eval_apply.go
Labels: bug, core

#20316 vendor: github.com/hashicorp/go-tfe@v0.3.8
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/configuration_version.go
  vendor/github.com/hashicorp/go-tfe/team.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/modules.txt
Labels: dependencies

#20333 helper/plugin: fix panic with empty objects in normalizeNullValues
  helper/plugin/grpc_provider.go
  helper/plugin/grpc_provider_test.go
Labels: bug, provider-sdk

#20334 config: Backport file hashing functions from 0.12
  config/interpolate_funcs.go
  config/interpolate_funcs_test.go
  website/docs/configuration/interpolation.html.md
Labels: config, enhancement

#20336 vendor: go get github.com/hashicorp/hcl2@master
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/structure.go
  vendor/modules.txt
Labels: bug, config

#20337 helper/validation: Backport All(), Any(), and IntInSlice() functions
  helper/validation/validation.go
  helper/validation/validation_test.go
Labels: enhancement, provider-sdk

#20339 helper/schema: Add deprecation to ResourceData.UnsafeSetFieldRaw
  helper/schema/resource_data.go
Labels: provider-sdk

#20347 plans/objchange: Fix panic in AssertObjectCompatible with set blocks
  plans/objchange/compatible.go
  plans/objchange/compatible_test.go
Labels: bug, core

#20348 simple list diffs may also have missing elements
  builtin/providers/test/resource.go
  builtin/providers/test/resource_list.go
  builtin/providers/test/resource_list_test.go
  terraform/diff.go
Labels: provider-sdk

#17151 Ensure state and pillar remote locations are always defined
  builtin/provisioners/salt-masterless/resource_provisioner.go
Labels: bug, provisioner/salt-masterless

#20379 backend/remote: use `state.v2` for remote state only
  backend/remote-state/etcdv2/backend.go
  backend/remote/backend.go
  backend/remote/testing.go
Labels: backend/remote, enhancement

#20397 move provider init error to where it is generated
  backend/local/backend.go
  terraform/context.go
  terraform/resource_provider.go
Labels: bug, cli

#20398 configs/configupgrade: upgrade expressions inside heredocs
  configs/configupgrade/test-fixtures/valid/heredoc-flush/input/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-flush/want/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-flush/want/versions.tf
  configs/configupgrade/test-fixtures/valid/heredoc-no-interp/input/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-no-interp/want/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-no-interp/want/versions.tf
  configs/configupgrade/test-fixtures/valid/heredoc-sameline/input/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-sameline/want/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-sameline/want/versions.tf
  configs/configupgrade/test-fixtures/valid/heredoc-standard/input/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-standard/want/heredoc.tf
  configs/configupgrade/test-fixtures/valid/heredoc-standard/want/versions.tf
  configs/configupgrade/upgrade_expr.go
  configs/configupgrade/upgrade_native.go
Labels: cli, enhancement

#20399 remove ssh private key contents from errors
  communicator/ssh/provisioner.go
Labels: bug, provisioner/remote-exec

#20400 configs/configupgrade: Fix up internal HIL conversion functions
  configs/configupgrade/test-fixtures/valid/funcs-replaced/input/funcs-replaced.tf
  configs/configupgrade/test-fixtures/valid/funcs-replaced/want/funcs-replaced.tf
  configs/configupgrade/upgrade_expr.go
Labels: cli, enhancement

#20403 configs/configupgrade: Silently ignore and trim .% and .# in ignore_changes
  configs/configupgrade/test-fixtures/valid/ignore-changes-flatmap-colls/input/ignore-changes-flatmap-colls.tf
  configs/configupgrade/test-fixtures/valid/ignore-changes-flatmap-colls/want/ignore-changes-flatmap-colls.tf
  configs/configupgrade/test-fixtures/valid/ignore-changes-flatmap-colls/want/versions.tf
  configs/configupgrade/upgrade_expr.go
Labels: cli, enhancement

#20404 configs/configupgrade: Test for removing commas between block arguments
  configs/configupgrade/test-fixtures/valid/argument-commas/input/argument-commas.tf
  configs/configupgrade/test-fixtures/valid/argument-commas/want/argument-commas.tf
  configs/configupgrade/test-fixtures/valid/argument-commas/want/versions.tf
Labels: cli, enhancement

#20405 configs/configupgrade: Detect and fix element(...) usage with sets
  configs/configupgrade/test-fixtures/valid/element-of-set/input/element-of-set.tf
  configs/configupgrade/test-fixtures/valid/element-of-set/want/element-of-set.tf
  configs/configupgrade/test-fixtures/valid/element-of-set/want/versions.tf
  configs/configupgrade/upgrade_expr.go
  configs/configupgrade/upgrade_test.go
Labels: cli, enhancement

#20417 print scp error before exiting on error code
  communicator/ssh/communicator.go
Labels: provisioner/file

#20430 vendor: github.com/xanzy/ssh-agent@v0.2.1
  go.mod
  go.sum
  vendor/github.com/xanzy/ssh-agent/go.mod
  vendor/github.com/xanzy/ssh-agent/go.sum
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/internal/chacha20/asm_arm64.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/openpgp/write.go
  vendor/golang.org/x/crypto/pkcs12/pkcs12.go
  vendor/golang.org/x/crypto/ssh/knownhosts/knownhosts.go
  vendor/golang.org/x/sys/unix/README.md
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.pl
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/modules.txt
Labels: dependencies

#20352 mildwonkey/show docs
  command/show.go
  website/docs/commands/show.html.markdown
  website/docs/internals/json-format.html.md
  website/layouts/docs.erb
Labels: documentation

#20434 vendor: Bump mattn dependencies to go-mod-aware versions
  go.mod
  go.sum
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/go.mod
  vendor/github.com/mattn/go-colorable/go.sum
  vendor/github.com/mattn/go-isatty/go.mod
  vendor/github.com/mattn/go-isatty/go.sum
  vendor/github.com/mattn/go-isatty/isatty_appengine.go
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_linux.go
  vendor/github.com/mattn/go-isatty/isatty_linux_ppc64x.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-shellwords/LICENSE
  vendor/github.com/mattn/go-shellwords/README.md
  vendor/github.com/mattn/go-shellwords/go.mod
  vendor/github.com/mattn/go-shellwords/shellwords.go
  vendor/github.com/mattn/go-shellwords/util_go15.go
  vendor/github.com/mattn/go-shellwords/util_posix.go
  vendor/github.com/mattn/go-shellwords/util_windows.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/modules.txt
Labels: dependencies

#20443 vendor: Bump levenshtein & osext to go-mod-aware versions
  go.mod
  go.sum
  vendor/github.com/agext/levenshtein/.gitignore
  vendor/github.com/agext/levenshtein/.travis.yml
  vendor/github.com/agext/levenshtein/README.md
  vendor/github.com/agext/levenshtein/go.mod
  vendor/github.com/agext/levenshtein/test.sh
  vendor/github.com/kardianos/osext/go.mod
  vendor/modules.txt
Labels: dependencies

#20445 configs/configupgrade: Fix up uses of the .count pseudo-attribute
  configs/configupgrade/test-fixtures/valid/resource-count-ref/input/resource-count-ref.tf
  configs/configupgrade/test-fixtures/valid/resource-count-ref/want/resource-count-ref.tf
  configs/configupgrade/test-fixtures/valid/resource-count-ref/want/versions.tf
  configs/configupgrade/upgrade_expr.go
Labels: cli, enhancement

#20437 add ssh keepalive messages to communicator
  communicator/ssh/communicator.go
  communicator/ssh/communicator_test.go
Labels: bug, provisioner/remote-exec

#20447 config/configupgrade: Test to show that list unwrapping works for sets
  configs/configschema/decoder_spec.go
  configs/configupgrade/test-fixtures/valid/redundant-list/input/redundant-list.tf
  configs/configupgrade/test-fixtures/valid/redundant-list/want/redundant-list.tf
Labels: cli, enhancement

#20432 s3 workspace_key_prefix
  backend/remote-state/s3/backend.go
  backend/remote-state/s3/backend_state.go
  backend/remote-state/s3/backend_test.go
Labels: backend/s3

#20450 command: Specialized error message for var decls in tfvars
  command/meta_vars.go
  command/plan_test.go
Labels: cli, enhancement

#20211 Swift remote backend support for workspaces & locking
  backend/remote-state/swift/backend.go
  backend/remote-state/swift/backend_state.go
  backend/remote-state/swift/backend_test.go
  backend/remote-state/swift/client.go
  backend/remote-state/swift/client_test.go
Labels: backend/swift, enhancement

#20460 backend/remote: use the can-queue-apply permission
  backend/remote/backend_apply.go
  backend/remote/backend_mock.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
Labels: backend/remote, bug

#20462 backend/remote: use the can-queue-apply permission
  backend/remote/backend_apply.go
  backend/remote/backend_mock.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/workspace.go
  vendor/modules.txt
Labels: backend/remote, bug

#20467 command: Remove promise of plan -validate-only from validate docs
  command/validate.go
Labels: bug, cli

#20480 backend init defaults and inputs
  backend/atlas/backend.go
  backend/backend.go
  backend/init/deprecate_test.go
  backend/init/init.go
  backend/local/backend.go
  backend/nil.go
  backend/remote-state/s3/backend.go
  backend/remote-state/s3/backend_test.go
  backend/remote/backend.go
  backend/remote/backend_test.go
  backend/remote/testing.go
  backend/testing.go
  builtin/providers/terraform/data_source_state.go
  command/init.go
  command/meta_backend.go
  helper/schema/backend.go
  helper/schema/backend_test.go
Labels: bug, config

#20483 vendor: github.com/dylanmei/winrmtest@99b7fe2fddf1
  go.mod
  go.sum
  vendor/github.com/antchfx/xpath/.travis.yml
  vendor/github.com/antchfx/xpath/README.md
  vendor/github.com/antchfx/xpath/build.go
  vendor/github.com/antchfx/xpath/func.go
  vendor/github.com/antchfx/xpath/func_go110.go
  vendor/github.com/antchfx/xpath/func_pre_go110.go
  vendor/github.com/antchfx/xpath/parse.go
  vendor/github.com/antchfx/xpath/query.go
  vendor/github.com/antchfx/xpath/xpath.go
  vendor/github.com/antchfx/xquery/xml/node.go
  vendor/github.com/dylanmei/winrmtest/go.mod
  vendor/github.com/dylanmei/winrmtest/go.sum
  vendor/github.com/satori/go.uuid/.travis.yml
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/codec.go
  vendor/github.com/satori/go.uuid/generator.go
  vendor/github.com/satori/go.uuid/sql.go
  vendor/github.com/satori/go.uuid/uuid.go
  vendor/modules.txt
Labels: dependencies

#20490 vendor: go get github.com/hashicorp/hcl2@master
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl2/hcl/json/structure.go
  vendor/modules.txt
Labels: bug, config

#20481 backend/remote: exit with 1 when a run is canceled
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan_test.go
Labels: backend/remote, bug

#20482 backend/remote: exit with 1 when a run is canceled
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan_test.go
Labels: backend/remote, bug

#20495 vendor: github.com/golang/protobuf@v1.3.0
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.proto
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/any/any.proto
  vendor/github.com/golang/protobuf/ptypes/duration.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.proto
  vendor/modules.txt
Labels: dependencies

#20497 backend/s3: Add debug logging and user agent
  backend/remote-state/s3/backend.go
Labels: backend/s3, enhancement

#20509 vendor: go get golang.org/x/crypto@31a38585487a
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/agent/server.go
  vendor/modules.txt
Labels: dependencies
