Repository hashicorp/terraform, pull requests merged in 2019-10, with the labels that each got.

#22705 Habitat provisioner updates
  builtin/provisioners/habitat/linux_provisioner.go
  builtin/provisioners/habitat/linux_provisioner_test.go
  builtin/provisioners/habitat/resource_provisioner.go
  builtin/provisioners/habitat/resource_provisioner_test.go
  website/docs/provisioners/habitat.html.markdown
Labels: enhancement, provisioner/habitat

#22519 website: Document behavior of `self` object for provisioners
  website/docs/configuration/expressions.html.md
  website/docs/configuration/resources.html.md
  website/docs/provisioners/connection.html.markdown
  website/docs/provisioners/index.html.markdown
  website/layouts/docs.erb
Labels: config, documentation, enhancement

#22811 bug: fix terraform trying to clean up orphan modules on target
  terraform/context_apply_test.go
  terraform/node_module_removed.go
  terraform/testdata/apply-targeted-resource-orphan-module/child/main.tf
  terraform/testdata/apply-targeted-resource-orphan-module/main.tf
Labels: bug, core, sdkv1, v0.12

#22846 Always evaluate resources in their entirety
  addrs/parse_ref.go
  addrs/parse_ref_test.go
  configs/configupgrade/analysis_expr.go
  lang/data.go
  lang/data_test.go
  lang/eval.go
  lang/eval_test.go
  terraform/context_apply_test.go
  terraform/eval_apply.go
  terraform/evaluate.go
  terraform/testdata/apply-invalid-index/main.tf
Labels: config, enhancement, sdkv1

#22966 Update expression docs to clarify for_each usage
  website/docs/configuration/expressions.html.md
Labels: config, documentation, enhancement

#22997 [Website] Add links to provider documentation
  website/docs/providers/index.html.markdown
  website/docs/providers/type/monitor-index.html.markdown
Labels: documentation, enhancement

#23011 remove duplicate statement
  command/plan.go
Labels: cli, enhancement

#23061 website: Full examples for for_each with flatten and setproduct
  website/docs/configuration/expressions.html.md
  website/docs/configuration/functions/flatten.html.md
  website/docs/configuration/functions/setproduct.html.md
  website/docs/configuration/resources.html.md
Labels: config, documentation, enhancement

#22989 command/validate: warn if unused flags are set on the command line
  command/validate.go
Labels: cli, enhancement

#23065 Revise our contributing/development documentation
  .github/CONTRIBUTING.md
  .github/SUPPORT.md
  BUILDING.md
  README.md
Labels: build, documentation, enhancement

#22626 Update output
  website/docs/commands/taint.html.markdown
Labels: bug, cli, documentation

#23157 Add a special error when each.value is nil in for_each resources
  terraform/context_apply_test.go
  terraform/evaluate.go
Labels: sdkv1

#23111 Fix documentation for issue #21614,
  website/docs/configuration/resources.html.md
  website/docs/modules/composition.html.markdown
  website/docs/state/workspaces.html.md
Labels: documentation

#21006 Clarify where you run the `terraform init` command
  website/docs/configuration/providers.html.md
Labels: documentation, enhancement

#22946 remove dotfile exclusion in copyDir
  configs/configload/copy_dir.go
Labels: bug, config, sdkv1, v0.12

#22937 create_before_destroy across modules
  terraform/context_apply_test.go
  terraform/graph_builder_apply.go
  terraform/graph_builder_apply_test.go
  terraform/testdata/apply-destroy-data-cycle/main.tf
  terraform/testdata/apply-module-replace-cycle-cbd/main.tf
  terraform/testdata/apply-module-replace-cycle-cbd/mod1/main.tf
  terraform/testdata/apply-module-replace-cycle-cbd/mod2/main.tf
  terraform/testdata/apply-module-replace-cycle/main.tf
  terraform/testdata/apply-module-replace-cycle/mod1/main.tf
  terraform/testdata/apply-module-replace-cycle/mod2/main.tf
  terraform/testdata/transform-cbd-destroy-edge-both-count/main.tf
  terraform/testdata/transform-cbd-destroy-edge-count/main.tf
  terraform/testdata/transform-destroy-cbd-edge-basic/main.tf
  terraform/transform_config_flat.go
  terraform/transform_config_flat_test.go
  terraform/transform_destroy_cbd.go
  terraform/transform_destroy_cbd_test.go
  terraform/transform_destroy_edge.go
  terraform/transform_diff.go
Labels: bug, core, sdkv1, v0.12

#23139 website: Add Terraform Registry Provider Docs page
  website/docs/registry/providers/docs.html.md
  website/layouts/registry.erb
Labels: documentation, enhancement

#22905 Docs: fix wording
  website/docs/modules/composition.html.markdown
Labels: bug, config, documentation

#21707 Document that Provider Proxy Configuration only supports `alias`
  website/docs/configuration/modules.html.md
  website/docs/configuration/providers.html.md
  website/docs/configuration/terraform.html.md
Labels: documentation, enhancement

#23217 config: Remove legacy interpolation function implementations
  config/config_test.go
  config/hcl2_shim_util.go
  config/hcl2_shim_util_test.go
  config/interpolate_funcs.go
  config/interpolate_funcs_test.go
  config/raw_config.go
Labels: config, enhancement

#23215 Resource value may be an object in self evaluation
  lang/eval.go
  terraform/context_apply_test.go
  terraform/testdata/apply-provisioner-for-each-self/main.tf
Labels: core, crash, sdkv1
