Repository hashicorp/terraform, pull requests merged in 2019-04, with the labels that each got.

#20875 configs/configupgrade: Prefer block syntax for list-of-object attributes
  configs/configupgrade/test-fixtures/valid/list-of-obj-as-block/input/list-of-obj-as-block.tf
  configs/configupgrade/test-fixtures/valid/list-of-obj-as-block/want/list-of-obj-as-block.tf
  configs/configupgrade/test-fixtures/valid/list-of-obj-as-block/want/versions.tf
  configs/configupgrade/upgrade_body.go
  configs/configupgrade/upgrade_test.go
  lang/blocktoattr/fixup.go
  lang/blocktoattr/schema.go
  lang/blocktoattr/variables.go
Labels: config, enhancement

#20904 filter nulls when shimming a config
  config/hcl2shim/values.go
  config/hcl2shim/values_test.go
Labels: provider-sdk

#20906 increase grpc recv limit
  plugin/grpc_provider.go
  plugin/grpc_provider_test.go
Labels: provider-sdk

#20891 helper/schema: Prevent setSet() panic with typed nil
  helper/schema/field_writer_map.go
  helper/schema/field_writer_map_test.go
Labels: bug, crash, provider-sdk

#20909 Validate configuration shims for nulls in lists
  config/hcl2shim/values.go
  config/hcl2shim/values_test.go
  helper/plugin/grpc_provider.go
  helper/plugin/grpc_provider_test.go
Labels: provider-sdk

#20923 Allow all planned computed diff fields
  builtin/providers/test/resource.go
  builtin/providers/test/resource_test.go
  helper/plugin/grpc_provider.go
Labels: provider-sdk

#20925 lang: EvalBlock should use ReferencesInBlock
  lang/eval.go
  lang/eval_test.go
Labels: bug, config

#20935 website: Documentation of the special "attributes as blocks" mode
  website/docs/configuration/attr-as-blocks.html.md
Labels: documentation

#20936 website: correct the title of the "matchkeys" function page
  website/docs/configuration/functions/matchkeys.html.md
Labels: documentation

#20939 configs/configupgrade: Normalize number literals to decimal
  configs/configupgrade/test-fixtures/valid/number-literals/input/number-literals.tf
  configs/configupgrade/test-fixtures/valid/number-literals/want/number-literals.tf
  configs/configupgrade/test-fixtures/valid/number-literals/want/versions.tf
  configs/configupgrade/upgrade_expr.go
Labels: bug, cli

#20942 lang/blocktoattr: Apply fixup within already-fixed-up blocks too
  lang/blocktoattr/fixup.go
  lang/blocktoattr/fixup_test.go
  lang/blocktoattr/variables_test.go
Labels: bug, config

#20952 gomod: update `go-tfe`
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-slug/go.mod
  vendor/github.com/hashicorp/go-slug/slug.go
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/notification_configuration.go
  vendor/github.com/hashicorp/go-tfe/state_version.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/type_helpers.go
  vendor/github.com/hashicorp/go-tfe/variable.go
  vendor/github.com/hashicorp/go-uuid/uuid.go
  vendor/modules.txt
Labels: backend/remote, bug

#20953 gomod: update `go-tfe`
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-slug/go.mod
  vendor/github.com/hashicorp/go-slug/slug.go
  vendor/github.com/hashicorp/go-tfe/go.mod
  vendor/github.com/hashicorp/go-tfe/go.sum
  vendor/github.com/hashicorp/go-tfe/notification_configuration.go
  vendor/github.com/hashicorp/go-tfe/state_version.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/github.com/hashicorp/go-tfe/type_helpers.go
  vendor/github.com/hashicorp/go-tfe/variable.go
  vendor/github.com/hashicorp/go-uuid/uuid.go
  vendor/modules.txt
Labels: backend/remote, bug

#20977 Don't allow unknown values in the config when generating the apply Diff
  builtin/providers/test/resource_state_func.go
  builtin/providers/test/resource_state_func_test.go
  helper/plugin/grpc_provider.go
  helper/schema/shims.go
  helper/schema/shims_test.go
Labels: provider-sdk

#20973 Optimized build processes and image sizes by using build containers.
  scripts/docker-release/Dockerfile-release
Labels: build, enhancement

#20949 configs/configschema: Introduce the NestingGroup mode for blocks
  command/format/diff.go
  command/jsonconfig/expression.go
  command/jsonprovider/block.go
  config/hcl2shim/values.go
  configs/configschema/coerce_value.go
  configs/configschema/decoder_spec.go
  configs/configschema/empty_value.go
  configs/configschema/empty_value_test.go
  configs/configschema/internal_validate.go
  configs/configschema/nestingmode_string.go
  configs/configschema/schema.go
  configs/configschema/validate_traversal.go
  configs/configupgrade/upgrade_native.go
  helper/plugin/unknown.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin5/tfplugin5.proto
  plans/objchange/all_null.go
  plans/objchange/compatible.go
  plans/objchange/normalize_obj.go
  plans/objchange/objchange.go
  plans/objchange/plan_valid.go
  plugin/convert/schema.go
  terraform/context_plan_test.go
  terraform/resource.go
  terraform/test-fixtures/plan-block-nesting-group/block-nesting-group.tf
Labels: config, enhancement, provider-sdk

#20989 Prevent a panic caused by writing to a nil map
  backend/remote/backend_context.go
Labels: backend/remote, crash

#20990 Prevent a panic caused by writing to a nil map
  backend/remote/backend_context.go
Labels: backend/remote, crash

#21017 configs: Handle "dynamic" blocks as special during override merging
  configs/module_merge_body.go
  configs/module_merge_test.go
  configs/test-fixtures/valid-modules/override-dynamic-block-base/a_override.tf
  configs/test-fixtures/valid-modules/override-dynamic-block-base/base.tf
  configs/test-fixtures/valid-modules/override-dynamic-block-override/a_override.tf
  configs/test-fixtures/valid-modules/override-dynamic-block-override/base.tf
  configs/util.go
Labels: bug, config

#21019 helper/resource: Ignore Removed attributes for ImportStateVerify
  builtin/providers/test/provider.go
  builtin/providers/test/resource_import_removed.go
  builtin/providers/test/resource_import_removed_test.go
  helper/resource/testing_import_state.go
  helper/schema/field_reader.go
  helper/schema/resource.go
Labels: bug, provider-sdk

#21033 core: Keep old value on error even for delete
  builtin/providers/test/provider.go
  builtin/providers/test/resource_undeletable.go
  terraform/context_apply_test.go
  terraform/eval_apply.go
Labels: bug, core

#21035 helper/schema: Use a more targeted shim for nested set diff applying
  builtin/providers/test/diff_apply_test.go
  builtin/providers/test/resource_config_mode.go
  builtin/providers/test/resource_config_mode_test.go
  helper/schema/shims.go
  terraform/diff.go
Labels: bug, provider-sdk

#21031 configs/configupgrade: Preserve comments on items in object exprs
  configs/configupgrade/test-fixtures/valid/noop/input/resources.tf
  configs/configupgrade/test-fixtures/valid/noop/want/resources.tf
  configs/configupgrade/upgrade_expr.go
Labels: bug, cli

#21041 configs/configupgrade: Don't panic if analyzer fails
  configs/configupgrade/upgrade.go
Labels: bug, cli, crash

#21039 core: Input variables are always unknown during validate
  terraform/context_validate_test.go
  terraform/evaluate.go
Labels: bug, core

#18083 Use user-supplied plugin path when running graph command
  command/graph.go
Labels: bug, cli

#21042 website: v0.12 upgrade guide about list variables and brackets
  website/upgrade-guides/0-12.html.markdown
Labels: documentation

#21045 website: Fix incorrect example in Module Composition page
  website/docs/modules/composition.html.markdown
Labels: documentation, modules

#21068 delete unknown values from apply config altogether
  builtin/providers/test/resource.go
  builtin/providers/test/resource_test.go
  helper/schema/shims.go
  helper/schema/shims_test.go
Labels: bug, provider-sdk

#21077 Fixes for maps in shims
  builtin/providers/test/resource_map.go
  builtin/providers/test/resource_map_test.go
  helper/plugin/grpc_provider.go
  helper/plugin/grpc_provider_test.go
Labels: provider-sdk

#21082 vendor: go get github.com/hashicorp/go-msgpack@v0.5.4
  go.mod
  go.sum
Labels: dependencies

#21117 deps: github.com/aws/aws-sdk-go@v1.19.18
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/NOTICE.txt
  vendor/github.com/aws/aws-sdk-go/aws/awsutil/equal.go
  vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/session/cabundle_transport.go
  vendor/github.com/aws/aws-sdk-go/aws/session/cabundle_transport_1_5.go
  vendor/github.com/aws/aws-sdk-go/aws/session/cabundle_transport_1_6.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/doc.go
  vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/customizations.go
  vendor/modules.txt
Labels: backend/s3, enhancement

#21102 update to latest go-tfe
  backend/remote/backend_common.go
  backend/remote/backend_mock.go
  backend/remote/backend_plan.go
  backend/remote/backend_plan_test.go
  backend/remote/test-fixtures/plan-cost-estimation/ce.log
  backend/remote/test-fixtures/plan-cost-estimation/main.tf
  backend/remote/test-fixtures/plan-cost-estimation/plan.log
  backend/remote/testing.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-tfe/cost_estimation.go
  vendor/github.com/hashicorp/go-tfe/organization.go
  vendor/github.com/hashicorp/go-tfe/run.go
  vendor/github.com/hashicorp/go-tfe/tfe.go
  vendor/modules.txt
Labels: backend/remote, enhancement

#21143 command/format: take noop changes from lcs
  command/format/diff.go
  command/format/diff_test.go
Labels: cli

#21139 Make sure UIInput keeps working after being canceled
  command/ui_input.go
  command/ui_input_test.go
Labels: bug, core, enhancement

#21134 vendor: go get github.com/zclconf/go-cty@master
  go.mod
  go.sum
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go
  vendor/modules.txt
Labels: bug, config, crash, dependencies

#21140 Make sure UIInput keeps working after being canceled
  command/ui_input.go
  command/ui_input_test.go
Labels: bug, core, enhancement

#20044 [WIP] Re-enable the end-to-end tests
  command/e2etest/automation_test.go
  command/e2etest/init_test.go
  command/e2etest/main_test.go
  command/e2etest/primary_test.go
  command/e2etest/test-fixtures/plugin-cache/cache/os_arch/terraform-provider-template_v2.1.0_x4
  command/e2etest/test-fixtures/plugin-cache/main.tf
  e2e/e2e.go
  plugin/discovery/get.go
Labels: build

#21146 Stop grpc server when running ACC tests
  helper/resource/grpc_test_provider.go
  plugin/grpc_provider.go
Labels: provider-sdk

#21148 backend/remote: do not unlock after a failed upload
  backend/remote/backend_state.go
Labels: backend/remote, enhancement

#21147 backend/remote: do not unlock after a failed upload
  backend/remote/backend_state.go
Labels: backend/remote, enhancement

#21165 update go-plugin
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-plugin/client.go
  vendor/modules.txt
Labels: dependencies

#21166 vendor: go get github.com/zclconf/go-cty@master
  command/format/diff_test.go
  go.mod
  go.sum
  lang/funcs/collection_test.go
  vendor/github.com/zclconf/go-cty/cty/set/iterator.go
  vendor/github.com/zclconf/go-cty/cty/set/ops.go
  vendor/github.com/zclconf/go-cty/cty/set/rules.go
  vendor/github.com/zclconf/go-cty/cty/set_internals.go
  vendor/modules.txt
Labels: config, enhancement
