Repository hashicorp/terraform, pull requests merged in 2019-07, with the labels that each got.

#20018 Change import message to 'prepared'
  command/hook_ui.go
Labels: cli

#21948 update go-getter
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-getter/checksum.go
  vendor/github.com/hashicorp/go-getter/detect_bitbucket.go
  vendor/modules.txt
Labels: upstream

#21957 update hcl2
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression.go
  vendor/modules.txt
Labels: config

#14858 drop empty line on version check
  command/version.go
Labels: cli, enhancement

#17465 Add support for user configured state object names in swift containers
  backend/remote-state/swift/backend.go
  backend/remote-state/swift/backend_state.go
  backend/remote-state/swift/client.go
  website/docs/backends/types/swift.html.md
Labels: backend/swift, enhancement

#21908 deps: github.com/aws/aws-sdk-go@v1.20.10
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/csm/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/enable.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/doc_custom.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/modules.txt
Labels: backend/s3, dependencies, enhancement

#22057 dynamic set blocks produce inconsistent final plan
  builtin/providers/test/resource_nested_set_test.go
  plans/objchange/compatible.go
  plans/objchange/compatible_test.go
Labels: bug, config, core

#22037 monitor ssh connection live-ness
  communicator/ssh/communicator.go
  communicator/ssh/communicator_test.go
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/internal/chacha20/asm_ppc64le.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/openpgp/keys.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/ssh_gss.go
  vendor/modules.txt
Labels: provisioner/remote-exec

#22098 ensure we record diagnostics from nested modules
  command/show_test.go
  command/testdata/show-json/nested-module-error/main.tf
  command/testdata/show-json/nested-module-error/modules/main.tf
  command/testdata/show-json/nested-module-error/modules/more-modules/main.tf
  command/testdata/show-json/nested-modules/modules/more-modules/main.tf
  command/testdata/show-json/nested-modules/output.json
  configs/config_build.go
  configs/config_build_test.go
  configs/testdata/nested-errors/child_a/child_a.tf
  configs/testdata/nested-errors/child_c/child_c.tf
  configs/testdata/nested-errors/root.tf
Labels: bug, config

#22096 [WIP] backend/enhanced: start with absolute configuration path
  backend/remote/backend_plan.go
  backend/remote/backend_plan_test.go
Labels: backend/remote, bug

#22068 fix example config for terraform >= 0.12
  website/docs/providers/terraform/index.html.markdown
Labels: documentation, enhancement, provider/terraform

#21954 Update pingdom community provider url
  website/docs/providers/type/community-index.html.markdown
Labels: bug, documentation

#22044 Allow null values in Compact function
  lang/funcs/collection.go
  lang/funcs/collection_test.go
Labels: bug, config, crash

#21831 Update in terraform output documentation
  website/docs/commands/output.html.markdown
Labels: bug, documentation

#18820 change from work to working directory
  website/docs/commands/init.html.markdown
Labels: bug, documentation

#22119 lang/funcs: Pass through empty list in chunklist
  lang/funcs/collection.go
  lang/funcs/collection_test.go
Labels: bug, config, crash

#22136 states/statefile: additional context for some v3 upgrade error messages
  states/statefile/version3_upgrade.go
Labels: bug, core

#22097 Improve ssh connection debug messages
  communicator/ssh/communicator.go
Labels: enhancement, provisioner/file, provisioner/remote-exec

#19166 Minor edits to improve the reading flow
  website/intro/getting-started/build.html.md
Labels: documentation, enhancement

#21922 Resource for_each
  .tfdev
  addrs/for_each_attr.go
  addrs/parse_ref.go
  addrs/parse_ref_test.go
  configs/configupgrade/analysis_expr.go
  configs/parser_config_test.go
  configs/resource.go
  configs/testdata/invalid-files/data-count-and-for_each.tf
  configs/testdata/invalid-files/resource-count-and-for_each.tf
  lang/data.go
  lang/data_test.go
  lang/eval.go
  lang/eval_test.go
  terraform/context_plan_test.go
  terraform/eval_apply.go
  terraform/eval_diff.go
  terraform/eval_for_each.go
  terraform/eval_read_data.go
  terraform/eval_state.go
  terraform/eval_validate.go
  terraform/evaluate.go
  terraform/graph_builder_plan_test.go
  terraform/node_data_refresh.go
  terraform/node_resource_abstract.go
  terraform/node_resource_apply_instance.go
  terraform/node_resource_plan.go
  terraform/node_resource_plan_instance.go
  terraform/node_resource_refresh.go
  terraform/resource_address.go
  terraform/testdata/plan-for-each/main.tf
  terraform/transform_orphan_count.go
  terraform/transform_resource_count.go
  website/docs/configuration/data-sources.html.md
  website/docs/configuration/expressions.html.md
  website/docs/configuration/resources.html.md
Labels: config, enhancement

#22186 backend/oss: Support for assume role config
  backend/remote-state/oss/backend.go
  backend/remote-state/oss/backend_test.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/assume_role.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/client.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/generate_session_access_key.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/get_caller_identity.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_assumed_role_user.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_credentials.go
  vendor/github.com/aliyun/alibaba-cloud-sdk-go/services/sts/struct_session_access_key.go
  vendor/modules.txt
  website/docs/backends/types/oss.html.md
  website/docs/providers/index.html.markdown
Labels: backend/oss

#22256 Update copy for Exists
  helper/schema/resource.go
Labels: documentation

#22271 website: example of csvdecode with for_each
  website/docs/configuration/functions/csvdecode.html.md
Labels: config, documentation
