Repository hashicorp/terraform, pull requests merged in 2019-12, with the labels that each got.

#23449 addrs: rename Provider Name to more accurate Provider Type
  addrs/provider_type.go
  command/init.go
  command/plugins_test.go
  plugin/discovery/get.go
  plugin/discovery/get_test.go
  tools/terraform-bundle/package.go
Labels: sdkv1

#23550 check for missing Current instance in EachMap
  terraform/evaluate.go
Labels: sdkv1

#23548 providers: use addrs.ProviderType as map keys for provider.Factory
  addrs/provider.go
  addrs/provider_type.go
  backend/local/testing.go
  builtin/providers/test/resource_import_other_test.go
  command/apply_test.go
  command/command_test.go
  command/import_test.go
  command/init.go
  command/internal_plugin_test.go
  command/plugins.go
  command/plugins_test.go
  configs/configupgrade/analysis.go
  configs/configupgrade/upgrade_test.go
  helper/resource/testing.go
  helper/resource/testing_import_state.go
  helper/resource/testing_test.go
  plugin/discovery/get.go
  plugin/discovery/get_test.go
  providers/resolver.go
  repl/session_test.go
  terraform/context.go
  terraform/context_apply_test.go
  terraform/context_components.go
  terraform/context_components_test.go
  terraform/context_fixtures_test.go
  terraform/context_import_test.go
  terraform/context_input_test.go
  terraform/context_plan_test.go
  terraform/context_refresh_test.go
  terraform/context_validate_test.go
  terraform/eval_context_builtin_test.go
  terraform/graph_builder_plan_test.go
  terraform/resource_provider.go
  terraform/resource_provider_mock_test.go
  tools/terraform-bundle/package.go
Labels: sdkv1

#23475 Cleanup SetResourceInstanceCurrent to be clearer and more reliable
  states/module.go
  states/resource.go
  terraform/eval_diff.go
Labels: sdkv1

#23561 Update comment in SetResourceInstanceCurrent
  states/module.go
Labels: sdkv1

#23546 make plan-diff format a bit more dry
  command/format/diff.go
Labels: sdkv1

#17400 Strip flags from internal_plugin args (fixes TF_CLI_ARGS usage)
  command/internal_plugin.go
  command/internal_plugin_test.go
Labels: bug, config

#23559 deprecation warning for destroy provisioner refs
  configs/provisioner.go
  configs/resource.go
  configs/testdata/warning-files/destroy-provisioners.tf
Labels: sdkv1

#23581 Fix panic on show plan
  command/format/diff.go
  command/show_test.go
Labels: sdkv1

#23595 Update destroy provisioner warnings
  command/meta_config.go
  configs/provisioner.go
Labels: sdkv1

#23619 experiments: a mechanism for opt-in experimental language features
  configs/experiments.go
  configs/experiments_test.go
  configs/module.go
  configs/parser_config.go
  configs/testdata/experiments/concluded/concluded_experiment.tf
  configs/testdata/experiments/current/current_experiment.tf
  configs/testdata/experiments/invalid/invalid_experiments.tf
  configs/testdata/experiments/unknown/unknown_experiment.tf
  experiments/doc.go
  experiments/errors.go
  experiments/experiment.go
  experiments/set.go
  experiments/testing.go
Labels: config, enhancement, sdkv1

#22963 Allow s3 backends to contain more then 1000 workspaces
  backend/remote-state/s3/backend_state.go
Labels: backend/s3, bug, v0.12

#23632 command: New -compact-warnings option
  command/apply.go
  command/format/diagnostic.go
  command/format/diagnostic_test.go
  command/meta.go
  command/plan.go
  command/refresh.go
  tfdiags/consolidate_warnings.go
  tfdiags/consolidate_warnings_test.go
  website/docs/commands/apply.html.markdown
  website/docs/commands/plan.html.markdown
  website/docs/commands/refresh.html.markdown
Labels: cli, enhancement, sdkv1

#23613 Mildwonkey/f configs provider
  addrs/module_instance.go
  addrs/provider_config.go
  addrs/provider_config_test.go
  command/import.go
  command/import_test.go
  command/init.go
  command/plugins.go
  configs/provider.go
  configs/provider_requirements.go
  configs/provider_test.go
  plugin/discovery/get.go
  plugin/discovery/get_test.go
  states/statefile/version3_upgrade.go
Labels: sdkv1

#23634 website: Note about using jsonencode/yamlencode in templatefile
  website/docs/configuration/functions/templatefile.html.md
Labels: config, documentation, enhancement

#23644 vendor: go get github.com/hashicorp/hcl/v2@v2.2.0
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
  vendor/github.com/hashicorp/hcl/v2/README.md
  vendor/github.com/hashicorp/hcl/v2/appveyor.yml
  vendor/github.com/hashicorp/hcl/v2/go.mod
  vendor/github.com/hashicorp/hcl/v2/go.sum
  vendor/github.com/hashicorp/hcl/v2/gohcl/decode.go
  vendor/github.com/hashicorp/hcl/v2/hcldec/spec.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_body.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/ast_expression.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/generate.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion_primitive.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/format.go
  vendor/github.com/zclconf/go-cty/cty/gob.go
  vendor/github.com/zclconf/go-cty/cty/set_internals.go
  vendor/modules.txt
Labels: cli, dependencies, enhancement

#23663 check resource-level connections block for references
  terraform/context_apply_test.go
  terraform/node_resource_abstract.go
  terraform/provisioner_mock.go
  terraform/testdata/apply-plan-connection-refs/main.tf
Labels: sdkv1

#23656 Add a backend-specific env var for the GCS backend.
  backend/remote-state/gcs/backend.go
  website/docs/backends/types/gcs.html.md
Labels: backend/gcs, enhancement

#23265 Update Output values docs
  website/docs/configuration/outputs.html.md
Labels: documentation

#23696 NodeDestroyResource does not need a provider
  terraform/graph_builder_apply_test.go
  terraform/node_resource_destroy.go
  terraform/testdata/graph-builder-orphan-alias/main.tf
Labels: sdkv1

#23151 Correct simple typo in `walk.go`.
  dag/walk.go
Labels: sdkv1
