Repository hashicorp/terraform, pull requests merged in 2020-04, with the labels that each got.

#24522 Mildwonkey/tests
  command/providers.go
  terraform/context_components_test.go
  terraform/context_refresh_test.go
  terraform/context_test.go
  terraform/context_validate_test.go
  terraform/eval_context_builtin_test.go
  terraform/eval_provider_test.go
  terraform/eval_state_test.go
  terraform/evaluate_valid_test.go
  terraform/graph_builder_apply_test.go
  terraform/graph_builder_plan_test.go
  terraform/graph_builder_refresh_test.go
  terraform/module_dependencies.go
  terraform/module_dependencies_test.go
  terraform/node_data_refresh_test.go
  terraform/resource_provider_mock_test.go
  terraform/schemas_test.go
  terraform/terraform_test.go
  terraform/testdata/transform-provider-fqns-module/child/main.tf
  terraform/testdata/transform-provider-fqns-module/main.tf
  terraform/testdata/transform-provider-fqns/main.tf
  terraform/transform_destroy_cbd_test.go
  terraform/transform_destroy_edge_test.go
  terraform/transform_diff_test.go
  terraform/transform_orphan_count_test.go
  terraform/transform_orphan_resource_test.go
  terraform/transform_provider_test.go
  terraform/transform_provisioner_test.go
  terraform/transform_root_test.go
  terraform/transform_transitive_reduction_test.go
Labels: sdkv1

#24523 command: Add state replace-provider subcommand
  addrs/provider.go
  command/state_meta.go
  command/state_replace_provider.go
  command/state_replace_provider_test.go
  commands.go
Labels: sdkv1

#24535 Mildwonkey/command tests
  command/command_test.go
  command/format/state.go
  command/graph_test.go
  command/jsonplan/plan.go
  command/jsonplan/values.go
  command/jsonplan/values_test.go
  command/jsonprovider/provider.go
  command/jsonstate/state.go
  command/jsonstate/state_test.go
  command/plan_test.go
  command/refresh_test.go
  command/show_test.go
  command/state_show_test.go
  command/testdata/providers-schema/basic/output.json
  command/testdata/show-json-state/basic/terraform.tfstate
  command/testdata/show-json-state/modules/output.json
  command/testdata/show-json-state/modules/terraform.tfstate
  command/testdata/show-json/basic-create/output.json
  command/testdata/show-json/basic-delete/output.json
  command/testdata/show-json/basic-delete/terraform.tfstate
  command/testdata/show-json/basic-update/output.json
  command/testdata/show-json/basic-update/terraform.tfstate
  command/testdata/show-json/modules/output.json
  command/testdata/show-json/multi-resource-update/output.json
  command/testdata/show-json/multi-resource-update/terraform.tfstate
  command/testdata/show-json/nested-modules/output.json
Labels: sdkv1

#24540 command/jsonconfig: Use correct provider address to access schema
  command/jsonconfig/config.go
  command/jsonplan/plan.go
  command/jsonstate/state.go
Labels: cli, enhancement

#24539 handle orphaned instances in expanded modules
  terraform/context_apply_test.go
  terraform/context_plan_test.go
  terraform/graph_builder_apply.go
  terraform/graph_builder_apply_test.go
  terraform/graph_builder_destroy_plan.go
  terraform/graph_builder_eval.go
  terraform/graph_builder_import.go
  terraform/graph_builder_plan.go
  terraform/graph_builder_refresh.go
  terraform/graph_builder_refresh_test.go
  terraform/node_data_refresh.go
  terraform/node_local.go
  terraform/node_module_expand.go
  terraform/node_module_variable.go
  terraform/node_output.go
  terraform/node_resource_apply.go
  terraform/node_resource_destroy.go
  terraform/node_resource_plan.go
  terraform/node_resource_refresh.go
  terraform/node_value.go
  terraform/transform_module_expansion.go
  terraform/transform_orphan_count.go
  terraform/transform_orphan_resource.go
  terraform/transform_provider.go
  terraform/transform_reference.go
  terraform/transform_root.go
Labels: sdkv1

#24545 addrs: Simplify presentation of provider FQNs
  addrs/provider.go
  addrs/provider_test.go
  command/init.go
Labels: sdkv1

#24562 don't call os.NewFile on unknown FDs
  helper/wrappedstreams/streams.go
  helper/wrappedstreams/streams_other.go
Labels: sdkv1

#24565 Create module validation nodes
  terraform/context_validate_test.go
  terraform/graph_builder_plan.go
  terraform/graph_builder_validate.go
  terraform/node_module_expand.go
  terraform/transform_module_expansion.go
Labels: sdkv1

#24554 internal/getproviders: Tidy up some confusion about package hashes
  internal/getproviders/package_authentication.go
  internal/getproviders/registry_client.go
  internal/getproviders/registry_source_test.go
  internal/getproviders/types.go
  internal/providercache/dir_modify.go
Labels: cli, enhancement

#24575 Enable count.index and each.key/value in module expansion
  terraform/eval_context_builtin.go
  terraform/eval_variable.go
  terraform/evaluate.go
  terraform/node_module_variable.go
  terraform/testdata/plan-modules-expand/main.tf
Labels: sdkv1

#24576 internal/getproviders: Tests for MultiSource
  internal/getproviders/multi_source_test.go
Labels: cli, enhancement

#24577 internal/getproviders: Tests for MemoizeSource
  internal/getproviders/memoize_source_test.go
Labels: cli, enhancement

#24587 don't allow count && for_each in module calls
  configs/module_call.go
  configs/module_call_test.go
Labels: sdkv1

#24525 Updating import usage doc with accurate example of complex import with secondary resources
  website/docs/import/usage.html.md
Labels: documentation

#24574 Point module references to the close node
  dag/walk.go
  terraform/node_module_expand.go
  terraform/node_module_removed.go
  terraform/transform_module_expansion.go
  terraform/transform_reference.go
  terraform/transform_removed_modules.go
Labels: sdkv1

#24599 Fix races in GetVariableValue and login
  command/login.go
  states/statemgr/filesystem_test.go
  terraform/eval_context_builtin.go
  terraform/hook_test.go
Labels: sdkv1

#24605 Allow module variables to pass validation
  terraform/context_validate_test.go
  terraform/eval_apply.go
  terraform/eval_count.go
  terraform/eval_diff.go
  terraform/eval_for_each.go
  terraform/eval_for_each_test.go
  terraform/eval_read_data.go
  terraform/eval_state.go
  terraform/eval_validate.go
  terraform/eval_variable.go
  terraform/node_data_refresh.go
  terraform/node_module_expand.go
  terraform/node_module_variable.go
  terraform/node_module_variable_test.go
  terraform/node_resource_refresh.go
  terraform/node_root_variable.go
  terraform/transform_module_variable.go
Labels: sdkv1

#24155 Keep s3 docs in line with functionality
  website/docs/modules/sources.html.markdown
Labels: documentation

#24502 Fix a typo in the Graylog provider name
  website/docs/providers/type/community-index.html.markdown
Labels: documentation

#24609 Fix typo in maintainer-etiquette
  docs/maintainer-etiquette.md
Labels: documentation

#24623 Correctly connect module output references during plan
  addrs/module_call.go
  states/state_string.go
  terraform/context_apply_test.go
  terraform/transform_reference.go
Labels: sdkv1

#24531 Fix typos
  helper/schema/core_schema.go
  states/statemgr/locker.go
Labels: sdkv1

#24650 vendor: go get github.com/hashicorp/hcl/v2@v2.4.0
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/LICENSE
  vendor/github.com/apparentlymart/go-textseg/textseg/all_tokens.go
  vendor/github.com/apparentlymart/go-textseg/textseg/generate.go
  vendor/github.com/apparentlymart/go-textseg/textseg/grapheme_clusters.go
  vendor/github.com/apparentlymart/go-textseg/textseg/grapheme_clusters.rl
  vendor/github.com/apparentlymart/go-textseg/textseg/grapheme_clusters_table.rl
  vendor/github.com/apparentlymart/go-textseg/textseg/tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/unicode2ragel.rb
  vendor/github.com/apparentlymart/go-textseg/textseg/utf8_seqs.go
  vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
  vendor/github.com/hashicorp/hcl/v2/go.mod
  vendor/github.com/hashicorp/hcl/v2/go.sum
  vendor/github.com/hashicorp/hcl/v2/gohcl/doc.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser_template.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/spec.md
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/token.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/tokens.go
  vendor/github.com/hashicorp/hcl/v2/json/scanner.go
  vendor/github.com/hashicorp/hcl/v2/pos_scanner.go
  vendor/modules.txt
Labels: dependencies

#24666 Feature: Sum Function
  lang/funcs/collection.go
  lang/funcs/collection_test.go
  lang/functions.go
  lang/functions_test.go
  website/docs/configuration/functions/sum.html.md
  website/layouts/functions.erb
Labels: sdkv1

#24685 tests: Added tests to exercise hyphenated providers
  addrs/provider_test.go
  command/init_test.go
  command/testdata/init-required-providers/main.tf
  internal/getproviders/filesystem_mirror_source_test.go
  internal/getproviders/testdata/filesystem-mirror/registry.terraform.io/hashicorp/random-beta/1.2.0/linux_amd64/terraform-provider-random-beta
  internal/providercache/dir_test.go
  internal/providercache/testdata/cachedir/registry.terraform.io/hashicorp/random-beta/1.2.0/linux_amd64/terraform-provider-random-beta
Labels: sdkv1

#24689 main: skip direct provider installation for providers available locally
  command/e2etest/init_test.go
  command/e2etest/testdata/local-only-provider/main.tf
  command/e2etest/testdata/local-only-provider/terraform.d/plugins/example.com/awesomecorp/happycloud/1.2.0/os_arch/terraform-provider-happycloud_v1.2.0
  provider_source.go
Labels: cli, enhancement

#24715 terraform: return `initialization required` error when provider schemas not found
  command/plan_test.go
  terraform/context.go
  terraform/resource_provider.go
Labels: sdkv1

#24533 Add FreeIPA provider
  website/docs/providers/type/community-index.html.markdown
Labels: documentation

#24697 Always return all module instances during evaluation
  addrs/parse_ref.go
  addrs/parse_ref_test.go
  lang/data.go
  lang/data_test.go
  lang/eval.go
  lang/eval_test.go
  plans/changes.go
  plans/changes_sync.go
  repl/session_test.go
  states/module.go
  states/output_value.go
  states/state.go
  states/state_deepcopy.go
  states/state_test.go
  states/statefile/version4.go
  states/sync.go
  terraform/context_plan_test.go
  terraform/context_validate_test.go
  terraform/evaluate.go
Labels: sdkv1

#24479 Update doco to add reference TF_IGNORE environment variable
  website/docs/commands/environment-variables.html.md
Labels: documentation

#24728 Explicit provider installation source configuration
  command/cliconfig/cliconfig.go
  command/cliconfig/cliconfig_test.go
  command/cliconfig/provider_installation.go
  command/cliconfig/provider_installation_test.go
  command/cliconfig/testdata/provider-installation
  command/cliconfig/testdata/provider-installation-errors
  command/cliconfig/testdata/provider-installation.json
  command/e2etest/init_test.go
  command/e2etest/testdata/custom-provider-install-method/cliconfig.tfrc
  command/e2etest/testdata/custom-provider-install-method/cliconfig.tfrc.json
  command/e2etest/testdata/custom-provider-install-method/fs-mirror/example.com/awesomecorp/happycloud/1.2.0/os_arch/terraform-provider-happycloud_v1.2.0
  command/e2etest/testdata/custom-provider-install-method/main.tf
  internal/getproviders/http_mirror_source.go
  main.go
  provider_source.go
  website/docs/commands/cli-config.html.markdown
  website/docs/configuration/providers.html.md
Labels: cli, enhancement

#24752 website: Add docs for state replace-provider
  command/state_replace_provider.go
  website/docs/commands/state/replace-provider.html.md
  website/layouts/commands-state.erb
Labels: documentation

#24763 configs: Simplify required_providers blocks
  configs/config.go
  configs/module.go
  configs/module_merge.go
  configs/module_merge_test.go
  configs/module_test.go
  configs/parser_config.go
  configs/provider_requirements.go
  configs/provider_requirements_test.go
  configs/testdata/invalid-modules/multiple-required-providers/a.tf
  configs/testdata/invalid-modules/multiple-required-providers/b.tf
  configs/testdata/valid-modules/required-providers-after-resource/main.tf
  configs/testdata/valid-modules/required-providers-after-resource/providers.tf
  configs/testdata/valid-modules/required-providers-overrides/bar_provider_override.tf
  configs/testdata/valid-modules/required-providers-overrides/main.tf
  configs/testdata/valid-modules/required-providers-overrides/providers.tf
Labels: sdkv1

#24780 Add expansion transformer to eval graph
  terraform/graph_builder_eval.go
Labels: sdkv1

#24786 Update CHANGELOG.md for swift authentication
  CHANGELOG.md
Labels: backend/swift

#24445 Add reference to new modules track
  website/docs/modules/index.html.markdown
Labels: documentation

#24783 configs: Fix for resources with implied providers
  configs/module.go
  configs/module_test.go
  configs/testdata/valid-modules/implied-providers/providers.tf
  configs/testdata/valid-modules/implied-providers/resources.tf
Labels: sdkv1

#24751 Resource (and module) evaluate improvements
  terraform/evaluate.go
Labels: sdkv1

#24808 Support reading module outputs in terraform console
  command/console_test.go
  command/testdata/modules/.terraform/modules/modules.json
  command/testdata/modules/child/main.tf
  command/testdata/modules/main.tf
  command/testdata/modules/terraform.tfstate
  terraform/node_output.go
Labels: sdkv1
