Repository hashicorp/terraform, pull requests merged in 2020-05, with the labels that each got.

#24807 Remove EachMode from state
  command/jsonstate/state.go
  command/jsonstate/state_test.go
  command/state_mv.go
  command/state_mv_test.go
  states/eachmode_string.go
  states/module.go
  states/resource.go
  states/state_deepcopy.go
  states/state_test.go
  states/statefile/version4.go
  states/statemgr/testing.go
  states/sync.go
  terraform/context_apply_test.go
  terraform/eval_state.go
  terraform/evaluate.go
Labels: sdkv1

#24484 fix typo in Base64DecodeFunc log
  lang/funcs/encoding.go
Labels: sdkv1

#24696 Add support for force pushing with the remote backend
  backend/remote/backend_state.go
  state/remote/remote.go
  state/remote/remote_test.go
  state/remote/state.go
  state/remote/state_test.go
Labels: backend/remote, terraform-cloud

#24884 Backport remote backend force push to v0.12
  backend/remote/backend_state.go
  state/remote/remote.go
  state/remote/remote_test.go
  state/remote/state.go
  state/remote/state_test.go
Labels: backend/remote, terraform-cloud

#24846 getproviders: move protocol compatibility functions into registry client
  addrs/provider.go
  command/init.go
  internal/getproviders/errors.go
  internal/getproviders/registry_client.go
  internal/getproviders/registry_client_test.go
  internal/getproviders/registry_source.go
  internal/getproviders/registry_source_test.go
  internal/getproviders/types.go
  internal/providercache/installer.go
  internal/providercache/installer_test.go
Labels: sdkv1

#19155 Chef: Gracefully Handle RFC062 Exit Codes
  builtin/provisioners/chef/resource_provisioner.go
  communicator/winrm/communicator.go
  website/docs/provisioners/chef.html.markdown
Labels: enhancement, provisioner/chef

#24942 website/docs: provider aliases in the JSON format
  website/docs/configuration/syntax-json.html.md
Labels: documentation

#23146 Add info on dynamodb locking multiple state files as per issue #15303
  website/docs/backends/types/s3.html.md
Labels: backend/s3, documentation, enhancement, sdkv1

#24952 vendor: go get github.com/hashicorp/hcl/v2@v2.5.1
  go.mod
  go.sum
  vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/parser.go
  vendor/github.com/hashicorp/hcl/v2/hclwrite/parser.go
  vendor/modules.txt
Labels: dependencies

#24319 improve s3.html.md
  website/docs/backends/types/s3.html.md
Labels: documentation

#22826 local backend example added
  website/docs/providers/terraform/d/remote_state.html.md
Labels: backend/local, documentation, enhancement

#25054 configs: Custom variable validation is no longer experimental
  configs/experiments.go
  configs/testdata/invalid-files/variable-validation-bad-msg.tf
  configs/testdata/invalid-files/variable-validation-condition-badref.tf
  configs/testdata/invalid-files/variable-validation-condition-noref.tf
  configs/testdata/invalid-modules/variable-validation-without-optin/variable-validation-without-optin.tf
  configs/testdata/valid-files/variable_validation.tf
  experiments/experiment.go
  terraform/context_validate_test.go
  terraform/testdata/validate-variable-custom-validations-child/child/child.tf
  website/docs/configuration/functions/can.html.md
  website/docs/configuration/variables.html.md
Labels: config, enhancement
