Repository hashicorp/terraform, pull requests merged in 2020-06, with the labels that each got.

#25101 website: Draw better attention to for and for_each patterns
  website/docs/configuration/expressions.html.md
  website/docs/configuration/resources.html.md
Labels: config, documentation

#25127 Add `-yes` flag to 0.13upgrade help message
  command/013_config_upgrade.go
Labels: v0.13

#22885 fix default state file path for refresh command
  command/refresh.go
Labels: bug, cli, v0.12

#24600 internal/modsdir: Fix Dropped Error
  internal/modsdir/manifest.go
Labels: sdkv1

#21312 Update error message for apply validation
  plans/objchange/compatible.go
  terraform/eval_apply.go
Labels: bug, core

#25134 backend/s3: Updates for Terraform v0.13.0
  backend/remote-state/s3/backend.go
  backend/remote-state/s3/backend_test.go
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/decode.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/types.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/checksum/content_md5.go
  vendor/github.com/aws/aws-sdk-go/service/dynamodb/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/body_hash.go
  vendor/github.com/aws/aws-sdk-go/service/s3/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/s3/statusok_error.go
  vendor/github.com/aws/aws-sdk-go/service/s3/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/hashicorp/aws-sdk-go-base/.golangci.yml
  vendor/github.com/hashicorp/aws-sdk-go-base/.travis.yml
  vendor/github.com/hashicorp/aws-sdk-go-base/CHANGELOG.md
  vendor/github.com/hashicorp/aws-sdk-go-base/awsauth.go
  vendor/github.com/hashicorp/aws-sdk-go-base/awserr.go
  vendor/github.com/hashicorp/aws-sdk-go-base/config.go
  vendor/github.com/hashicorp/aws-sdk-go-base/endpoints.go
  vendor/github.com/hashicorp/aws-sdk-go-base/errors.go
  vendor/github.com/hashicorp/aws-sdk-go-base/go.mod
  vendor/github.com/hashicorp/aws-sdk-go-base/go.sum
  vendor/github.com/hashicorp/aws-sdk-go-base/mock.go
  vendor/github.com/hashicorp/aws-sdk-go-base/session.go
  vendor/modules.txt
  website/docs/backends/types/s3.html.md
Labels: backend/s3, breaking-change, bug, enhancement

#25234 Remove BUILDING.md docs
  BUILDING.md
Labels: documentation

#25273 vendor: update go-cty-yaml
  go.mod
  go.sum
  lang/functions_test.go
  vendor/github.com/zclconf/go-cty-yaml/CHANGELOG.md
  vendor/github.com/zclconf/go-cty-yaml/resolve.go
  vendor/modules.txt
Labels: dependencies

#25341 prevent panic in remote backend retry
  backend/remote/backend.go
Labels: v0.12, v0.13

#25355 add note re. SSH host key validation to provisioner connection doc
  website/docs/provisioners/connection.html.markdown
Labels: documentation

#25339 Trimprefix: what happens when prefix is not in string?
  website/docs/configuration/functions/trimprefix.html.md
Labels: documentation

#25361 lang/funcs: Filesystem functions hint about dynamically-generated files
  lang/funcs/filesystem.go
  lang/funcs/filesystem_test.go
Labels: config, enhancement

#22300 command: adjust exit code of state rm
  command/state_rm.go
  command/state_rm_test.go
Labels: breaking-change, bug, cli

#25376 website: Restore the docs for "terraform 0.12upgrade"
  website/docs/commands/0.12upgrade.html.markdown
  website/docs/commands/0.13upgrade.html.markdown
  website/layouts/docs.erb
Labels: cli, documentation

#24069 Azure backend: support snapshots/versioning
  backend/remote-state/azure/backend.go
  backend/remote-state/azure/backend_state.go
  backend/remote-state/azure/backend_test.go
  backend/remote-state/azure/client.go
  website/docs/backends/types/azurerm.html.md
Labels: backend/azure, enhancement

#25113 website: Terraform v0.13 upgrade guide
  website/docs/configuration/provider-requirements.html.md
  website/layouts/guides.erb
  website/upgrade-guides/0-13.html.markdown
Labels: documentation

#25394 Document swift support for locks
  website/docs/backends/types/swift.html.md
Labels: documentation
