Repository hashicorp/terraform, pull requests merged in 2020-09, with the labels that each got.

#26069 docs: Provider protocol wire format for values
  docs/plugin-protocol/object-wire-format.md
Labels: documentation, enhancement

#25439 backend/http: add support for configuration by environment variable
  backend/remote-state/http/backend.go
  backend/remote-state/http/backend_test.go
  website/docs/backends/types/http.html.md
Labels: backend/http

#26098 Small typo in the internals link to the provider network mirror protocol
  website/docs/commands/cli-config.html.markdown
Labels: documentation

#26085 Clarify `locals` vs. `local.thing` distinction
  website/docs/configuration/locals.html.md
  website/docs/configuration/variables.html.md
Labels: documentation

#25729 Return an error on unlock failure
  command/clistate/state.go
  command/clistate/state_test.go
Labels: breaking-change

#26087 main: new global option -chdir
  command/e2etest/primary_test.go
  command/e2etest/testdata/chdir-option/subdir/main.tf
  command/meta.go
  commands.go
  e2e/e2e.go
  help.go
  main.go
  terraform/context.go
  terraform/evaluate.go
  website/docs/commands/apply.html.markdown
  website/docs/commands/console.html.markdown
  website/docs/commands/destroy.html.markdown
  website/docs/commands/force-unlock.html.markdown
  website/docs/commands/get.html.markdown
  website/docs/commands/graph.html.markdown
  website/docs/commands/index.html.markdown
  website/docs/commands/init.html.markdown
  website/docs/commands/plan.html.markdown
  website/docs/commands/providers.html.markdown
  website/docs/commands/refresh.html.markdown
  website/docs/commands/show.html.markdown
  website/docs/commands/validate.html.markdown
Labels: cli, enhancement

#26188 Backport 26186
  terraform/context_apply_test.go
  terraform/transform_module_expansion.go
Labels: v0.13

#26204 website: Add Google and Microsoft products to the summary for supported remote backends
  website/docs/state/remote.html.md
Labels: documentation

#25842 Sanitize lock path for the Consul backend when it ends with a /
  backend/remote-state/consul/backend_test.go
  backend/remote-state/consul/client.go
  backend/remote-state/consul/client_test.go
Labels: backend/consul

#26222 website: Adding a note around data-sources and depends_on for 0.12 users
  website/docs/configuration/data-sources.html.md
Labels: documentation

#26181 website: Fix docs for implied provider FS mirrors
  website/docs/commands/cli-config.html.markdown
Labels: documentation

#26244 website: Credentials helper response for no creds
  website/docs/internals/credentials-helpers.html.md
Labels: documentation

#25656 lang/funcs: Add "alltrue" function
  lang/funcs/collection.go
  lang/funcs/collection_test.go
  lang/functions.go
  lang/functions_test.go
  website/docs/configuration/functions/alltrue.html.md
  website/layouts/functions.erb
Labels: config, enhancement

#26337 docs: Vendor provisioner deprecation version
  website/docs/provisioners/chef.html.markdown
  website/docs/provisioners/habitat.html.markdown
  website/docs/provisioners/puppet.html.markdown
  website/docs/provisioners/salt-masterless.html.md
Labels: documentation

#26390 command/fmt: Restore some more-opinionated behaviors
  command/fmt.go
  command/fmt_test.go
  command/testdata/fmt/general_in.tf
  command/testdata/fmt/general_out.tf
  command/testdata/fmt/variable_type_in.tf
  command/testdata/fmt/variable_type_out.tf
Labels: cli, enhancement

#22467 Fix taint and untaint commands when in a workspace
  command/command_test.go
  command/taint.go
  command/taint_test.go
  command/untaint.go
  command/untaint_test.go
Labels: bug, cli

#26241 website: Terraform import and remote backends
  website/docs/import/index.html.md
  website/docs/import/usage.html.md
Labels: documentation

#25029 Update templatefile documentation
  website/docs/configuration/functions/templatefile.html.md
Labels: documentation

#26307 Update apply.html.markdown
  website/docs/commands/apply.html.markdown
Labels: documentation

#26403 command/init: Better error message for provider unsupported platform
  command/init.go
Labels: cli, enhancement

#26424 command/init: Remove support for legacy provider addresses
  command/e2etest/init_test.go
  command/init.go
  command/init_test.go
  internal/getproviders/legacy_lookup.go
  internal/getproviders/legacy_lookup_test.go
  internal/getproviders/registry_client.go
  internal/getproviders/registry_source.go
Labels: cli, enhancement
