Repository hashicorp/terraform, pull requests merged in 2020-08, with the labels that each got.

#25721 website: Documentation about the one-to-one object binding assumption
  website/docs/commands/import.html.md
  website/docs/import/index.html.md
  website/docs/import/usage.html.md
  website/docs/state/index.html.md
  website/docs/state/purpose.html.md
Labels: documentation, enhancement

#25792 Fix sidebar link for Terraform standard backends to include link to Kubernetes backend docs
  website/layouts/backend-types.erb
Labels: documentation

#25844 Update publishing.html.md
  website/docs/registry/providers/publishing.html.md
Labels: documentation

#25903 backend/s3: Update aws-sdk-go-base to v0.6.0
  backend/remote-state/s3/backend_test.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/aws-sdk-go-base/CHANGELOG.md
  vendor/github.com/hashicorp/aws-sdk-go-base/README.md
  vendor/github.com/hashicorp/aws-sdk-go-base/awsauth.go
  vendor/github.com/hashicorp/aws-sdk-go-base/awserr.go
  vendor/github.com/hashicorp/aws-sdk-go-base/mock.go
  vendor/github.com/hashicorp/aws-sdk-go-base/session.go
  vendor/github.com/hashicorp/aws-sdk-go-base/tfawserr/awserr.go
  vendor/modules.txt
  website/docs/backends/types/s3.html.md
Labels: backend/s3, dependencies, enhancement

#25692 internal/getproviders: Allow basedir for local search to be symlink
  internal/getproviders/filesystem_search.go
  internal/getproviders/filesystem_search_test.go
  internal/getproviders/testdata/search-local-directory/symlinks/real/example.com/foo/bar/1.0.0/linux_amd64/terraform-provider-bar
  internal/getproviders/testdata/search-local-directory/symlinks/real/example.net
  internal/getproviders/testdata/search-local-directory/symlinks/symlink
Labels: bug, cli, v0.13

#25811 terraform version: fix output order
  command/version.go
  command/version_test.go
Labels: bug

#25857 allow plan data state comparison with legacy SDK
  terraform/eval_read_data_plan.go
  terraform/eval_read_data_plan_test.go
Labels: core

#25890 terraform: Eval module call arguments for import
  command/import_test.go
  command/testdata/import-module-input-variable/child/main.tf
  command/testdata/import-module-input-variable/main.tf
  command/testdata/import-module-input-variable/terraform.tfvars
  terraform/node_module_variable.go
Labels: import

#25770 backend/azurerm: support for authenticating using a Client Certificate
  backend/remote-state/azure/arm_client.go
  backend/remote-state/azure/backend.go
  backend/remote-state/azure/backend_test.go
  website/docs/backends/types/azurerm.html.md
Labels: backend/azure

#25901 Updating links for cloud init guide in docs
  website/docs/provisioners/index.html.markdown
Labels: documentation

#25917 terraform-bundle: initial changelog
  tools/terraform-bundle/CHANGELOG.md
Labels: documentation

#25585 fix ossbackend only returned 100 workspaces
  backend/remote-state/oss/backend_state.go
  backend/remote-state/oss/backend_test.go
Labels: backend/oss

#25994 website: Provider requirements are not inherited
  website/docs/configuration/modules.html.md
Labels: documentation

#25992 build: Use go 1.14.7
  .go-version
Labels: build

#26037 Update publishing.html.md
  website/docs/registry/providers/publishing.html.md
Labels: documentation
