Repository hashicorp/terraform, pull requests merged in 2020-11, with the labels that each got.

#26784 backend: Only show root module output changes
  backend/local/backend_plan.go
  backend/local/testdata/plan-outputs-changed/main.tf
  backend/local/testdata/plan-outputs-changed/submodule/main.tf
Labels: 0.14-backport

#26450 website: Update resources.html.md
  website/docs/configuration/resources.html.md
Labels: documentation

#26758 Website: fixed spelling error
  website/docs/state/index.html.md
Labels: documentation

#26788 allow path and terraform in self-block eval
  lang/eval.go
  lang/eval_test.go
Labels: 0.14-backport

#26802 docs: Fix typo (provider arg in data source)
  website/docs/configuration/data-sources.html.md
Labels: 0.14-backport, documentation

#26762 Upgrade go-getter to v1.5.0
  go.mod
  go.sum
  internal/providercache/package_install.go
Labels: 0.14-backport

#26783 getproviders: Normalize versions before dedupe
  internal/getproviders/types.go
  internal/getproviders/types_test.go
Labels: 0.14-backport

#26818 lang/funcs: Remove the deprecated "list" and "map" functions
  lang/funcs/collection.go
  lang/funcs/collection_test.go
  lang/functions_test.go
  terraform/testdata/apply-resource-scale-in/main.tf
  terraform/testdata/plan-for-each/main.tf
  website/docs/configuration/functions/list.html.md
  website/docs/configuration/functions/map.html.md
Labels: config, enhancement

#26827 Update zclconf/go-cty dependency
  go.mod
  go.sum
Labels: 0.14-backport

#26835 Website: Update lookup.html.md
  website/docs/configuration/functions/lookup.html.md
Labels: documentation

#26700 backend: Add service account impersonation to GCS Backend and update the docs
  backend/remote-state/gcs/backend.go
  go.mod
  go.sum
  website/docs/backends/types/gcs.html.md
Labels: 0.14-backport, backend/gcs

#26832 Mark variables as sensitive (if relevant) in validate
  terraform/context_validate_test.go
  terraform/evaluate.go
Labels: 0.14-backport

#26837 backend: Add service account impersonation to GCS Backend and update the docs
  backend/remote-state/gcs/backend.go
  go.mod
  go.sum
  website/docs/backends/types/gcs.html.md
Labels: backend/gcs

#26761 terraform: Compare locks and provider requirements
  command/meta.go
  terraform/context.go
  terraform/context_test.go
Labels: 0.14-backport, cli

#26844 website: Update output command docs
  website/docs/commands/output.html.markdown
Labels: 0.14-backport, documentation

#26841 backend/gcs: remove deprecated "path" config argument
  backend/remote-state/gcs/backend.go
  backend/remote-state/gcs/backend_state.go
  backend/remote-state/gcs/backend_test.go
  website/docs/backends/types/gcs.html.md
Labels: 0.14-backport, backend/gcs

#26836 builtin/provider/terraform: Add field descriptions
  builtin/providers/terraform/data_source_state.go
Labels: documentation

#26845 website: update link to new varibles tutorial
  website/docs/configuration/variables.html.md
Labels: documentation

#26874 Update delete.html.md
  website/docs/commands/workspace/delete.html.md
Labels: 0.14-backport, documentation

#26877 Backport of Update delete.html.md into v0.14
  website/docs/commands/workspace/delete.html.md
Labels: documentation

#26871 configs: Fix provider lookup local name mismatch
  configs/resource.go
  terraform/evaluate_valid_test.go
  terraform/testdata/static-validate-refs/static-validate-refs.tf
Labels: 0.14-backport, config

#26873 website: Initial docs about the APT/Yum repositories
  website/docs/cli/install/apt.html.md
  website/docs/cli/install/yum.html.md
  website/layouts/downloads.erb
Labels: 0.13-backport, 0.14-backport, documentation, enhancement

#26886 Update libpq
  go.mod
  go.sum
Labels: 0.14-backport, backend/pg

#26865 Support for remote_exec on Windows SSH
  communicator/ssh/communicator.go
  communicator/ssh/provisioner.go
  communicator/ssh/provisioner_test.go
  terraform/eval_validate.go
  website/docs/provisioners/connection.html.markdown
Labels: provisioner/remote-exec

#26914 Update go-getter to v1.5.1 with support for vhost style S3 paths
  go.mod
  go.sum
  website/docs/modules/sources.html.markdown
Labels: 0.14-backport, bug, dependencies

#26799 Remove redundant Local Named Values section
  website/docs/configuration/expressions.html.md
Labels: 0.14-backport, documentation

#26766 lang/funcs: Experimental "defaults" function
  lang/funcs/defaults.go
  lang/funcs/defaults_test.go
  lang/functions.go
  lang/functions_test.go
  lang/scope.go
  terraform/eval_context_builtin.go
  website/docs/configuration/functions/defaults.html.md
  website/layouts/language.erb
Labels: config, enhancement, experiment/module_variable_optional_attrs

#26756 switch to hashicorp docker mirror
  .circleci/config.yml
  Dockerfile
Labels: build

#25964 Remove 'system' references from module registry protocol docs.
  website/docs/internals/module-registry-protocol.html.md
Labels: 0.14-backport

#26936 terraform: Unmark provider configuration arguments
  terraform/node_provider.go
  terraform/node_provider_test.go
Labels: 0.14-backport

#26932 website/intro: remove outdated examples section
  website/intro/examples/aws.html.markdown
  website/intro/examples/consul.html.markdown
  website/intro/examples/count.markdown
  website/intro/examples/cross-provider.markdown
  website/intro/examples/index.html.markdown
  website/layouts/intro.erb
Labels: documentation

#26941 website: Document alternatives to terraform_remote_state
  website/docs/providers/terraform/d/remote_state.html.md
Labels: 0.14-backport, documentation, enhancement, hashibot/ignore, provider/terraform

#26944 Don't render a plan for module outputs
  backend/local/backend_plan_test.go
  backend/local/testdata/plan-module-outputs-changed/main.tf
  backend/local/testdata/plan-module-outputs-changed/mod/main.tf
  plans/changes.go
  plans/plan_test.go
Labels: 0.14-backport

#26949 configs: Specialized warning for single-interpolation object keys
  configs/compat_shim.go
  configs/compat_shim_test.go
Labels: config, enhancement

#26951 website: "coalesce" function unifies its argument types
  website/docs/configuration/functions/coalesce.html.md
Labels: config, documentation, enhancement

#26952 website: Reword confusing statement about module sources in TFE
  website/docs/modules/sources.html.markdown
Labels: documentation, modules

#26955 website: Fix confusing example for local-exec provisioner
  website/docs/provisioners/local-exec.html.markdown
Labels: documentation, enhancement

#26954 configs: Emit a warning for backends in nested modules
  configs/config_build.go
  configs/config_build_test.go
  configs/testdata/nested-backend-warning/child/child.tf
  configs/testdata/nested-backend-warning/root.tf
Labels: config, enhancement

#26894 website: Fix a random typo in azurerm backend
  website/docs/backends/types/azurerm.html.md
Labels: documentation

#26967 main: Special error message for invalid top-level command
  main.go
Labels: cli, enhancement

#26964 command: Fix fmt to preserve blank block labels
  command/testdata/fmt/general_in.tf
  command/testdata/fmt/general_out.tf
  go.mod
  go.sum
Labels: 0.14-backport, cli, dependencies

#26966 website: Miscellaneous 0.14 docs backports
  website/docs/backends/legacy-0-8.html.md
  website/docs/commands/0.12upgrade.html.markdown
  website/docs/commands/state/index.html.md
  website/docs/configuration/functions/element.html.md
  website/docs/configuration/functions/lookup.html.md
  website/docs/configuration/provider-requirements.html.md
  website/docs/configuration/syntax-json.html.md
  website/docs/configuration/syntax.html.md
  website/docs/configuration/variables.html.md
  website/docs/configuration/version-constraints.html.md
  website/docs/internals/internal-plugins.html.md
  website/docs/modules/sources.html.markdown
  website/docs/plugins/provider.html.md
  website/docs/providers/type/community-index.html.markdown
  website/docs/registry/index.html.md
  website/docs/registry/modules/publish.html.md
  website/docs/registry/modules/use.html.md
  website/docs/registry/providers/publishing.html.md
  website/docs/state/remote.html.md
  website/intro/vs/chef-puppet.html.markdown
Labels: documentation

#26968 website: Remove registry docs (adopted into terraform-website)
  website/docs/registry/api.html.md
  website/docs/registry/images/registry-issue.png
  website/docs/registry/images/registry1.png
  website/docs/registry/images/registry2.png
  website/docs/registry/images/user-account.png
  website/docs/registry/index.html.md
  website/docs/registry/modules/images/registry-verified.png
  website/docs/registry/modules/publish.html.md
  website/docs/registry/modules/use.html.md
  website/docs/registry/modules/verified.html.md
  website/docs/registry/private.html.md
  website/docs/registry/providers/docs.html.md
  website/docs/registry/providers/images/archived-tier.png
  website/docs/registry/providers/images/community-tier.png
  website/docs/registry/providers/images/github-oauth-permissions.png
  website/docs/registry/providers/images/official-tier.png
  website/docs/registry/providers/images/publishing.png
  website/docs/registry/providers/images/verified-tier.png
  website/docs/registry/providers/index.html.md
  website/docs/registry/providers/os-arch.html.md
  website/docs/registry/providers/publishing.html.md
  website/layouts/registry.erb
Labels: 0.14-backport, documentation

#26986 Unmark values before provider validate call
  terraform/context_components_test.go
  terraform/context_validate_test.go
  terraform/eval_validate.go
  terraform/eval_validate_test.go
  terraform/provider_mock.go
Labels: 0.14-backport

#26947 backend: Validate remote backend Terraform version
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_context.go
  backend/remote/backend_mock.go
  backend/remote/backend_test.go
  command/console.go
  command/graph.go
  command/import.go
  command/init.go
  command/meta.go
  command/meta_backend.go
  command/output.go
  command/providers.go
  command/providers_schema.go
  command/show.go
  command/state_list.go
  command/state_meta.go
  command/state_mv.go
  command/state_pull.go
  command/state_push.go
  command/state_replace_provider.go
  command/state_rm.go
  command/state_show.go
  command/taint.go
  command/untaint.go
  command/workspace_delete.go
  command/workspace_list.go
  command/workspace_new.go
  command/workspace_select.go
  website/docs/commands/import.html.md
  website/docs/commands/state/mv.html.md
  website/docs/commands/state/push.html.md
  website/docs/commands/state/replace-provider.html.md
  website/docs/commands/state/rm.html.md
  website/docs/commands/taint.html.markdown
  website/docs/commands/untaint.html.markdown
Labels: 0.13-backport, 0.14-backport, backend/remote

#26999 Fix diags non-assignment bugs
  lang/eval.go
  terraform/context_validate_test.go
Labels: 0.14-backport

#26987 Backport of website: Remove registry docs (adopted into terraform-website) into v0.14
  website/docs/registry/api.html.md
  website/docs/registry/images/registry-issue.png
  website/docs/registry/images/registry1.png
  website/docs/registry/images/registry2.png
  website/docs/registry/images/user-account.png
  website/docs/registry/index.html.md
  website/docs/registry/modules/images/registry-verified.png
  website/docs/registry/modules/publish.html.md
  website/docs/registry/modules/use.html.md
  website/docs/registry/modules/verified.html.md
  website/docs/registry/private.html.md
  website/docs/registry/providers/docs.html.md
  website/docs/registry/providers/images/archived-tier.png
  website/docs/registry/providers/images/community-tier.png
  website/docs/registry/providers/images/github-oauth-permissions.png
  website/docs/registry/providers/images/official-tier.png
  website/docs/registry/providers/images/publishing.png
  website/docs/registry/providers/images/verified-tier.png
  website/docs/registry/providers/index.html.md
  website/docs/registry/providers/os-arch.html.md
  website/docs/registry/providers/publishing.html.md
  website/layouts/registry.erb
Labels: documentation

#27026 website: More words about "terraform fmt"
  website/docs/commands/fmt.html.markdown
Labels: 0.14-backport

#27045 repl: Display multi-line strings as heredocs
  repl/format.go
  repl/format_test.go
Labels: 0.14-backport, cli

#27055 Upgrade to hcl v2.7.2
  go.mod
  go.sum
Labels: 0.14-backport
