Repository hashicorp/terraform, pull requests merged in 2020-12, with the labels that each got.

#27066 website: Add new learn links, improve legacy landing pages
  website/docs/configuration/blocks/providers/index.html.md
  website/docs/configuration/dependency-lock.html.md
  website/docs/configuration/expressions.html.md
  website/docs/configuration/expressions/conditionals.html.md
  website/docs/configuration/expressions/function-calls.html.md
  website/docs/configuration/expressions/index.html.md
  website/docs/configuration/expressions/references.html.md
  website/docs/configuration/expressions/splat.html.md
  website/docs/configuration/functions.html.md
  website/docs/configuration/modules.html.md
  website/docs/configuration/provider-requirements.html.md
  website/docs/configuration/resources.html.md
  website/docs/configuration/variables.html.md
Labels: 0.14-backport

#27058 Add comments about this URL being linked to in the CLI
  website/docs/plugins/signing.html.md
Labels: 0.14-backport, documentation

#27069 website: Initial docs for the provider_sensitive_attrs experiment
  website/docs/configuration/expressions/references.html.md
Labels: 0.14-backport, config, documentation, enhancement

#27090 website: fix a few functional glitches (0.14 version)
  website/docs/backends/types/terraform-enterprise.html.md
  website/docs/configuration/functions/defaults.html.md
  website/docs/configuration/functions/textdecodebase64.html.md
  website/docs/configuration/functions/textencodebase64.html.md
Labels: documentation

#27089 website: fix a few functional glitches
  website/docs/configuration/functions/defaults.html.md
  website/docs/configuration/functions/textdecodebase64.html.md
  website/docs/configuration/functions/textencodebase64.html.md
Labels: documentation

#27108 Anytrue alltrue docs clarification.
  website/docs/configuration/functions/alltrue.html.md
  website/docs/configuration/functions/anytrue.html.md
Labels: 0.14-backport, documentation

#27074 Fix apt install typo
  website/docs/cli/install/apt.html.md
Labels: 0.14-backport, documentation

#27114 website: Correct formatting for lists in dependency lock docs
  website/docs/commands/providers/lock.html.md
  website/docs/configuration/dependency-lock.html.md
Labels: 0.14-backport, bug, cli, config, documentation

#27091 website: Fix several broken links
  website/docs/configuration/blocks/modules/syntax.html.md
  website/docs/configuration/blocks/resources/behavior.html.md
  website/docs/configuration/blocks/resources/index.html.md
  website/docs/configuration/blocks/resources/syntax.html.md
  website/docs/configuration/files/index.html.md
  website/docs/plugins/basics.html.md
  website/docs/provisioners/index.html.markdown
  website/upgrade-guides/0-9.html.markdown
Labels: 0.14-backport, documentation

#27112 Website: 0.14 Upgrade guide additions
  website/upgrade-guides/0-14.html.markdown
Labels: 0.14-backport, documentation

#27038 website: Fix typo in docs/commands/cli-config
  website/docs/commands/cli-config.html.markdown
Labels: 0.14-backport, documentation

#27120 Backport of website: Fix typo in docs/commands/cli-config into v0.14
  website/docs/commands/cli-config.html.markdown
Labels: documentation

#27124 Website: Upgrade guide link fix
  website/upgrade-guides/0-14.html.markdown
Labels: 0.14-backport, documentation

#27125 Backport of Website: Upgrade guide link fix into v0.14
  website/upgrade-guides/0-14.html.markdown
Labels: documentation

#27128 terraform: Write state if sensitivity changes
  terraform/context_apply_test.go
  terraform/eval_apply.go
Labels: 0.14-backport

#27130 Backport of terraform: Write state if sensitivity changes into v0.14
  terraform/context_apply_test.go
  terraform/eval_apply.go
Labels: v0.14

#27131 Avoid double-marking variables
  terraform/context_plan_test.go
  terraform/evaluate.go
  terraform/evaluate_test.go
  terraform/testdata/plan-variable-sensitivity-module/child/main.tf
  terraform/testdata/plan-variable-sensitivity-module/main.tf
Labels: 0.14-backport

#27169 Update docs and add warning for -get-plugins
  command/init.go
  command/init_test.go
  tools/terraform-bundle/README.md
  website/docs/commands/init.html.markdown
Labels: 0.13-backport, 0.14-backport

#27174 ignore_changes can ignore unknowns too
  terraform/eval_diff.go
  terraform/eval_diff_test.go
Labels: 0.14-backport

#27184 Fix wrong syntax in setproduct.html.md
  website/docs/configuration/functions/setproduct.html.md
Labels: 0.14-backport, documentation

#27178 Update hcl2 dependency
  go.mod
  go.sum
Labels: 0.14-backport

#27001 Backport of backend: Validate remote backend Terraform version into v0.14
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_context.go
  backend/remote/backend_mock.go
  backend/remote/backend_test.go
  command/console.go
  command/graph.go
  command/import.go
  command/init.go
  command/meta.go
  command/meta_backend.go
  command/output.go
  command/providers.go
  command/providers_schema.go
  command/show.go
  command/state_list.go
  command/state_meta.go
  command/state_mv.go
  command/state_pull.go
  command/state_push.go
  command/state_replace_provider.go
  command/state_rm.go
  command/state_show.go
  command/taint.go
  command/untaint.go
  command/workspace_delete.go
  command/workspace_list.go
  command/workspace_new.go
  command/workspace_select.go
  website/docs/commands/import.html.md
  website/docs/commands/state/mv.html.md
  website/docs/commands/state/push.html.md
  website/docs/commands/state/replace-provider.html.md
  website/docs/commands/state/rm.html.md
  website/docs/commands/taint.html.markdown
  website/docs/commands/untaint.html.markdown
Labels: backend/remote

#27000 Backport of backend: Validate remote backend Terraform version into v0.13
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_context.go
  backend/remote/backend_mock.go
  backend/remote/backend_test.go
  command/console.go
  command/graph.go
  command/import.go
  command/init.go
  command/meta.go
  command/meta_backend.go
  command/output.go
  command/providers.go
  command/providers_schema.go
  command/show.go
  command/state_list.go
  command/state_meta.go
  command/state_mv.go
  command/state_pull.go
  command/state_push.go
  command/state_replace_provider.go
  command/state_rm.go
  command/state_show.go
  command/taint.go
  command/untaint.go
  command/workspace_delete.go
  command/workspace_list.go
  command/workspace_new.go
  command/workspace_select.go
  website/docs/commands/import.html.md
  website/docs/commands/state/mv.html.md
  website/docs/commands/state/push.html.md
  website/docs/commands/state/replace-provider.html.md
  website/docs/commands/state/rm.html.md
  website/docs/commands/taint.html.markdown
  website/docs/commands/untaint.html.markdown
Labels: backend/remote

#27002 Backport of backend: Validate remote backend Terraform version into v0.12
  backend/remote/backend.go
  backend/remote/backend_apply_test.go
  backend/remote/backend_context.go
  backend/remote/backend_mock.go
  backend/remote/backend_test.go
  command/console.go
  command/graph.go
  command/import.go
  command/init.go
  command/meta.go
  command/meta_backend.go
  command/output.go
  command/providers.go
  command/providers_schema.go
  command/show.go
  command/state_list.go
  command/state_meta.go
  command/state_mv.go
  command/state_pull.go
  command/state_push.go
  command/state_rm.go
  command/state_show.go
  command/taint.go
  command/untaint.go
  command/workspace_delete.go
  command/workspace_list.go
  command/workspace_new.go
  command/workspace_select.go
  website/docs/commands/import.html.md
  website/docs/commands/state/mv.html.md
  website/docs/commands/state/push.html.md
  website/docs/commands/state/rm.html.md
  website/docs/commands/taint.html.markdown
  website/docs/commands/untaint.html.markdown
Labels: backend/remote

#27011 builtin/providers/terraform: Disable remote state file version checks
  backend/atlas/backend.go
  backend/backend.go
  backend/local/backend.go
  backend/nil.go
  backend/remote-state/artifactory/backend.go
  backend/remote-state/azure/backend_state.go
  backend/remote-state/consul/backend_state.go
  backend/remote-state/cos/backend_state.go
  backend/remote-state/etcdv2/backend.go
  backend/remote-state/etcdv3/backend_state.go
  backend/remote-state/gcs/backend_state.go
  backend/remote-state/http/backend.go
  backend/remote-state/inmem/backend.go
  backend/remote-state/manta/backend_state.go
  backend/remote-state/oss/backend_state.go
  backend/remote-state/pg/backend_state.go
  backend/remote-state/s3/backend_state.go
  backend/remote-state/swift/backend_state.go
  backend/remote/backend.go
  backend/remote/backend_state.go
  builtin/providers/terraform/data_source_state.go
  builtin/providers/terraform/data_source_state_test.go
  builtin/providers/terraform/testdata/future.tfstate
  command/show.go
  command/state_push.go
  command/workspace_new.go
  plans/planfile/reader.go
  state/lock.go
  state/remote/state.go
  states/statefile/file.go
  states/statefile/read.go
  states/statemgr/filesystem.go
  states/statemgr/persistent.go
  states/statemgr/statemgr_fake.go
Labels: provider/terraform

#27197 Fix terraform_remote_state backend version check
  builtin/providers/terraform/data_source_state.go
Labels: 0.13-backport, 0.14-backport

#27199 backend/remote: Fix for "latest" workspace version
  backend/remote/backend.go
  backend/remote/backend_test.go
Labels: 0.13-backport, 0.14-backport

#27212 command/output: Raw output mode
  command/output.go
  command/output_test.go
  website/docs/commands/output.html.markdown
Labels: 0.14-backport, cli, enhancement

#27211 website: Fix a stray broken link to 0.8 -> 0.9 backend upgrade doc
  website/upgrade-guides/0-9.html.markdown
Labels: 0.14-backport

#27233 set SkipRefresh for plan and apply
  backend/local/backend_apply_test.go
  backend/local/backend_local.go
Labels: 0.14-backport

#27234 command: Revert local patch for pkg/browser
  command/webbrowser/native.go
  go.mod
  go.sum
Labels: windows

#27237 lang/funcs: Fix alltrue/anytrue with unknowns
  lang/funcs/collection.go
  lang/funcs/collection_test.go
Labels: 0.14-backport, functions

#27227 command/init: Hint about providers in other namespaces
  command/init.go
  internal/getproviders/didyoumean.go
  internal/getproviders/didyoumean_test.go
  internal/providercache/installer.go
Labels: UX, cli, enhancement

#27238 Unmark values in count before go conversion
  terraform/eval_count.go
  terraform/eval_count_test.go
Labels: 0.14-backport

#27249 lang: Improved robustness of sum function
  lang/funcs/collection.go
  lang/funcs/collection_test.go
Labels: 0.14-backport, functions

#27244 command/init: Remove the warnings about the "legacy" provider cache directory
  command/init.go
  command/init_test.go
  command/meta_providers.go
Labels: cli, enhancement

#27281 Guard against double marking in other locations in evaluate
  terraform/evaluate.go
Labels: 0.14-backport

#27280 (docs) Document sensitivity + function call behavior
  website/docs/configuration/expressions/function-calls.html.md
Labels: 0.14-backport, documentation

#27299 [docs] Add limitations section to for_each
  website/docs/configuration/meta-arguments/for_each.html.md
Labels: 0.14-backport

#27320 Update hcl and go-cty dependencies
  go.mod
  go.sum
Labels: dependencies

#27322 Update hcl and go-cty dependencies
  go.mod
  go.sum
Labels: dependencies

#27317 Add links to outputs and locals tutorials
  website/docs/configuration/locals.html.md
  website/docs/configuration/outputs.html.md
Labels: 0.14-backport

#27339 website: Remove provider category indexes, reduce main list
  website/docs/providers/index.html.markdown
  website/docs/providers/type/cloud-index.html.markdown
  website/docs/providers/type/community-index.html.markdown
  website/docs/providers/type/database-index.html.markdown
  website/docs/providers/type/infra-index.html.markdown
  website/docs/providers/type/major-index.html.markdown
  website/docs/providers/type/misc-index.html.markdown
  website/docs/providers/type/monitor-index.html.markdown
  website/docs/providers/type/network-index.html.markdown
  website/docs/providers/type/vcs-index.html.markdown
  website/layouts/language.erb
Labels: 0.14-backport, documentation
