Repository hashicorp/terraform, pull requests merged in 2020-03, with the labels that each got.

#24227 Update remote.html.md
  website/docs/backends/types/remote.html.md
Labels: documentation

#24265 Update cty to v1.3.1 and migrate to cty stdlib function where applicable
  go.mod
  go.sum
  lang/funcs/collection.go
  lang/funcs/collection_test.go
  lang/funcs/filesystem_test.go
  lang/funcs/number.go
  lang/funcs/number_test.go
  lang/funcs/string.go
  lang/funcs/string_test.go
  lang/functions.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/lib/pq/oid/gen.go
  vendor/github.com/ugorji/go/codec/xml.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion.go
  vendor/github.com/zclconf/go-cty/cty/convert/conversion_collection.go
  vendor/github.com/zclconf/go-cty/cty/convert/unify.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/collection.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/conversion.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/datetime.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/number.go
  vendor/github.com/zclconf/go-cty/cty/function/stdlib/string.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: sdkv1

#24277 lang: Fix non-string key panics in map function
  lang/funcs/collection.go
  lang/funcs/collection_test.go
Labels: sdkv1

#24270 build: Use Go 1.14
  .go-version
  .travis.yml
  go.mod
  internal/getproviders/registry_source_test.go
  vendor/modules.txt
Labels: build, enhancement

#24260 registry: retryable discovery requests
  internal/initwd/module_install.go
  registry/client.go
  registry/client_test.go
  registry/test/mock_registry.go
  website/docs/commands/environment-variables.html.md
Labels: sdkv1

#24259 registry: configurable client timeout
  registry/client.go
  registry/client_test.go
  website/docs/commands/environment-variables.html.md
Labels: sdkv1

#24295 terraform: refactor ProvidedBy() to return an addrs.ProviderConfig interface
  terraform/node_resource_abstract.go
  terraform/transform_attach_schema.go
  terraform/transform_import_state.go
  terraform/transform_provider.go
Labels: sdkv1

#24313 states: Fix coverage blips in statemgr/filesystem
  states/statemgr/filesystem_test.go
Labels: sdkv1

#24084 Add CreateBeforeDestroy to instance state
  states/instance_object.go
  states/instance_object_src.go
  states/state_deepcopy.go
  terraform/graph_builder_apply_test.go
  terraform/node_resource_destroy.go
  terraform/transform_diff.go
Labels: sdkv1

#24312 Mildwonkey/ps schema
  configs/config.go
  configs/config_test.go
  configs/module.go
  configs/module_test.go
  terraform/graph_builder_apply.go
  terraform/graph_builder_eval.go
  terraform/graph_builder_import.go
  terraform/graph_builder_plan.go
  terraform/graph_builder_refresh.go
  terraform/node_resource_abstract.go
  terraform/transform_attach_schema.go
  terraform/transform_import_state.go
  terraform/transform_provider.go
Labels: sdkv1

#24341 fix a flapping test involving CreateBeforeDestroy
  terraform/context_apply_test.go
  terraform/testdata/apply-module-replace-cycle/mod1/main.tf
Labels: sdkv1

#24149 Fix & improve state locking of OSS backend
  backend/remote-state/oss/backend.go
  backend/remote-state/oss/backend_state.go
  backend/remote-state/oss/backend_test.go
  backend/remote-state/oss/client.go
  backend/remote-state/oss/client_test.go
  website/docs/backends/types/oss.html.md
Labels: backend/oss, breaking-change

#24331 More module expansion groundwork
  addrs/module.go
  terraform/graph.go
  terraform/graph_builder_apply_test.go
  terraform/graph_interface_subgraph.go
  terraform/node_data_refresh.go
  terraform/node_data_refresh_test.go
  terraform/node_local.go
  terraform/node_module_expand.go
  terraform/node_module_removed.go
  terraform/node_module_variable.go
  terraform/node_output.go
  terraform/node_output_orphan.go
  terraform/node_provider_abstract.go
  terraform/node_provider_disabled.go
  terraform/node_provisioner.go
  terraform/node_resource_abstract.go
  terraform/node_resource_plan.go
  terraform/node_resource_plan_destroy.go
  terraform/node_resource_plan_instance.go
  terraform/node_resource_plan_orphan.go
  terraform/node_resource_refresh.go
  terraform/node_resource_refresh_test.go
  terraform/node_resource_validate.go
  terraform/node_root_variable.go
  terraform/transform_attach_config_provider.go
  terraform/transform_config.go
  terraform/transform_expand.go
  terraform/transform_expand_test.go
  terraform/transform_import_state.go
  terraform/transform_local.go
  terraform/transform_module_expansion.go
  terraform/transform_module_variable.go
  terraform/transform_output.go
  terraform/transform_provider.go
  terraform/transform_reference.go
  terraform/transform_reference_test.go
Labels: sdkv1

#24346 Continue pushing the Path calls out of the Resource and Provider types
  addrs/provider_config.go
  addrs/provider_config_test.go
  backend/local/backend_plan_test.go
  backend/testing.go
  command/apply_destroy_test.go
  command/apply_test.go
  command/command_test.go
  command/format/diff_test.go
  command/format/state_test.go
  command/graph_test.go
  command/jsonplan/values_test.go
  command/jsonstate/state_test.go
  command/plan_test.go
  command/show_test.go
  command/state_mv_test.go
  command/state_rm_test.go
  command/state_show.go
  command/state_show_test.go
  command/taint_test.go
  command/untaint_test.go
  command/workspace_command_test.go
  configs/config.go
  configs/config_test.go
  helper/resource/state_shim_test.go
  helper/resource/testing.go
  plans/plan_test.go
  plans/planfile/tfplan_test.go
  providers/addressed_types_test.go
  repl/session_test.go
  states/state_test.go
  states/statefile/version3_upgrade.go
  states/statemgr/testing.go
  terraform/context_apply_test.go
  terraform/context_import_test.go
  terraform/context_input.go
  terraform/context_input_test.go
  terraform/context_plan_test.go
  terraform/context_refresh_test.go
  terraform/eval_context_builtin.go
  terraform/eval_context_builtin_test.go
  terraform/eval_provider_test.go
  terraform/eval_state.go
  terraform/graph_builder_apply_test.go
  terraform/node_data_refresh.go
  terraform/node_data_refresh_test.go
  terraform/node_provider_abstract.go
  terraform/node_resource_abstract.go
  terraform/node_resource_apply.go
  terraform/node_resource_destroy.go
  terraform/node_resource_plan.go
  terraform/node_resource_refresh.go
  terraform/node_resource_validate.go
  terraform/transform_attach_schema.go
  terraform/transform_diff_test.go
  terraform/transform_import_state.go
  terraform/transform_orphan_resource_test.go
  terraform/transform_provider.go
  terraform/transform_provisioner_test.go
Labels: sdkv1

#24342 terraform: provider source test
  addrs/provider.go
  addrs/provider_test.go
  configs/config_test.go
  configs/module.go
  configs/module_merge.go
  configs/module_test.go
  configs/parser_test.go
  configs/provider_requirements.go
  configs/provider_requirements_test.go
  configs/provider_test.go
  configs/testdata/valid-modules/nested-providers-fqns/child/main.tf
  configs/testdata/valid-modules/nested-providers-fqns/main.tf
  configs/testdata/valid-modules/providers-fqns/main.tf
  terraform/testdata/transform-provider-fqns-module/child/main.tf
  terraform/testdata/transform-provider-fqns-module/main.tf
  terraform/testdata/transform-provider-fqns/main.tf
  terraform/transform_provider_test.go
Labels: sdkv1

#24362 implement addrs.ConfigResource
  addrs/parse_target_test.go
  addrs/resource.go
  addrs/target_test.go
  terraform/context_import_test.go
  terraform/eval_context_builtin.go
  terraform/eval_state.go
  terraform/graph_builder_apply_test.go
  terraform/node_data_refresh.go
  terraform/node_data_refresh_test.go
  terraform/node_module_expand.go
  terraform/node_module_removed.go
  terraform/node_provider_abstract.go
  terraform/node_provider_disabled.go
  terraform/node_resource_abstract.go
  terraform/node_resource_apply.go
  terraform/node_resource_plan.go
  terraform/node_resource_refresh.go
  terraform/node_resource_refresh_test.go
  terraform/transform_attach_config_provider.go
  terraform/transform_config.go
Labels: sdkv1

#24296 Make modules targetable
  addrs/module.go
  addrs/module_instance.go
  addrs/resource.go
  addrs/target_test.go
  terraform/transform_targets_test.go
Labels: sdkv1

#24382 configs: attach provider fqn to Resource
  configs/config_test.go
  configs/module.go
  configs/module_merge.go
  configs/module_merge_test.go
  configs/module_test.go
  configs/resource.go
  configs/testdata/valid-modules/nested-providers-fqns/child/main.tf
  configs/testdata/valid-modules/nested-providers-fqns/main.tf
  configs/testdata/valid-modules/override-resource-provider/a_override.tf
  configs/testdata/valid-modules/override-resource-provider/base.tf
Labels: sdkv1

#24389 more module expansion foundation
  addrs/resource.go
  command/format/state.go
  command/jsonstate/state.go
  command/jsonstate/state_test.go
  command/state_meta.go
  command/state_mv.go
  helper/resource/state_shim.go
  states/module.go
  states/resource.go
  states/state.go
  states/state_string.go
  states/state_test.go
  states/statefile/version4.go
  states/sync.go
  terraform/context_refresh_test.go
  terraform/eval_count.go
  terraform/eval_count_boundary.go
  terraform/node_data_refresh.go
  terraform/node_resource_abstract.go
  terraform/node_resource_apply.go
  terraform/node_resource_apply_instance.go
  terraform/node_resource_destroy.go
  terraform/node_resource_destroy_deposed.go
  terraform/node_resource_plan.go
  terraform/node_resource_plan_destroy.go
  terraform/node_resource_plan_instance.go
  terraform/node_resource_plan_orphan.go
  terraform/node_resource_refresh.go
  terraform/node_resource_validate.go
  terraform/resource_test.go
  terraform/transform_attach_config_provider_meta.go
  terraform/transform_attach_config_resource.go
  terraform/transform_attach_schema.go
  terraform/transform_diff.go
  terraform/transform_orphan_count.go
  terraform/transform_orphan_resource.go
  terraform/transform_reference.go
  terraform/transform_resource_count.go
  terraform/transform_state.go
  terraform/transform_targets.go
Labels: sdkv1

#24343 vendor: Fix checksum for github.com/coreos/etcd
  go.sum
Labels: bug, build

#24396 terraform: large refactor to use Provider from configs.Resource
  addrs/resource.go
  configs/configupgrade/analysis.go
  configs/module.go
  configs/module_test.go
  configs/resource.go
  configs/testdata/valid-modules/nested-providers-fqns/main.tf
  states/statefile/version3_upgrade.go
  states/statemgr/testing.go
  terraform/eval_state_upgrade.go
  terraform/node_resource_abstract.go
  terraform/transform_attach_schema.go
  terraform/transform_import_state.go
  terraform/transform_provider.go
Labels: sdkv1

#24411 registry: Fix panic when server is unreachable
  registry/client.go
  registry/client_test.go
  registry/test/mock_registry.go
Labels: sdkv1

#24412 Mildwonkey/ps import
  builtin/providers/test/provider.go
  builtin/providers/test/resource_import_other.go
  builtin/providers/test/resource_import_other_test.go
  builtin/providers/test/resource_import_removed.go
  builtin/providers/test/resource_import_removed_test.go
  command/import_test.go
  helper/resource/testing_import_state.go
  terraform/context_import.go
  terraform/context_import_test.go
  terraform/graph_builder_import.go
  terraform/testdata/import-module/child/main.tf
  terraform/testdata/import-module/child/submodule/main.tf
  terraform/testdata/import-module/main.tf
  terraform/testdata/import-provider-module/child/main.tf
  terraform/testdata/import-provider-vars/main.tf
  terraform/testdata/import-provider/main.tf
  terraform/transform_import_state.go
  terraform/transform_provider_test.go
Labels: sdkv1

#24417 rename provider-specific functions
  command/init.go
  command/init_test.go
  command/plugins.go
  command/testdata/init-get-providers/main.tf
  moduledeps/module.go
  moduledeps/module_test.go
  terraform/context.go
Labels: sdkv1

#24428 Mildwonkey/ps-addr-is
  addrs/provider.go
  addrs/provider_test.go
  configs/config_test.go
  configs/module_merge_test.go
  configs/module_test.go
Labels: sdkv1

#24444 Expander.ExpandResource should use AbsResource
  instances/expander.go
  instances/expander_test.go
  terraform/node_data_refresh.go
  terraform/node_resource_plan.go
  terraform/node_resource_refresh.go
Labels: sdkv1

#24461 Module Expansion Activate!
  command/apply_destroy_test.go
  command/command_test.go
  command/refresh_test.go
  command/show_test.go
  command/state_mv_test.go
  configs/module_call.go
  configs/module_call_test.go
  states/instance_object.go
  states/instance_object_src.go
  states/state_deepcopy.go
  states/state_test.go
  states/statefile/version4.go
  terraform/context_apply_test.go
  terraform/context_plan_test.go
  terraform/context_refresh_test.go
  terraform/eval.go
  terraform/eval_context.go
  terraform/eval_context_builtin.go
  terraform/eval_context_builtin_test.go
  terraform/eval_context_mock.go
  terraform/eval_output.go
  terraform/eval_state.go
  terraform/graph.go
  terraform/graph_builder_apply.go
  terraform/graph_builder_apply_test.go
  terraform/graph_builder_plan.go
  terraform/graph_builder_refresh.go
  terraform/graph_builder_refresh_test.go
  terraform/graph_walk.go
  terraform/graph_walk_context.go
  terraform/node_data_refresh.go
  terraform/node_data_refresh_test.go
  terraform/node_module_expand.go
  terraform/node_output.go
  terraform/node_output_orphan.go
  terraform/node_resource_abstract.go
  terraform/node_resource_apply.go
  terraform/node_resource_apply_instance.go
  terraform/node_resource_destroy.go
  terraform/node_resource_plan.go
  terraform/node_resource_refresh.go
  terraform/node_resource_refresh_test.go
  terraform/node_resource_validate.go
  terraform/terraform_test.go
  terraform/testdata/plan-modules-expand/child/main.tf
  terraform/testdata/plan-modules-expand/main.tf
  terraform/transform_config.go
  terraform/transform_config_test.go
  terraform/transform_destroy_cbd_test.go
  terraform/transform_destroy_edge.go
  terraform/transform_destroy_edge_test.go
  terraform/transform_orphan_count.go
  terraform/transform_orphan_resource.go
  terraform/transform_output.go
  terraform/transform_provider.go
Labels: sdkv1

#24446 Update ModuleCallOutput and add AbsModuleCallOutput
  addrs/module_call.go
  addrs/output_value.go
  addrs/parse_ref.go
  addrs/parse_ref_test.go
  lang/data.go
  lang/data_test.go
  lang/eval.go
  terraform/evaluate.go
  terraform/evaluate_valid.go
  terraform/node_output.go
Labels: sdkv1

#24473 command/format: Fix multi-line diagnostic output
  command/format/diagnostic.go
  command/format/diagnostic_test.go
Labels: sdkv1

#24472 internal/getproviders: A new shared model for provider requirements
  configs/config.go
  configs/config_test.go
  configs/testdata/provider-reqs/child/provider-reqs-child.tf
  configs/testdata/provider-reqs/provider-reqs-root.tf
  internal/earlyconfig/config.go
  internal/earlyconfig/config_test.go
  internal/earlyconfig/testdata/provider-reqs/child/provider-reqs-child.tf
  internal/earlyconfig/testdata/provider-reqs/provider-reqs-root.tf
  internal/getproviders/types.go
  internal/providercache/installer.go
  states/state.go
Labels: cli, enhancement, sdkv1

#24485 Added links to Learn and certification exams to the README
  README.md
Labels: documentation

#24504 states/version3 upgrade: revert provider FQN changes
  states/statefile/testdata/roundtrip/v3-bigint.out.tfstate
  states/statefile/testdata/roundtrip/v3-grabbag.out.tfstate
  states/statefile/testdata/roundtrip/v3-invalid-depends.out.tfstate
  states/statefile/testdata/roundtrip/v3-simple.out.tfstate
  states/statefile/testdata/roundtrip/v4-simple.in.tfstate
  states/statefile/version3_upgrade.go
Labels: sdkv1

#24513 Mildwonkey/terraform tests (targeting integration branch)
  configs/config.go
  configs/config_test.go
  configs/module.go
  configs/module_merge.go
  configs/module_merge_test.go
  configs/module_test.go
  terraform/context_apply_test.go
  terraform/context_fixtures_test.go
  terraform/context_import_test.go
  terraform/context_input_test.go
  terraform/context_plan_test.go
  terraform/context_refresh_test.go
  terraform/context_validate_test.go
  terraform/eval_apply.go
  terraform/eval_context_builtin.go
  terraform/eval_context_mock.go
  terraform/eval_diff.go
  terraform/eval_read_data.go
  terraform/eval_refresh.go
  terraform/evaluate_valid.go
  terraform/node_resource_abstract.go
  terraform/terraform_test.go
Labels: sdkv1
