Repository hashicorp/terraform, pull requests merged in 2021-11, with the labels that each got.

#29307 Flatten `assume_role` block for OSS backend
  internal/backend/remote-state/oss/backend.go
  internal/backend/remote-state/oss/backend_state.go
  internal/backend/remote-state/oss/client.go
  website/docs/language/settings/backends/oss.html.md
Labels: backend/oss

#29836 command: Adjust skipping of resource counts for any remote implementation
  internal/command/apply.go
  internal/command/meta_backend.go
Labels: Terraform Cloud integration

#29842 cloud: Fix prerelease version constraint checks
  internal/cloud/backend.go
  internal/cloud/backend_test.go
Labels: cloud

#29834 experiments: config_driven_move has concluded
  internal/command/testdata/show-json/moved-drift/main.tf
  internal/command/testdata/show-json/moved/main.tf
  internal/configs/experiments.go
  internal/configs/testdata/invalid-modules/config-driven-move-experiment/config-driven-move-experiment.tf
  internal/configs/testdata/valid-modules/moved-blocks/moved-blocks-1.tf
  internal/experiments/experiment.go
  internal/refactoring/move_statement_test.go
  internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf
  internal/terraform/context_plan2_test.go
Labels: enhancement, config

#29835 Cloud: Init without erroring when no workspaces match the `tags`
  internal/cloud/e2e/init_with_empty_tags_test.go
  internal/command/meta_backend.go
Labels: cloud

#29845 nullable variable docs
  website/docs/language/expressions/types.html.md
  website/docs/language/values/variables.html.md
Labels: documentation

#29841 backend/oss: Supports the new attribute sts_endpoint
  internal/backend/remote-state/oss/backend.go
  website/docs/language/settings/backends/oss.html.md
Labels: 1.0-backport

#29846 cloud: Allow cloud tests to be run in parallel
  internal/cloud/e2e/apply_auto_approve_test.go
  internal/cloud/e2e/backend_apply_before_init_test.go
  internal/cloud/e2e/init_with_empty_tags_test.go
  internal/cloud/e2e/migrate_state_multi_to_tfc_test.go
  internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go
  internal/cloud/e2e/migrate_state_single_to_tfc_test.go
  internal/cloud/e2e/migrate_state_tfc_to_other_test.go
  internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go
  internal/cloud/e2e/run_variables_test.go
Labels: cloud

#29849 configs: fix ignore_changes config override bug
  internal/configs/configschema/validate_traversal.go
  internal/configs/module_merge.go
  internal/configs/module_merge_test.go
  internal/configs/testdata/valid-modules/override-ignore-changes/main.tf
  internal/configs/testdata/valid-modules/override-ignore-changes/main_override.tf
Labels: config, 1.0-backport

#29827 command/format: improve list nested attribute rendering
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: cli

#29853 Cloud: Update Workspace during Tags strategy
  internal/cloud/backend.go
  internal/cloud/e2e/migrate_state_multi_to_tfc_test.go
  internal/cloud/tfe_client_mock.go
Labels: cloud, 1.1-backport

#29864 update go-cty to v1.10.0
  go.mod
  go.sum
Labels: 1.0-backport, 1.1-backport

#29862 generate precise resource types during validate
  internal/terraform/context_plan_test.go
  internal/terraform/evaluate.go
  internal/terraform/testdata/plan-self-ref-multi-all/main.tf
Labels: 1.1-backport

#29868 backend/oss: Removes the ConflictWith tag which on the attributes assume_role* to fix the incompatible error
  internal/backend/remote-state/oss/backend.go
  website/docs/language/settings/backends/oss.html.md
Labels: 1.1-backport

#29878 cloud: Autoselect migrated current workspace + migrate UX adjustments
  internal/command/meta_backend_migrate.go
Labels: cloud, 1.1-backport

#29881 cloud: Add streamlined 'remote' backend state migration path
  internal/backend/remote/backend.go
  internal/command/meta_backend.go
  internal/command/meta_backend_migrate.go
Labels: cloud, 1.1-backport

#29887 Fix typo in 0.13 upgrade guide
  website/upgrade-guides/0-13.html.markdown
Labels: documentation

#29889 main: Report version information for "interesting" dependencies
  main.go
  version/dependencies.go
Labels: enhancement, build

#29844 cloud: convert uses of worspaces.operations into workspaces.executionMode
  internal/cloud/backend.go
  internal/cloud/backend_apply_test.go
  internal/cloud/backend_test.go
  internal/cloud/tfe_client_mock.go
Labels: cloud, 1.1-backport

#29892 Command state mv: Error when backup or backup-out options are used without the state option on non-local backends
  internal/command/state_mv.go
  internal/command/state_mv_test.go
  internal/command/testdata/init-backend-http/main.tf
  website/docs/cli/commands/state/mv.html.md
Labels: enhancement, documentation, 1.1-backport

#29919 Backport of Command state mv: Error when backup or backup-out options are used without the state option on non-local backends into v1.1
  internal/command/state_mv.go
  internal/command/state_mv_test.go
  internal/command/testdata/init-backend-http/main.tf
  website/docs/cli/commands/state/mv.html.md
Labels: enhancement, documentation

#29928 `ignore_changes` converting null maps to empty maps, and applying marks.
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/reduce_plan_test.go
Labels: 1.1-backport

#29883 Cloud: Make e2e Tests Less Chatty, and More Stable
  go.mod
  go.sum
  internal/cloud/e2e/README.md
  internal/cloud/e2e/apply_auto_approve_test.go
  internal/cloud/e2e/backend_apply_before_init_test.go
  internal/cloud/e2e/helper_test.go
  internal/cloud/e2e/init_with_empty_tags_test.go
  internal/cloud/e2e/main_test.go
  internal/cloud/e2e/migrate_state_multi_to_tfc_test.go
  internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go
  internal/cloud/e2e/migrate_state_single_to_tfc_test.go
  internal/cloud/e2e/migrate_state_tfc_to_other_test.go
  internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go
  internal/cloud/e2e/run_variables_test.go
Labels: cloud, 1.1-backport

#29926 funcs: defer close file in filesha256
  internal/lang/funcs/crypto.go
  internal/lang/funcs/filesystem.go
Labels: 1.1-backport

#29902 Backport of cloud: convert uses of worspaces.operations into workspaces.executionMode into v1.1
  internal/cloud/backend.go
  internal/cloud/backend_apply_test.go
  internal/cloud/backend_test.go
  internal/cloud/tfe_client_mock.go
Labels: cloud

#29943 refactoring: error when changing resource type during move
  internal/addrs/move_endpoint.go
  internal/addrs/move_endpoint_module.go
  internal/addrs/move_endpoint_test.go
  internal/addrs/moveable.go
  internal/addrs/resource.go
  internal/configs/moved_test.go
  internal/refactoring/move_validate.go
  internal/refactoring/move_validate_test.go
  internal/refactoring/testdata/move-validate-zoo/move-validate-root.tf
Labels: 1.1-backport

#29863 Cloud: Migrate empty default workspace prompt
  internal/cloud/e2e/migrate_state_multi_to_tfc_test.go
  internal/command/meta_backend_migrate.go
Labels: cloud, 1.1-backport

#29953 Remove retracted k8s package
  go.mod
  go.sum
  internal/backend/remote-state/kubernetes/backend_state.go
  internal/backend/remote-state/kubernetes/backend_test.go
  internal/backend/remote-state/kubernetes/client.go
Labels: 1.1-backport

#29968 backend/azurerm: adding support for authenticating via MSAL in addition to ADAL
  go.mod
  go.sum
  internal/backend/remote-state/azure/arm_client.go
  internal/backend/remote-state/azure/backend.go
  internal/backend/remote-state/azure/backend_test.go
  internal/backend/remote-state/azure/helpers_test.go
  website/docs/language/settings/backends/azurerm.html.md
Labels: enhancement, backend/azure

#29977 Fix failing checks
  go.mod
  go.sum
  internal/getproviders/package_authentication.go
  internal/getproviders/package_authentication_test.go
Labels: dependencies, security, 1.1-backport

#29979 Backport of Fix failing checks into v1.1
  go.mod
  go.sum
  internal/getproviders/package_authentication.go
  internal/getproviders/package_authentication_test.go
Labels: dependencies, security

#29983 cli: Fix diff for nested set unchanged elements
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: cli, 1.1-backport

#29986 cli: Fix nested single and map diff rendering
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: cli, 1.1-backport

#29967 Clarify 'cloud' configuration block message
  internal/command/meta_backend.go
Labels: cloud, 1.1-backport

#29997 Cloud integration requires input for migrations
  internal/command/init_test.go
  internal/command/meta_backend_migrate.go
Labels: cloud, 1.1-backport

#29987 command/init: Add -cloud alias to -backend, adjust `init` help output
  internal/command/arguments/flags.go
  internal/command/init.go
Labels: cloud, 1.1-backport

#30019 core: Fix schema loading for deleted resources
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_abstract_instance_test.go
Labels: core, v1.1, 1.1-backport

#30029 configs: Add sensitive marks for nested attributes
  internal/configs/configschema/implied_type.go
  internal/configs/configschema/implied_type_test.go
  internal/configs/configschema/marks.go
  internal/configs/configschema/marks_test.go
Labels: config, v1.1, 1.1-backport

#30048 backend/http: supply logging.LogOutput() to retryable client
  internal/backend/remote-state/http/backend.go
Labels: backend/http, 1.0-backport, 1.1-backport

#30053 addrs: Expose the registry address parser's error messages
  internal/addrs/module_source.go
  internal/addrs/module_source_test.go
  internal/configs/module_call.go
  internal/configs/testdata/error-files/module-invalid-registry-source-with-module.tf
  internal/configs/testdata/error-files/module-local-source-with-version.tf
  internal/earlyconfig/config_build.go
  internal/initwd/module_install.go
  internal/initwd/module_install_test.go
Labels: enhancement, config
