Repository hashicorp/terraform, pull requests merged in 2021-05, with the labels that each got.

#28583 cli: Show forces replacement for sensitive attrs
  command/format/diff.go
  command/format/diff_test.go
Labels: 0.15-backport, cli

#28584 command/views: Add reason to JSON planned change
  command/views/json/change.go
  command/views/operation_test.go
Labels: 0.15-backport, json-output

#28594 Update go-tfe client to v0.14.0
  backend/remote/backend_mock.go
  go.mod
  go.sum
Labels: 0.15-backport, backend/remote

#28598 cli: Fix diagnostic snippet crash
  command/format/diagnostic.go
  command/format/diagnostic_test.go
  command/views/json/diagnostic.go
  command/views/json/diagnostic_test.go
  command/views/json/testdata/diagnostic/error-with-source-code-unavailable.json
  command/views/json/testdata/diagnostic/error-with-unset-highlight-end-position.json
Labels: 0.15-backport, cli, json-output

#28607 Upgrade cty to 1.8.3
  go.mod
  go.sum
Labels: 0.15-backport, dependencies

#28606 Validate passing default providers through modules
  configs/provider_validation.go
  configs/testdata/config-diagnostics/pass-inherited-provider/main.tf
  configs/testdata/config-diagnostics/pass-inherited-provider/mod/main.tf
  configs/testdata/config-diagnostics/pass-inherited-provider/mod2/main.tf
  configs/testdata/config-diagnostics/pass-inherited-provider/warnings
  configs/testdata/config-diagnostics/unknown-root-provider/main.tf
  configs/testdata/config-diagnostics/unknown-root-provider/mod/main.tf
  configs/testdata/config-diagnostics/unknown-root-provider/warnings
  terraform/context_validate_test.go
  terraform/transform_provider.go
Labels: 0.15-backport

#28608 jsonplan: Add replace_paths
  command/jsonplan/plan.go
  command/jsonplan/plan_test.go
  command/testdata/show-json/requires-replace/output.json
  website/docs/internals/json-format.html.md
Labels: 0.15-backport, cli, json-output

#28624 null check in ValueMarks
  configs/configschema/marks.go
  configs/configschema/marks_test.go
Labels: 0.15-backport

#28629 core: If we refresh during orphan processing, use the result for planning
  terraform/node_resource_abstract_instance.go
  terraform/node_resource_plan_orphan.go
  terraform/node_resource_plan_orphan_test.go
Labels: bug, core

#28644 Improve marks support for `length` and `lookup`
  lang/funcs/collection.go
  lang/funcs/collection_test.go
Labels: 0.15-backport, functions

#28653 plans/planfile: Read state snapshots as part of reading a plan
  plans/planfile/planfile_test.go
  plans/planfile/reader.go
Labels: bug, cli

#28654 core: Update working state for resource instances in refresh-only mode
  terraform/context_plan2_test.go
  terraform/node_resource_plan_instance.go
Labels: bug, core

#28656 command/views: Remove baseState argument from plan-rendering views
  backend/local/backend_apply.go
  backend/local/backend_plan.go
  command/show.go
  command/views/operation.go
  command/views/operation_test.go
  command/views/plan.go
  command/views/show.go
Labels: cli, enhancement

#28681 lang/funcs: File hashing functions stream data from disk
  lang/funcs/crypto.go
  lang/funcs/filesystem.go
Labels: config, enhancement

#28684 backend/remote: clearer error when we fail to read the organization
  backend/remote/backend.go
  backend/remote/backend_test.go
Labels: 0.15-backport, backend/remote

#28677 core: "Did you mean" hints for unsupported resource types
  terraform/node_resource_validate.go
Labels: core, enhancement

#28687 Decode change values with marks
  command/format/diff.go
  command/jsonplan/plan.go
  command/jsonplan/values.go
  plans/changes_src.go
  plans/changes_test.go
  plans/objchange/normalize_obj.go
  terraform/context_apply2_test.go
  terraform/context_plan_test.go
  terraform/evaluate.go
  terraform/node_output.go
Labels: 0.15-backport

#28704 core: "Did you mean" hint for missing data. prefix in references
  terraform/evaluate_valid.go
  terraform/evaluate_valid_test.go
  terraform/testdata/static-validate-refs/static-validate-refs.tf
Labels: core, enhancement

#28717 backend/gcs: Rework service account impersonation
  CHANGELOG.md
  backend/remote-state/gcs/backend.go
  go.mod
  go.sum
Labels: backend/gcs

#28724 save apply diagnostics on backend failure
  internal/backend/local/backend_apply.go
  internal/backend/local/backend_apply_test.go
Labels: 0.15-backport

#28736 pg backend requires PostgreSQL 10
  website/docs/language/settings/backends/pg.html.md
Labels: 0.15-backport, documentation

#28738 cli: Improve sensitivity change warning output
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: 0.15-backport, cli

#28190 terraform: use ProtocolVersion from unmanaged providers' reattachConfig to chose the correct PluginClient
  internal/command/e2etest/unmanaged_test.go
  internal/command/meta_providers.go
  main.go
Labels: 0.15-backport

#28739 update CODEOWNERS paths
  CODEOWNERS
Labels: 0.15-backport

#28745 negative substring indexes
  website/docs/language/functions/substr.html.md
Labels: 0.15-backport, documentation

#28753 return diagnostics from provisioners
  internal/builtin/provisioners/file/resource_provisioner.go
  internal/builtin/provisioners/file/resource_provisioner_test.go
  internal/builtin/provisioners/local-exec/resource_provisioner.go
  internal/builtin/provisioners/remote-exec/resource_provisioner.go
  internal/builtin/provisioners/remote-exec/resource_provisioner_test.go
  internal/terraform/node_resource_abstract_instance.go
Labels: 0.15-backport

#28746 backend/remote: add support for -refresh=false, -refresh-only, and -replace options
  go.mod
  go.sum
  internal/backend/remote/backend_apply.go
  internal/backend/remote/backend_apply_test.go
  internal/backend/remote/backend_mock.go
  internal/backend/remote/backend_plan.go
  internal/backend/remote/backend_plan_test.go
  internal/backend/remote/testing.go
Labels: 0.15-backport, backend/remote

#28758 update go version
  .go-version
Labels: 0.15-backport

#28766 Fix crash with deposed instances in orphaned resources
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/transform_orphan_resource.go
  internal/terraform/transform_orphan_resource_test.go
Labels: 0.15-backport

#28770 update circle go image to cimg, matching release pipeline
  .circleci/config.yml
  .go-version
Labels: 0.15-backport

#28796 plan: handle deposed instances when rendering drift
  internal/command/format/diff.go
  internal/command/views/operation_test.go
  internal/command/views/plan.go
Labels: 0.15-backport

#28808 return error for invalid resource import
  internal/terraform/transform_import_state.go
  internal/terraform/transform_import_state_test.go
Labels: 0.15-backport

#28806 command/views: Remove unused drift summary message
  internal/command/views/json/message_types.go
  internal/command/views/json_view.go
Labels: 0.15-backport, cli

#28805 website: Add documentation for machine readable UI
  website/docs/cli/commands/apply.html.md
  website/docs/cli/commands/plan.html.md
  website/docs/internals/machine-readable-ui.html.md
Labels: 0.15-backport, documentation

#28819 backend/local: Fix lock when applying stale plan
  internal/backend/local/backend_local.go
  internal/backend/local/backend_local_test.go
Labels: 0.15-backport, backend/local

#28820 backend/remote: point refresh users towards -refresh-only
  internal/backend/remote/backend.go
Labels: backend/remote

#28781 initwd: Error message for local paths escaping module packages
  internal/initwd/module_install.go
  internal/initwd/module_install_test.go
  internal/initwd/testdata/load-module-package-escape/child/package-escape-child.tf
  internal/initwd/testdata/load-module-package-escape/grandchild/package-escape-grandchild.tf
  internal/initwd/testdata/load-module-package-escape/package-escape.tf
  internal/initwd/testdata/load-module-package-prefix/package-prefix.tf
  internal/initwd/testdata/load-module-package-prefix/package/child/package-prefix-child.tf
  internal/initwd/testdata/load-module-package-prefix/package/grandchild/package-prefix-grandchild.tf
  website/docs/language/modules/sources.html.md
Labels: cli, enhancement
