Repository hashicorp/terraform, pull requests merged in 2021-07, with the labels that each got.

#29051 Add page metadata
  website/guides/core-workflow.html.md
  website/intro/index.html.markdown
  website/intro/use-cases.html.markdown
  website/intro/vs/boto.html.markdown
  website/intro/vs/chef-puppet.html.markdown
  website/intro/vs/cloudformation.html.markdown
  website/intro/vs/custom.html.markdown
  website/intro/vs/index.html.markdown
Labels: documentation

#29066 Add compatibility promises to sidebar toc
  website/layouts/language.erb
Labels: documentation

#29110 update go-cty to v1.9.0
  go.mod
  go.sum
Labels: 1.0-backport

#29107 Link refresh tutorial from plan and refresh docs pages
  website/docs/cli/commands/plan.html.md
  website/docs/cli/commands/refresh.html.md
Labels: documentation

#29134 website: remove legacy provider docs index
  website/docs/cli/commands/index.html.md
  website/docs/configuration-0-11/data-sources.html.md
  website/docs/configuration-0-11/providers.html.md
  website/docs/configuration-0-11/resources.html.md
  website/docs/language/data-sources/index.html.md
  website/docs/language/providers/index.html.md
  website/docs/providers/index.html.markdown
  website/layouts/language.erb
Labels: 1.0-backport

#29072 json-output: Add resource drift to machine readable UI
  internal/command/views/json/message_types.go
  internal/command/views/json_view.go
  internal/command/views/json_view_test.go
  internal/command/views/operation.go
  internal/command/views/operation_test.go
  website/docs/internals/machine-readable-ui.html.md
Labels: 1.0-backport, json-output

#29163 website: Adds anchor for TF_CLI_ARGS.
  website/docs/cli/config/environment-variables.html.md
Labels: 1.0-backport, documentation

#29175 Fix flapping JSON output test
  internal/command/views/json_view_test.go
  internal/command/views/operation_test.go
Labels: 1.0-backport

#29178 Fix flapping JSON output test properly
  internal/command/views/operation.go
  internal/command/views/operation_test.go
Labels: 1.0-backport

#28128 StateMgr must be able to return with locked state
  internal/backend/remote-state/etcdv3/backend_state.go
Labels: backend/etcdv3

#29200 manual rebase of #25554
  go.mod
  go.sum
  internal/backend/remote-state/etcdv2/backend.go
  internal/backend/remote-state/etcdv2/client.go
  internal/backend/remote-state/etcdv3/backend.go
  internal/backend/remote-state/etcdv3/backend_state.go
  internal/backend/remote-state/etcdv3/backend_test.go
  internal/backend/remote-state/etcdv3/client.go
  internal/logging/logging.go
Labels: backend/etcdv3

#29199 etcdv3 backend is unmaintained
  CODEOWNERS
Labels: backend/etcdv3

#29206 format/diff: fix panic with null map in NestedType attrs
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: 1.0-backport

#29193 Handle marks on ignore_changes values
  internal/terraform/context_apply2_test.go
  internal/terraform/context_plan_test.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/reduce_plan_test.go
Labels: 1.0-backport

#29081 error_count
  website/docs/cli/commands/validate.html.md
Labels: 1.0-backport

#29208 update hcl v2.10.1
  go.mod
  go.sum
  internal/configs/configschema/validate_traversal_test.go
Labels: 1.0-backport

#29117 Description metadata - language docs
  website/docs/language/data-sources/index.html.md
  website/docs/language/dependency-lock.html.md
  website/docs/language/expressions/conditionals.html.md
  website/docs/language/expressions/dynamic-blocks.html.md
  website/docs/language/expressions/for.html.md
  website/docs/language/expressions/function-calls.html.md
  website/docs/language/expressions/index.html.md
  website/docs/language/expressions/operators.html.md
  website/docs/language/expressions/references.html.md
  website/docs/language/expressions/splat.html.md
  website/docs/language/expressions/strings.html.md
  website/docs/language/expressions/type-constraints.html.md
  website/docs/language/expressions/types.html.md
  website/docs/language/expressions/version-constraints.html.md
  website/docs/language/files/index.html.md
  website/docs/language/files/override.html.md
  website/docs/language/functions/index.html.md
  website/docs/language/index.html.md
  website/docs/language/meta-arguments/count.html.md
  website/docs/language/meta-arguments/depends_on.html.md
  website/docs/language/meta-arguments/for_each.html.md
  website/docs/language/meta-arguments/lifecycle.html.md
  website/docs/language/meta-arguments/module-providers.html.md
  website/docs/language/meta-arguments/resource-provider.html.md
  website/docs/language/modules/develop/index.html.md
  website/docs/language/modules/index.html.md
  website/docs/language/modules/sources.html.md
  website/docs/language/modules/syntax.html.md
  website/docs/language/providers/configuration.html.md
  website/docs/language/providers/index.html.md
  website/docs/language/providers/requirements.html.md
  website/docs/language/resources/behavior.html.md
  website/docs/language/resources/index.html.md
  website/docs/language/resources/provisioners/connection.html.md
  website/docs/language/resources/provisioners/index.html.md
  website/docs/language/resources/provisioners/null_resource.html.md
  website/docs/language/resources/provisioners/syntax.html.md
  website/docs/language/resources/syntax.html.md
  website/docs/language/settings/backends/index.html.md
  website/docs/language/settings/index.html.md
  website/docs/language/state/index.html.md
  website/docs/language/syntax/configuration.html.md
  website/docs/language/syntax/index.html.md
  website/docs/language/syntax/json.html.md
  website/docs/language/syntax/style.html.md
  website/docs/language/values/index.html.md
  website/docs/language/values/locals.html.md
  website/docs/language/values/variables.html.md
Labels: 1.0-backport

#29222 configs/configschema: extend block.AttributeByPath to descend into Objects
  internal/configs/configschema/path.go
  internal/configs/configschema/path_test.go
Labels: 1.0-backport

#29234 Conciseness and fixed some typos in apt.html.md
  website/docs/cli/install/apt.html.md
Labels: documentation

#29241 terraform-workspace should be terraform.workspace
  website/docs/language/expressions/references.html.md
Labels: documentation, providers

#29247 addrs: Address rewriting logic for moves of module calls and module instances
  internal/addrs/move_endpoint_module.go
  internal/addrs/move_endpoint_module_test.go
Labels: core, enhancement

#29215 Add initial Dependabot configuration
  .github/dependabot.yml
Labels: dependencies

#28838 Fix handling large states in the Consul backend
  internal/backend/remote-state/consul/client.go
  internal/backend/remote-state/consul/client_test.go
Labels: 1.0-backport, backend/consul

#29216 Laura description metadata cli
  website/docs/cli/auth/index.html.md
  website/docs/cli/code/index.html.md
  website/docs/cli/commands/apply.html.md
  website/docs/cli/commands/console.html.md
  website/docs/cli/commands/destroy.html.md
  website/docs/cli/commands/env.html.md
  website/docs/cli/commands/fmt.html.md
  website/docs/cli/commands/force-unlock.html.md
  website/docs/cli/commands/get.html.md
  website/docs/cli/commands/graph.html.md
  website/docs/cli/commands/import.html.md
  website/docs/cli/commands/index.html.md
  website/docs/cli/commands/init.html.md
  website/docs/cli/commands/plan.html.md
  website/docs/cli/commands/providers.html.md
  website/docs/cli/commands/version.html.md
  website/docs/cli/commands/workspace/index.html.md
  website/docs/cli/config/config-file.html.md
  website/docs/cli/config/environment-variables.html.md
  website/docs/cli/config/index.html.md
  website/docs/cli/import/index.html.md
  website/docs/cli/index.html.md
  website/docs/cli/init/index.html.md
  website/docs/cli/inspect/index.html.md
  website/docs/cli/plugins/index.html.md
  website/docs/cli/plugins/signing.html.md
  website/docs/cli/run/index.html.md
  website/docs/cli/state/index.html.md
  website/docs/cli/state/inspect.html.md
  website/docs/cli/state/move.html.md
  website/docs/cli/state/recover.html.md
  website/docs/cli/state/taint.html.md
  website/docs/cli/workspaces/index.html.md
  website/docs/internals/index.html.md
  website/docs/language/dependency-lock.html.md
  website/docs/language/expressions/dynamic-blocks.html.md
  website/docs/language/expressions/for.html.md
  website/docs/language/meta-arguments/count.html.md
  website/docs/language/meta-arguments/depends_on.html.md
  website/docs/language/meta-arguments/for_each.html.md
  website/docs/language/meta-arguments/lifecycle.html.md
  website/docs/language/meta-arguments/module-providers.html.md
  website/docs/language/meta-arguments/resource-provider.html.md
  website/docs/language/modules/sources.html.md
  website/docs/language/providers/configuration.html.md
  website/docs/language/resources/behavior.html.md
  website/docs/language/resources/index.html.md
  website/docs/language/resources/provisioners/connection.html.md
  website/docs/language/resources/provisioners/null_resource.html.md
  website/docs/language/settings/index.html.md
  website/docs/language/syntax/index.html.md
Labels: 1.0-backport, documentation, enhancement
