Repository hashicorp/terraform, pull requests merged in 2021-09, with the labels that each got.

#28334 Add null to type conversion docs
  website/docs/language/functions/tobool.html.md
  website/docs/language/functions/tonumber.html.md
  website/docs/language/functions/tostring.html.md
Labels: documentation

#28345 document that destroy provisioners don't run with create_before_destroy
  website/docs/language/meta-arguments/lifecycle.html.md
  website/docs/language/resources/provisioners/syntax.html.md
Labels: documentation, tw-reviewed

#29509 documentation: commit sha can be passed to ref
  website/docs/language/modules/sources.html.md
Labels: documentation

#29523 command: Render "moved" annotations in plan UI
  internal/command/format/diff.go
  internal/command/format/diff_test.go
  internal/command/views/plan.go
  internal/command/views/plan_test.go
  internal/plans/changes.go
  internal/plans/changes_src.go
  internal/plans/changes_test.go
Labels: cli

#29502 json-output: Release format version 1.0
  internal/command/jsonplan/plan.go
  internal/command/jsonprovider/provider.go
  internal/command/jsonstate/state.go
  internal/command/testdata/providers-schema/basic/output.json
  internal/command/testdata/providers-schema/empty/output.json
  internal/command/testdata/providers-schema/required/output.json
  internal/command/testdata/show-json-sensitive/output.json
  internal/command/testdata/show-json-state/basic/output.json
  internal/command/testdata/show-json-state/empty/output.json
  internal/command/testdata/show-json-state/modules/output.json
  internal/command/testdata/show-json-state/sensitive-variables/output.json
  internal/command/testdata/show-json/basic-create/output.json
  internal/command/testdata/show-json/basic-delete/output.json
  internal/command/testdata/show-json/basic-update/output.json
  internal/command/testdata/show-json/drift/output.json
  internal/command/testdata/show-json/module-depends-on/output.json
  internal/command/testdata/show-json/modules/output.json
  internal/command/testdata/show-json/multi-resource-update/output.json
  internal/command/testdata/show-json/nested-modules/output.json
  internal/command/testdata/show-json/provider-version-no-config/output.json
  internal/command/testdata/show-json/provider-version/output.json
  internal/command/testdata/show-json/requires-replace/output.json
  internal/command/testdata/show-json/sensitive-values/output.json
  internal/command/testdata/validate-invalid/incorrectmodulename/output.json
  internal/command/testdata/validate-invalid/interpolation/output.json
  internal/command/testdata/validate-invalid/missing_defined_var/output.json
  internal/command/testdata/validate-invalid/missing_quote/output.json
  internal/command/testdata/validate-invalid/missing_var/output.json
  internal/command/testdata/validate-invalid/multiple_modules/output.json
  internal/command/testdata/validate-invalid/multiple_providers/output.json
  internal/command/testdata/validate-invalid/multiple_resources/output.json
  internal/command/testdata/validate-invalid/output.json
  internal/command/testdata/validate-invalid/outputs/output.json
  internal/command/testdata/validate-valid/output.json
  internal/command/views/validate.go
  website/docs/cli/commands/providers/schema.html.md
  website/docs/cli/commands/validate.html.md
  website/docs/internals/json-format.html.md
Labels: json-output

#29552 Add docs on how to release a new major protocol version.
  docs/plugin-protocol/releasing-new-version.md
Labels: documentation, build

#29451 Added required paramter `resource_group_name` for MSI
  website/docs/language/settings/backends/azurerm.html.md
Labels: documentation, backend/azure

#28579 Added clarity: remote-exec connection requirement
  website/docs/language/resources/provisioners/remote-exec.html.md
Labels: documentation

#29563 remove incorrect computed check
  internal/plans/objchange/plan_valid.go
  internal/plans/objchange/plan_valid_test.go
Labels: 1.0-backport

#29559 Prevent `ObjectWithOptionalAttrs` from escaping
  internal/backend/unparsed_value_test.go
  internal/configs/configschema/decoder_spec.go
  internal/configs/configschema/implied_type.go
  internal/configs/configschema/implied_type_test.go
  internal/configs/experiments.go
  internal/configs/module_merge.go
  internal/configs/module_merge_test.go
  internal/configs/named_values.go
  internal/plans/objchange/objchange_test.go
  internal/terraform/evaluate.go
  internal/terraform/evaluate_test.go
  internal/terraform/node_module_variable.go
  internal/terraform/node_module_variable_test.go
  internal/terraform/node_root_variable_test.go
  internal/terraform/variables.go
Labels: 1.0-backport

#29580 handle empty containers in ProposedNew NestedTypes
  internal/configs/configschema/coerce_value.go
  internal/configs/configschema/coerce_value_test.go
  internal/plans/objchange/objchange.go
  internal/plans/objchange/objchange_test.go
Labels: 1.0-backport

#29578 handle NestedTypes in configschema CoerceValue
  internal/configs/configschema/coerce_value.go
  internal/configs/configschema/coerce_value_test.go
Labels: 1.0-backport

#29581 refactoring: TestValidateMoves/cyclic_chain can now pass
  internal/refactoring/move_validate_test.go
Labels: enhancement, core, build

#29591 core: Fail if a moved resource instance is excluded by -target
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
Labels: enhancement, core

#29598 Add Machine-Readable UI to sidebar
  website/docs/internals/machine-readable-ui.html.md
  website/layouts/docs.erb
Labels: core, documentation, 1.0-backport

#29235 `terraform add`: `-out` option append to existing config & optionally check resource existance
  internal/command/add.go
  internal/command/add_test.go
  internal/command/views/add.go
Labels: cli

#29589 core: Compute resource drift during plan phase, store in plan file
  internal/command/format/diff.go
  internal/command/format/diff_test.go
  internal/command/format/difflanguage_string.go
  internal/command/jsonplan/plan.go
  internal/command/testdata/show-json/drift/output.json
  internal/command/testdata/show-json/multi-resource-update/output.json
  internal/command/views/operation_test.go
  internal/command/views/plan.go
  internal/plans/internal/planproto/planfile.pb.go
  internal/plans/internal/planproto/planfile.proto
  internal/plans/plan.go
  internal/plans/planfile/planfile_test.go
  internal/plans/planfile/tfplan.go
  internal/plans/planfile/tfplan_test.go
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
  internal/terraform/context_refresh_test.go
Labels: core

#29597 cli: Improved plan UI for move-only changes
  internal/command/views/operation_test.go
  internal/command/views/plan.go
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
Labels: cli

#29603 json-output: Add support for config-driven move to plan JSON and streaming JSON UI
  internal/command/jsonplan/plan.go
  internal/command/jsonplan/resource.go
  internal/command/testdata/show-json/moved-drift/main.tf
  internal/command/testdata/show-json/moved-drift/output.json
  internal/command/testdata/show-json/moved-drift/terraform.tfstate
  internal/command/testdata/show-json/moved/main.tf
  internal/command/testdata/show-json/moved/output.json
  internal/command/testdata/show-json/moved/terraform.tfstate
  internal/command/testdata/show-json/multi-resource-update/output.json
  internal/command/views/json/change.go
  internal/command/views/json_view_test.go
  internal/command/views/operation.go
  internal/command/views/operation_test.go
  website/docs/internals/json-format.html.md
  website/docs/internals/machine-readable-ui.html.md
Labels: json-output

#29640 core: Fix refresh-only interaction with orphans
  internal/terraform/context_plan2_test.go
  internal/terraform/node_resource_plan.go
Labels: core, 1.0-backport

#29645 backend/remote: Support interop from 0.14 to 1.1
  internal/backend/remote/backend.go
  internal/backend/remote/backend_test.go
Labels: backend/remote

#29649 json-output: Add change reasons to explain deletes
  internal/command/views/json/change.go
  internal/command/views/json/hook.go
  website/docs/internals/machine-readable-ui.html.md
Labels: json-output

#29660 core: Emit only one warning for move collisions in destroy-plan mode
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
Labels: enhancement, core

#29665 Check required_version as early as possible
  internal/command/init.go
  internal/command/init_test.go
  internal/command/show_test.go
  internal/command/testdata/init-check-required-version-first-module/main.tf
  internal/command/testdata/init-check-required-version-first-module/mod/main.tf
  internal/command/testdata/init-check-required-version-first/main.tf
  internal/configs/configload/loader_load.go
  internal/configs/configload/loader_load_test.go
Labels: 1.0-backport
