Repository hashicorp/terraform, pull requests merged in 2021-06, with the labels that each got.

#28868 docs: Some notes on adopting new Unicode versions
  docs/README.md
  docs/unicode.md
Labels: build, documentation

#28864 Fix remote backend multi workspace state migration
  internal/command/init.go
  internal/command/meta_backend_migrate.go
Labels: 1.0-backport, backend/remote

#28900 website: Fix formatting of v1 compatibility promises
  website/docs/language/v1-compatibility-promises.html.md
Labels: bug, documentation

#28892 Remote backend: Stop setting message when creating runs
  internal/backend/remote/backend_plan.go
  internal/backend/remote/backend_plan_test.go
Labels: 1.0-backport

#28941 handle unexpected changes to unknown block
  internal/plans/objchange/plan_valid.go
  internal/plans/objchange/plan_valid_test.go
Labels: 1.0-backport

#28626 Quoting filesystem path in scp command argument
  internal/communicator/ssh/communicator.go
  internal/communicator/ssh/communicator_test.go
Labels: provisioner/file

#28979 blocktoattr fixup dropping MissingItemRange
  internal/lang/blocktoattr/fixup.go
  internal/lang/blocktoattr/fixup_test.go
Labels: 1.0-backport

#28924 docs: Document naming conventions for templates & backend configs
  website/docs/cli/config/config-file.html.md
  website/docs/language/functions/templatefile.html.md
  website/docs/language/settings/backends/configuration.html.md
  website/docs/language/settings/backends/remote.html.md
Labels: documentation

#28994 Upgrade cty to v1.8.4
  go.mod
  go.sum
Labels: 1.0-backport, upstream

#28998 Add links to terraform versions tutorials
  website/docs/language/settings/index.html.md
Labels: documentation

#29004 website: Explicit examples of -var escaping in various shells
  website/docs/cli/commands/plan.html.md
  website/docs/language/values/variables.html.md
Labels: cli, documentation, enhancement

#29048 command/views/json: Never generate invalid diagnostic snippet offsets
  internal/command/format/diagnostic.go
  internal/command/views/json/diagnostic.go
  internal/command/views/json/diagnostic_test.go
  internal/command/views/json/testdata/diagnostic/error-whose-range-starts-at-a-newline.json
Labels: bug, cli

#29049 command/jsonstate: remove redundant remarking of resource instance
  internal/command/jsonstate/state.go
  internal/command/jsonstate/state_test.go
Labels: 1.0-backport
