Repository hashicorp/terraform, pull requests merged in 2021-04, with the labels that each got.

#28267 Don't force data reads from dependency changes in sibling modules
  terraform/context_apply2_test.go
  terraform/context_plan2_test.go
  terraform/node_resource_abstract_instance.go
Labels: 0.15-backport

#28272 ensure plans always have a stored state
  terraform/context.go
  terraform/context_plan2_test.go
Labels: 0.15-backport

#28275 Add addresses to diagnostics
  backend/testing.go
  command/format/diagnostic.go
  command/meta_backend.go
  command/views/json/diagnostic.go
  plugin/convert/diagnostics_test.go
  plugin/grpc_error.go
  terraform/node_provider.go
  terraform/node_resource_abstract_instance.go
  terraform/node_resource_validate.go
  tfdiags/contextual.go
  tfdiags/contextual_test.go
  tfdiags/diagnostic.go
  tfdiags/diagnostic_base.go
Labels: 0.15-backport

#28317 restore saved dependencies on delete error
  terraform/context_apply_test.go
  terraform/node_resource_abstract_instance.go
Labels: 0.15-backport

#28326 lang/funcs: Make nonsensitive more permissive
  lang/funcs/sensitive.go
  lang/funcs/sensitive_test.go
  terraform/context_plan2_test.go
Labels: 0.15-backport, functions

#27454 lang/funcs: "one" function
  lang/funcs/collection.go
  lang/funcs/collection_test.go
  lang/functions.go
  lang/functions_test.go
  website/docs/language/functions/one.html.md
  website/layouts/language.erb
Labels: 0.15-backport, config, enhancement

#28355 website: v0.15 upgrade guide for sensitive resource attributes
  website/docs/language/expressions/references.html.md
  website/docs/language/values/outputs.html.md
  website/docs/language/values/variables.html.md
  website/upgrade-guides/0-15.html.markdown
Labels: 0.15-backport, documentation, enhancement

#28363 command: Add a newline before confirming apply
  backend/local/backend_apply.go
Labels: 0.15-backport, cli

#28329 tiny optimisations of dag.Set
  dag/set.go
  dag/set_test.go
Labels: 0.15-backport

#28381 core: Fix double-marked sensitive attributes
  terraform/context_apply2_test.go
  terraform/evaluate.go
  terraform/evaluate_test.go
Labels: 0.15-backport, core

#28387 website: Link to the v0.15 upgrade guide
  website/layouts/language.erb
Labels: 0.15-backport, bug, documentation

#28389 website: v0.15 Upgrade Guide entry for Azure Backend arguments
  website/upgrade-guides/0-15.html.markdown
Labels: 0.15-backport, bug, documentation, v0.15

#28409 cli: Fix remote backend UI issues
  command/apply.go
  command/plan.go
Labels: 0.15-backport, backend/remote, cli

#28412 cli: Fix missing apply summary for remote runs
  backend/remote/backend.go
  command/apply.go
Labels: 0.15-backport, backend/remote, cli

#28414 resolve provider types when building the config
  configs/config.go
  configs/config_build.go
  configs/provider.go
  configs/provider_validation.go
  configs/resource.go
  configs/testdata/valid-modules/nested-providers-fqns/child/main.tf
  configs/testdata/valid-modules/nested-providers-fqns/main.tf
Labels: 0.15-backport

#28444 wrong operation during destroy plan walk
  terraform/context.go
  terraform/context_plan2_test.go
Labels: 0.15-backport

#28446 lang/funcs: Conversion functions can handle sensitive values
  lang/funcs/conversion.go
  lang/funcs/conversion_test.go
Labels: 0.15-backport, bug, config

#26997 Port kubernetes backend config changes from kubernetes provider 2.0.0
  backend/remote-state/kubernetes/backend.go
  backend/remote-state/kubernetes/client.go
  website/docs/language/settings/backends/kubernetes.html.md
Labels: 0.14-backport, backend/k8s

#28457 additional null checks in provisioners
  builtin/provisioners/local-exec/resource_provisioner.go
  builtin/provisioners/local-exec/resource_provisioner_test.go
  builtin/provisioners/remote-exec/resource_provisioner.go
  builtin/provisioners/remote-exec/resource_provisioner_test.go
Labels: 0.15-backport

#28465 deps: update go-plugin to v1.4.1
  go.mod
  go.sum
Labels: 0.15-backport

#28460 dependencies: update cty from v1.8.1 to v1.8.2
  go.mod
  go.sum
Labels: 0.15-backport, config, dependencies, enhancement

#28472 core: Loosen output value sensitivity requirement
  terraform/context_plan2_test.go
  terraform/context_validate_test.go
  terraform/evaluate.go
  terraform/node_output.go
Labels: 0.15-backport, core

#28443 Add Learn link to Debugging
  website/docs/internals/debugging.html.md
Labels: 0.15-backport

#28479 New login success output for TFC/E
  command/login.go
  command/login_test.go
  command/meta.go
  command/testdata/login-tfe-server/tfeserver.go
Labels: 0.15-backport, cli

#28424 Better planing of unknown dynamic blocks
  configs/configschema/decoder_spec.go
  configs/configschema/decoder_spec_test.go
  go.mod
  go.sum
  lang/blocktoattr/fixup.go
  plans/objchange/compatible.go
  plans/objchange/compatible_test.go
  plans/objchange/objchange.go
  terraform/context_validate_test.go
Labels: 0.15-backport

#28539 Unmark config values when planning a data source read
  terraform/context_plan2_test.go
  terraform/node_resource_abstract.go
  terraform/node_resource_abstract_instance.go
  terraform/node_resource_abstract_test.go
  terraform/node_resource_apply_instance.go
  terraform/node_resource_destroy.go
  terraform/node_resource_destroy_deposed.go
  terraform/node_resource_plan_instance.go
  terraform/node_resource_plan_orphan.go
Labels: 0.15-backport

#28523 core: Add sensitive provider attrs to JSON plan
  command/jsonplan/plan.go
  command/show_test.go
  command/testdata/show-json-sensitive/main.tf
  command/testdata/show-json-sensitive/output.json
  configs/configschema/marks.go
  configs/configschema/marks_test.go
  terraform/evaluate.go
  terraform/evaluate_test.go
Labels: 0.15-backport, core

#28543 Add more diagnostic configuration context to provider methods
  terraform/node_provider.go
  terraform/node_provider_test.go
  terraform/node_resource_abstract_instance.go
Labels: 0.15-backport

#28553 remove codedov
  .circleci/config.yml
Labels: 0.13-backport, 0.14-backport, 0.15-backport

#28544 plans: Track an optional extra "reason" for some planned actions
  command/format/diff.go
  command/format/diff_test.go
  command/jsonplan/plan.go
  command/jsonplan/resource.go
  command/show_test.go
  command/testdata/show-json/requires-replace/main.tf
  command/testdata/show-json/requires-replace/output.json
  command/testdata/show-json/requires-replace/terraform.tfstate
  command/views/plan.go
  plans/changes.go
  plans/changes_src.go
  plans/internal/planproto/planfile.pb.go
  plans/internal/planproto/planfile.proto
  plans/planfile/tfplan.go
  plans/planfile/tfplan_test.go
  plans/resourceinstancechangeactionreason_string.go
  terraform/context_plan_test.go
  terraform/node_resource_abstract_instance.go
  terraform/testdata/plan-requires-replace/main.tf
  website/docs/internals/json-format.html.md
Labels: 0.15-backport, core, enhancement

#28566 cli: Add JSON logs for operations commands
  backend/local/backend_apply.go
  command/apply_test.go
  command/arguments/apply.go
  command/arguments/apply_test.go
  command/arguments/plan.go
  command/arguments/plan_test.go
  command/arguments/refresh.go
  command/arguments/refresh_test.go
  command/arguments/types.go
  command/testdata/apply/output.jsonlog
  command/views/apply.go
  command/views/apply_test.go
  command/views/hook_json.go
  command/views/hook_json_test.go
  command/views/json/change.go
  command/views/json/change_summary.go
  command/views/json/hook.go
  command/views/json/message_types.go
  command/views/json/output.go
  command/views/json/output_test.go
  command/views/json/resource_addr.go
  command/views/json_view.go
  command/views/json_view_test.go
  command/views/operation.go
  command/views/operation_test.go
  command/views/plan.go
  command/views/refresh.go
  command/views/refresh_test.go
Labels: 0.15-backport, cli, json-output

#28570 website: Reworking of the "terraform plan" docs, and related pages
  website/docs/cli/commands/apply.html.md
  website/docs/cli/commands/destroy.html.md
  website/docs/cli/commands/plan.html.md
  website/docs/cli/commands/refresh.html.md
  website/docs/cli/commands/taint.html.md
  website/docs/cli/commands/untaint.html.md
  website/docs/cli/state/resource-addressing.html.md
Labels: documentation, enhancement
