Repository hashicorp/terraform, pull requests merged in 2021-12, with the labels that each got.

#30056 update hcl@v2.11.0
  go.mod
  go.sum
Labels: 1.1-backport

#29945 Cloud: Update Terraform init -reconfigure prompt
  internal/command/meta_backend.go
Labels: cloud, 1.1-backport

#30061 Cloud: Apply without init error message
  internal/command/meta_backend.go
Labels: cloud, 1.1-backport

#30059 Cloud: Do not ask to migrate empty default workspace
  internal/command/meta_backend_migrate.go
Labels: cloud, 1.1-backport

#30062 update hcl@v2.11.1
  go.mod
  go.sum
Labels: 1.1-backport

#30037 Fix example for values-representation in docs for JSON Format internals
  website/docs/internals/json-format.html.md
Labels: documentation, review me!

#30028 Improve `.terraformignore` doc formatting
  website/docs/language/settings/backends/remote.html.md
Labels: documentation, review me!

#30046 Docs: Add newer Debian & Ubuntu versions to repo list
  website/docs/cli/install/apt.html.md
Labels: documentation, tw-reviewed

#29931 Website/Docs: debian install - run apt update first
  website/docs/cli/install/apt.html.md
Labels: documentation, tw-reviewed

#30100 Update note and add learn call out
  website/docs/language/modules/develop/refactoring.html.md
Labels: enhancement, 1.1-backport

#30103 website: Terraform v1.1 upgrade guide
  website/layouts/language.erb
  website/upgrade-guides/1-1.html.markdown
Labels: documentation, 1.1-backport

#30102 Add Terraform Cloud integration docs
  docs/architecture.md
  internal/backend/backend.go
  website/docs/cli/cloud/command-line-arguments.html.md
  website/docs/cli/cloud/index.html.md
  website/docs/cli/cloud/migrating.html.md
  website/docs/cli/cloud/settings.html.md
  website/docs/cli/state/move.html.md
  website/docs/cli/workspaces/index.html.md
  website/docs/language/settings/backends/artifactory.html.md
  website/docs/language/settings/backends/azurerm.html.md
  website/docs/language/settings/backends/configuration.html.md
  website/docs/language/settings/backends/consul.html.md
  website/docs/language/settings/backends/cos.html.md
  website/docs/language/settings/backends/etcd.html.md
  website/docs/language/settings/backends/etcdv3.html.md
  website/docs/language/settings/backends/gcs.html.md
  website/docs/language/settings/backends/http.html.md
  website/docs/language/settings/backends/index.html.md
  website/docs/language/settings/backends/kubernetes.html.md
  website/docs/language/settings/backends/manta.html.md
  website/docs/language/settings/backends/oss.html.md
  website/docs/language/settings/backends/pg.html.md
  website/docs/language/settings/backends/remote.html.md
  website/docs/language/settings/backends/s3.html.md
  website/docs/language/settings/backends/swift.html.md
  website/docs/language/settings/index.html.md
  website/docs/language/settings/terraform-cloud.html.md
  website/docs/language/state/remote.html.md
  website/docs/language/state/workspaces.html.md
  website/layouts/docs.erb
  website/layouts/language.erb
Labels: documentation, cloud, 1.1-backport

#30116 Update broken links
  website/docs/language/settings/backends/index.html.md
  website/docs/language/state/workspaces.html.md
Labels: 1.1-backport

#30123 Fix "Renaming a Module Call" example
  website/docs/language/modules/develop/refactoring.html.md
Labels: bug, documentation, 1.1-backport

#30151 core: Fix crash with orphaned module instance
  internal/command/format/diff.go
  internal/instances/expander.go
  internal/instances/expander_test.go
  internal/terraform/context_plan2_test.go
  internal/terraform/node_resource_plan_orphan.go
Labels: core, 1.1-backport

#30142 command/meta_backend: Allow the remote backend to have no workspaces [again]
  internal/command/meta_backend.go
Labels: backend/remote, 1.1-backport

#30171 use `cty.DynamicVal` for expanded resources during validation
  internal/terraform/context_plan_test.go
  internal/terraform/context_validate_test.go
  internal/terraform/evaluate.go
  internal/terraform/testdata/plan-self-ref-multi-all/main.tf
Labels: 1.1-backport

#30185 Cleanup panic output
  internal/logging/panic.go
Labels: 1.1-backport

#30189 Ignore unexpanded paths when validating move statements.
  internal/instances/expander.go
  internal/instances/set.go
  internal/instances/set_test.go
  internal/terraform/context_apply2_test.go
Labels: 1.1-backport

#30199 Apply graph failure handling
  internal/backend/local/backend_apply.go
  internal/terraform/context_apply.go
  internal/terraform/context_apply2_test.go
Labels: 1.1-backport

#30192 providercache: Discard lock entries for unused providers
  internal/command/init_test.go
  internal/command/testdata/init-provider-now-unused/main.tf
  internal/depsfile/locks.go
  internal/depsfile/locks_test.go
  internal/providercache/installer.go
  internal/providercache/installer_test.go
  website/docs/language/files/dependency-lock.mdx
Labels: bug, cli, v1.1, 1.1-backport

#30191 Update make website workflow
  Makefile
  website/README.md
Labels: 1.1-backport

#30223 Update taint command page to make alternative clearer
  website/docs/cli/commands/taint.mdx
Labels: documentation, 1.1-backport

#30095 skip provider resolution when there are errors
  internal/configs/config_build.go
  internal/configs/testdata/config-diagnostics/invalid-provider/errors
  internal/configs/testdata/config-diagnostics/invalid-provider/main.tf
  internal/configs/testdata/config-diagnostics/invalid-provider/mod/main.tf
  internal/configs/testdata/config-diagnostics/invalid-provider/warnings
Labels: 1.1-backport

#30233 refactoring: Move nested modules
  internal/refactoring/move_execute.go
  internal/refactoring/move_execute_test.go
Labels: cli, 1.1-backport

#30020 Cloud: Add parallelism back into the tests
  internal/cloud/e2e/apply_auto_approve_test.go
  internal/cloud/e2e/backend_apply_before_init_test.go
  internal/cloud/e2e/helper_test.go
  internal/cloud/e2e/init_with_empty_tags_test.go
  internal/cloud/e2e/main_test.go
  internal/cloud/e2e/migrate_state_multi_to_tfc_test.go
  internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go
  internal/cloud/e2e/migrate_state_single_to_tfc_test.go
  internal/cloud/e2e/migrate_state_tfc_to_other_test.go
  internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go
  internal/cloud/e2e/run_variables_test.go
Labels: cloud, 1.1-backport

#30247 website: Try function documentation "provably" vs "probably" typo
  website/docs/language/functions/try.mdx
Labels: bug, documentation, config, 1.1-backport

#30232 Handle move blocks within a module which is changing the index
  internal/addrs/module_instance_test.go
  internal/addrs/move_endpoint_module.go
  internal/addrs/move_endpoint_module_test.go
  internal/refactoring/move_execute.go
  internal/refactoring/move_statement.go
  internal/refactoring/move_statement_test.go
  internal/refactoring/move_validate_test.go
  internal/refactoring/testdata/move-statement-implied/child/move-statement-implied.tf
  internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf
Labels: 1.1-backport
