Repository hashicorp/terraform, pull requests merged in 2022-03, with the labels that each got.

#30575 build: Upgrade `alibaba-cloud-sdk-go` and `winrmtest` dependencies
  go.mod
  go.sum
Labels: build, security, 1.1-backport

#30595 build: Upgrade `alibaba-cloud-sdk-go` and `winrmtest` dependencies
  go.mod
  go.sum
Labels: build, security

#30639 configs: Refined error messages for mismatched provider passing
  internal/configs/config_build.go
  internal/configs/config_build_test.go
  internal/configs/provider.go
  internal/configs/provider_validation.go
  internal/configs/testdata/config-diagnostics/empty-configs/warnings
  internal/configs/testdata/config-diagnostics/incorrect-type/errors
  internal/configs/testdata/config-diagnostics/incorrect-type/warnings
  internal/configs/testdata/config-diagnostics/invalid-provider/warnings
  internal/configs/testdata/config-diagnostics/nested-provider/errors
  internal/configs/testdata/config-diagnostics/override-provider/errors
  internal/configs/testdata/config-diagnostics/pass-inherited-provider/main.tf
  internal/configs/testdata/config-diagnostics/pass-inherited-provider/warnings
  internal/configs/testdata/config-diagnostics/required-alias/errors
  internal/configs/testdata/config-diagnostics/unexpected-provider/warnings
  internal/configs/testdata/config-diagnostics/unknown-root-provider/warnings
Labels: enhancement, config

#30631 Document logical operators not short-circuiting
  website/docs/language/expressions/operators.mdx
Labels: documentation

#30637 Change aws.dest to aws.dst
  website/docs/language/modules/develop/providers.mdx
Labels: documentation

#30645 core: Fix expanded condition block validation
  internal/terraform/context_validate_test.go
  internal/terraform/node_resource_validate.go
  internal/terraform/node_resource_validate_test.go
Labels: core

#30658 core: Eval pre/postconditions in refresh-only mode
  internal/terraform/context_plan2_test.go
  internal/terraform/eval_conditions.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/node_output.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_apply_instance.go
  internal/terraform/node_resource_plan_instance.go
  internal/terraform/transform_output.go
  internal/tfdiags/diagnostic.go
  internal/tfdiags/hcl.go
Labels: core, experiment/preconditions_postconditions

#30653 Clearify which type of id is used in the documentation
  website/docs/cli/commands/import.mdx
  website/docs/cli/import/usage.mdx
Labels: documentation

#30659 core: Fix crashes when condition block expressions refer to sensitive values
  internal/terraform/context_plan2_test.go
  internal/terraform/eval_conditions.go
  internal/terraform/eval_variable.go
  internal/terraform/eval_variable_test.go
Labels: core, experiment/preconditions_postconditions

#30649 Documentation Update: Capture `cloud`/ `backend` block override behavior in docs
  website/docs/language/files/override.mdx
Labels: documentation

#30281 Terraform may be misled, not provider
  website/docs/cli/commands/refresh.mdx
Labels: documentation, tw-reviewed

#29972 fix: local variables should not be overridden by remote variables during `terraform import`
  internal/backend/remote/backend.go
  internal/backend/remote/backend_apply_test.go
  internal/backend/remote/backend_context.go
  internal/backend/remote/backend_context_test.go
  internal/backend/remote/backend_plan_test.go
  internal/backend/remote/backend_test.go
  internal/backend/remote/testdata/variables/main.tf
  internal/cloud/backend.go
  internal/cloud/backend_context.go
  internal/cloud/backend_context_test.go
  internal/cloud/testdata/variables/main.tf
Labels: enhancement

#30674 Update toset.mdx
  website/docs/language/functions/toset.mdx
Labels: documentation

#30684 functions: Fix sum() of all strings
  internal/lang/funcs/collection.go
  internal/lang/funcs/collection_test.go
Labels: functions, 1.1-backport

#30685 cli: Fix missing identifying attributes in diff
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: cli, 1.1-backport

#30702 Add note about powershell formatting
  website/docs/cli/commands/state/pull.mdx
  website/docs/cli/commands/state/push.mdx
Labels: 1.1-backport

#30720 Update comment for this transformer
  internal/terraform/transform_transitive_reduction.go
Labels: documentation

#30626 Pull changes from go-tfe 1.0
  go.mod
  go.sum
  internal/backend/remote/backend.go
  internal/backend/remote/backend_apply_test.go
  internal/backend/remote/backend_common.go
  internal/backend/remote/backend_context.go
  internal/backend/remote/backend_state.go
  internal/cloud/backend.go
  internal/cloud/backend_apply_test.go
  internal/cloud/backend_common.go
  internal/cloud/backend_context.go
  internal/cloud/backend_plan.go
  internal/cloud/backend_runTasks.go
  internal/cloud/backend_state.go
  internal/cloud/e2e/apply_auto_approve_test.go
  internal/cloud/e2e/helper_test.go
  internal/cloud/e2e/migrate_state_multi_to_tfc_test.go
  internal/cloud/e2e/migrate_state_remote_backend_to_tfc_test.go
  internal/cloud/e2e/migrate_state_single_to_tfc_test.go
  internal/cloud/e2e/migrate_state_tfc_to_tfc_test.go
  internal/cloud/tfe_client_mock.go
Labels: breaking-change, backend, cloud

#30728 Link workflow tutorials from docs
  website/docs/cli/commands/apply.mdx
  website/docs/cli/commands/init.mdx
  website/docs/cli/commands/plan.mdx
Labels: documentation

#30738 Update CHANGELOG.md
  CHANGELOG.md
Labels: go-tfe

#30712 Add PowerShell note to file provisioner page
  website/docs/language/resources/provisioners/file.mdx
Labels: powershell, 1.1-backport

#30747 Description of '-' symbol as used in format()
  website/docs/language/functions/format.mdx
Labels: documentation

#30423 Docs Update: Show example of state lock table access control
  website/docs/language/settings/backends/s3.mdx
Labels: provider/aws, documentation, tw-reviewed

#30511 Make state commands check required version (#28025)
  internal/command/command_test.go
  internal/command/meta.go
  internal/command/meta_test.go
  internal/command/state_mv.go
  internal/command/state_mv_test.go
  internal/command/state_pull.go
  internal/command/state_pull_test.go
  internal/command/state_push.go
  internal/command/state_push_test.go
  internal/command/state_replace_provider.go
  internal/command/state_replace_provider_test.go
  internal/command/state_rm.go
  internal/command/state_rm_test.go
  internal/command/taint.go
  internal/command/taint_test.go
  internal/command/testdata/command-check-required-version/main.tf
Labels: enhancement
