Repository hashicorp/terraform, pull requests merged in 2022-08, with the labels that each got.

#31545 Add note about module.path and local module sources
  website/docs/language/expressions/references.mdx
Labels: documentation, 1.2-backport

#31562 update json plan docs with drift output
  website/docs/internals/json-format.mdx
Labels: documentation, 1.2-backport

#31558 chore: remove `/docs`
  website/data/docs-nav-data.json
  website/docs/docs/glossary.mdx
  website/docs/docs/index.mdx
  website/docs/docs/partnerships.mdx
  website/docs/docs/terraform-tools.mdx
  website/img/docs/provider-program-steps.png
  website/img/docs/runtask-diagram.png
  website/img/docs/runtask-program-steps.png
  website/img/docs/terraform-integration-program-diagram.png
Labels: 1.1-backport, 1.2-backport

#31560 chore: delete `/guides` files
  website/data/guides-nav-data.json
  website/docs/guides/index.mdx
  website/docs/guides/terraform-provider-development-program.mdx
  website/img/docs/program-steps.png
  website/img/docs/verified-card.png
Labels: 1.1-backport, 1.2-backport

#31573 fix: validate implied provider names in submodules
  internal/configs/configload/loader_load_test.go
  internal/configs/configload/testdata/invalid-names-in-submodules/.terraform/modules/modules.json
  internal/configs/configload/testdata/invalid-names-in-submodules/main.tf
  internal/configs/configload/testdata/invalid-names-in-submodules/sub/main.tf
  internal/configs/provider_validation.go
Labels: bug, crash

#31590 fix: validate implied provider names in submodules
  internal/configs/configload/loader_load_test.go
  internal/configs/configload/testdata/invalid-names-in-submodules/.terraform/modules/modules.json
  internal/configs/configload/testdata/invalid-names-in-submodules/main.tf
  internal/configs/configload/testdata/invalid-names-in-submodules/sub/main.tf
  internal/configs/provider_validation.go
Labels: bug, crash

#31532 Account for `NestedType` in static traversal validation
  internal/configs/configschema/empty_value.go
  internal/configs/configschema/implied_type.go
  internal/configs/configschema/internal_validate.go
  internal/configs/configschema/validate_traversal.go
  internal/configs/configschema/validate_traversal_test.go
  internal/plans/objchange/objchange.go
Labels: 1.2-backport

#31576 validate deprecated attributes from static traversals
  internal/configs/configschema/validate_traversal.go
  internal/configs/configschema/validate_traversal_test.go
Labels: 1.2-backport

#31602 Update docs README backporting instructions
  website/README.md
Labels: tw-reviewed

#31608 don't lose warnings from static validation
  internal/lang/eval.go
  internal/terraform/context_validate_test.go
Labels: 1.2-backport

#31616 website: Remove the legacy v0.11 language documentation
  website/data/language-nav-data.json
  website/docs/language/configuration-0-11/data-sources.mdx
  website/docs/language/configuration-0-11/environment-variables.mdx
  website/docs/language/configuration-0-11/index.mdx
  website/docs/language/configuration-0-11/interpolation.mdx
  website/docs/language/configuration-0-11/load.mdx
  website/docs/language/configuration-0-11/locals.mdx
  website/docs/language/configuration-0-11/modules.mdx
  website/docs/language/configuration-0-11/outputs.mdx
  website/docs/language/configuration-0-11/override.mdx
  website/docs/language/configuration-0-11/providers.mdx
  website/docs/language/configuration-0-11/resources.mdx
  website/docs/language/configuration-0-11/syntax.mdx
  website/docs/language/configuration-0-11/terraform-enterprise.mdx
  website/docs/language/configuration-0-11/terraform.mdx
  website/docs/language/configuration-0-11/variables.mdx
Labels: enhancement, documentation, 1.2-backport

#31647 doc: use american english
  docs/destroying.md
Labels: documentation, 1.2-backport

#31648 typo: use destructions singular form
  docs/destroying.md
Labels: documentation

#31652 Backport of doc: use american english into v1.2
  docs/destroying.md
Labels: documentation

#31634 typeexpr: Replace null attr values with defaults
  internal/typeexpr/defaults.go
  internal/typeexpr/defaults_test.go
  website/docs/language/expressions/type-constraints.mdx
Labels: experiment/module_variable_optional_attrs

#31212 Update wording for 'path.cwd' to be explicit about implications
  website/docs/language/expressions/references.mdx
Labels: enhancement, documentation, tw-reviewed

#31637 docs: Use more consistent naming in Module Registry Protocol documentation
  website/docs/internals/module-registry-protocol.mdx
Labels: documentation, tw-reviewed, 1.2-backport

#31651 Migrating from Markdown to Form style Github issues.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#31672 docs: Fix condition example
  website/docs/language/expressions/custom-conditions.mdx
Labels: documentation, 1.2-backport

#31686 Remove future-facing statement from import page
  website/docs/cli/import/usage.mdx
Labels: documentation, 1.2-backport

#31687 lang/funcs: "timecmp" function
  internal/lang/funcs/datetime.go
  internal/lang/funcs/datetime_test.go
  internal/lang/functions.go
  internal/lang/functions_test.go
  website/data/language-nav-data.json
  website/docs/language/functions/timeadd.mdx
  website/docs/language/functions/timecmp.mdx
Labels: enhancement, config

#31697 build: Exclude .pb.go files from goimports checking
  scripts/goimportscheck.sh
Labels: bug, build

#31682 Update init.mdx
  website/docs/cli/commands/init.mdx
Labels: waiting-response, documentation

#31714 command: add destroy option to terraform apply help text
  internal/command/apply.go
Labels: 1.3-backport

#31636 ModuleSourceRemote String now considers query string (#31250)
  internal/addrs/module_source.go
  internal/addrs/module_source_test.go
Labels: bug
