Repository hashicorp/terraform, pull requests merged in 2022-10, with the labels that each got.

#31902 Prevent errors from NoOp deposed changes
  internal/terraform/context_plan2_test.go
  internal/terraform/transform_diff.go
Labels: 1.3-backport

#31876 Update custom-conditions.mdx
  website/docs/language/expressions/custom-conditions.mdx
Labels: enhancement, documentation, 1.3-backport

#31786 Add customer-managed encryption key (KMS) support to GCS backend
  go.mod
  internal/backend/remote-state/gcs/backend.go
  internal/backend/remote-state/gcs/backend_state.go
  internal/backend/remote-state/gcs/backend_test.go
  internal/backend/remote-state/gcs/client.go
  website/docs/language/settings/backends/gcs.mdx
Labels: enhancement, documentation, backend/gcs, tw-reviewed

#31914 special handling for legacy `ignore_changes = all`
  internal/terraform/context_plan_test.go
  internal/terraform/node_resource_abstract_instance.go
Labels: 1.3-backport

#31917 Extract more exact provider name when checking for destroy cycles
  internal/terraform/context_plan2_test.go
  internal/terraform/transform_destroy_edge.go
Labels: 1.3-backport

#31878 evaluation of missing instances during import
  internal/terraform/context_import_test.go
  internal/terraform/evaluate.go
  internal/terraform/testdata/import-provider-resources/main.tf
Labels: 1.3-backport

#31945 Update backends.mdx
  website/docs/language/state/backends.mdx
Labels: documentation, 1.2-backport, 1.3-backport

#31953 Add callout to Continuous Validation
  website/docs/language/expressions/custom-conditions.mdx
Labels: documentation, 1.3-backport

#31988 Fixing a bad link
  CHANGELOG.md
Labels: documentation

#31967 Add Private Service Connect endpoint support to GCS backend
  internal/backend/remote-state/gcs/backend.go
  website/docs/language/settings/backends/gcs.mdx
Labels: enhancement, backend/gcs

#31990 core: A NoOp orphan change has nothing to apply
  internal/terraform/context_apply2_test.go
  internal/terraform/node_resource_apply_instance.go
Labels: 1.3-backport

#31998 docs/plugin-protocol: Add notes about missing configuration in ReadResource and UpgradeResourceState request messages
  docs/plugin-protocol/tfplugin5.3.proto
  docs/plugin-protocol/tfplugin6.3.proto
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: documentation, providers/protocol

#31880 core: Simplify our idea of "root node" and require it for DynamicExpand
  internal/terraform/graph.go
  internal/terraform/node_local.go
  internal/terraform/node_module_variable.go
  internal/terraform/node_output.go
  internal/terraform/node_resource_apply.go
  internal/terraform/node_resource_import.go
  internal/terraform/node_resource_plan.go
  internal/terraform/transform_root.go
  internal/terraform/transform_root_test.go
Labels: enhancement, core

#31951 Add Documentation Issue form template
  .github/ISSUE_TEMPLATE/documentation_issue.yml
Labels: enhancement, documentation

#31908 go get -u golang.org/x/net
  go.mod
  go.sum
Labels: 1.3-backport

#32033 Update go-cty to latest version
  go.mod
  go.sum
Labels: 1.3-backport

#32051 Clean up handling of check-related graph nodes
  internal/plans/changes_sync.go
  internal/plans/plan.go
  internal/terraform/context.go
  internal/terraform/context_apply.go
  internal/terraform/context_apply2_test.go
  internal/terraform/context_eval_test.go
  internal/terraform/context_plan.go
  internal/terraform/evaluate.go
  internal/terraform/graph.go
  internal/terraform/graph_builder_apply.go
  internal/terraform/graph_builder_eval.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/node_output.go
  internal/terraform/transform_destroy_edge.go
  internal/terraform/transform_destroy_edge_test.go
  internal/terraform/transform_output.go
Labels: 1.3-backport

#31149 fix(docs): change set to list when recommending using toset()
  website/docs/language/meta-arguments/for_each.mdx
Labels: documentation, 1.3-backport

#31508 docs: fix typo regarding unknown values
  website/docs/language/expressions/references.mdx
Labels: documentation, tw-reviewed, 1.3-backport

#31792 Modifies permissions needed to use s3 with dynamoDb locks
  website/docs/language/settings/backends/s3.mdx
Labels: documentation, backend/s3, tw-reviewed, 1.3-backport

#31768 Update the # public providers estimate in the Terraform Intro
  website/docs/intro/index.mdx
Labels: documentation, 1.3-backport

#32065 Update GCS backend docs for TF >=0.12
  website/docs/language/settings/backends/gcs.mdx
Labels: documentation, backend/gcs

#31966 backend/azurerm: add support for generic OIDC authentication
  go.mod
  go.sum
  internal/backend/remote-state/azure/arm_client.go
  internal/backend/remote-state/azure/backend.go
  website/docs/language/settings/backends/azurerm.mdx
Labels: enhancement, provider/azurerm, 1.3-backport
