Repository hashicorp/terraform, pull requests merged in 2022-12, with the labels that each got.

#32322 chore: Update Digital Team Files
  website/Makefile
Labels: 1.1-backport, 1.2-backport, 1.3-backport

#32295 backend/oss: Ignore the getting oss endpoint error and using string concat instead; Improves the error message level
  internal/backend/remote-state/oss/backend.go
  internal/backend/remote-state/oss/client.go
Labels: backend/oss

#32351 build with Go 1.19.4
  .go-version
Labels: 1.3-backport

#32327 typo
  internal/terraform/evaluate.go
Labels: 1.3-backport

#32363 fix(unlock): amend force-unlock description
  internal/command/unlock.go
Labels: 1.3-backport

#32377 Use the apparentlymart/go-versions library to parse module constraints
  internal/initwd/module_install.go
  internal/initwd/module_install_test.go
  internal/initwd/testdata/prerelease-version-constraint-match/root.tf
  internal/initwd/testdata/prerelease-version-constraint/root.tf
Labels: 1.3-backport

#29520 Don't show symbols while input if variable marked as sensitive
  internal/backend/local/backend_local.go
Labels: enhancement

#31318 Bug fix: Terraform workspace command returns zero exit code when given an invalid argument.
  internal/command/workspace_command.go
Labels: bug

#31633 New Terraform Workspace select flag: `-or-create`
  internal/command/workspace_command.go
  internal/command/workspace_command_test.go
  internal/command/workspace_select.go
Labels: enhancement, workspaces

#32404 website: add missing Ubuntu apt repositories jammy and kinetic to the list
  website/docs/cli/install/apt.mdx
Labels: documentation, 1.3-backport
