Repository hashicorp/terraform, pull requests merged in 2022-09, with the labels that each got.

#31720 Remove Duplicate Divider for DevDot
  website/data/cli-nav-data.json
  website/data/internals-nav-data.json
  website/data/language-nav-data.json
Labels: documentation

#31729 Use upstreamed HCL typexpr package
  go.mod
  go.sum
  internal/configs/named_values.go
  internal/typeexpr/defaults.go
  internal/typeexpr/defaults_test.go
  internal/typeexpr/doc.go
  internal/typeexpr/get_type.go
  internal/typeexpr/get_type_test.go
  internal/typeexpr/public.go
  internal/typeexpr/type_string_test.go
  internal/typeexpr/type_type.go
  internal/typeexpr/type_type_test.go
Labels: 1.3-backport

#31752 Update frontmatter for devdot
  website/docs/cli/index.mdx
  website/docs/internals/index.mdx
  website/docs/language/index.mdx
Labels: documentation

#31547 Add more context about local backend configuration state file
  website/docs/language/settings/backends/configuration.mdx
Labels: 1.3-backport

#31484 Update Cloud Block Docs
  website/docs/language/settings/backends/remote.mdx
  website/docs/language/settings/terraform-cloud.mdx
Labels: documentation, 1.2-backport

#31774 Remove image borders
  website/img/docs/concrete-plan.png
  website/img/docs/in-progress-apply.png
  website/img/docs/intro-terraform-workflow.png
  website/img/docs/plan-comments.png
Labels: documentation

#31782 website: Version-specific upgrade guides (v1.2 branch)
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/0-10.mdx
  website/docs/language/upgrade-guides/0-11.mdx
  website/docs/language/upgrade-guides/0-12.mdx
  website/docs/language/upgrade-guides/0-13.mdx
  website/docs/language/upgrade-guides/0-14.mdx
  website/docs/language/upgrade-guides/0-15.mdx
  website/docs/language/upgrade-guides/0-7.mdx
  website/docs/language/upgrade-guides/0-8.mdx
  website/docs/language/upgrade-guides/0-9.mdx
  website/docs/language/upgrade-guides/1-0.mdx
  website/docs/language/upgrade-guides/1-1.mdx
  website/docs/language/upgrade-guides/1-2.mdx
  website/docs/language/upgrade-guides/index.mdx
  website/docs/language/v1-compatibility-promises.mdx
Labels: documentation

#31783 website: Version-specific upgrade guides (v1.1 branch)
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/1-1.mdx
  website/docs/language/upgrade-guides/index.mdx
  website/docs/language/v1-compatibility-promises.mdx
Labels: documentation

#31781 website: Version-specific upgrade guides (v1.3 branch)
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/0-10.mdx
  website/docs/language/upgrade-guides/0-11.mdx
  website/docs/language/upgrade-guides/0-12.mdx
  website/docs/language/upgrade-guides/0-13.mdx
  website/docs/language/upgrade-guides/0-14.mdx
  website/docs/language/upgrade-guides/0-15.mdx
  website/docs/language/upgrade-guides/0-7.mdx
  website/docs/language/upgrade-guides/0-8.mdx
  website/docs/language/upgrade-guides/0-9.mdx
  website/docs/language/upgrade-guides/1-0.mdx
  website/docs/language/upgrade-guides/1-1.mdx
  website/docs/language/upgrade-guides/1-2.mdx
  website/docs/language/upgrade-guides/index.mdx
  website/docs/language/v1-compatibility-promises.mdx
Labels: documentation

#31780 website: Version-specific upgrade guides (v1.4 branch)
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/0-10.mdx
  website/docs/language/upgrade-guides/0-11.mdx
  website/docs/language/upgrade-guides/0-12.mdx
  website/docs/language/upgrade-guides/0-13.mdx
  website/docs/language/upgrade-guides/0-14.mdx
  website/docs/language/upgrade-guides/0-15.mdx
  website/docs/language/upgrade-guides/0-7.mdx
  website/docs/language/upgrade-guides/0-8.mdx
  website/docs/language/upgrade-guides/0-9.mdx
  website/docs/language/upgrade-guides/1-0.mdx
  website/docs/language/upgrade-guides/1-1.mdx
  website/docs/language/upgrade-guides/1-2.mdx
  website/docs/language/upgrade-guides/index.mdx
  website/docs/language/v1-compatibility-promises.mdx
Labels: documentation

#31788 Remove legacy provisioners from docs
  website/data/language-nav-data.json
  website/docs/language/resources/provisioners/chef.mdx
  website/docs/language/resources/provisioners/habitat.mdx
  website/docs/language/resources/provisioners/puppet.mdx
  website/docs/language/resources/provisioners/salt-masterless.mdx
  website/docs/language/resources/provisioners/syntax.mdx
Labels: 1.2-backport, 1.3-backport

#31779 website: content updates for developer
  website/data/cli-nav-data.json
  website/data/internals-nav-data.json
  website/data/language-nav-data.json
  website/docs/cli/auth/index.mdx
  website/docs/cli/cloud/index.mdx
  website/docs/cli/cloud/migrating.mdx
  website/docs/cli/cloud/settings.mdx
  website/docs/cli/commands/import.mdx
  website/docs/cli/commands/index.mdx
  website/docs/cli/commands/init.mdx
  website/docs/cli/commands/plan.mdx
  website/docs/cli/commands/providers.mdx
  website/docs/cli/commands/refresh.mdx
  website/docs/cli/commands/workspace/index.mdx
  website/docs/cli/import/index.mdx
  website/docs/cli/import/usage.mdx
  website/docs/cli/index.mdx
  website/docs/cli/state/index.mdx
  website/docs/cli/state/move.mdx
  website/docs/internals/archiving.mdx
  website/docs/internals/debugging.mdx
  website/docs/internals/index.mdx
  website/docs/intro/index.mdx
  website/docs/intro/terraform-editions.mdx
  website/docs/intro/use-cases.mdx
  website/docs/language/attr-as-blocks.mdx
  website/docs/language/data-sources/index.mdx
  website/docs/language/expressions/conditionals.mdx
  website/docs/language/expressions/custom-conditions.mdx
  website/docs/language/expressions/function-calls.mdx
  website/docs/language/expressions/index.mdx
  website/docs/language/expressions/references.mdx
  website/docs/language/expressions/splat.mdx
  website/docs/language/files/dependency-lock.mdx
  website/docs/language/functions/index.mdx
  website/docs/language/index.mdx
  website/docs/language/meta-arguments/count.mdx
  website/docs/language/meta-arguments/for_each.mdx
  website/docs/language/meta-arguments/lifecycle.mdx
  website/docs/language/modules/develop/index.mdx
  website/docs/language/modules/develop/refactoring.mdx
  website/docs/language/modules/index.mdx
  website/docs/language/modules/sources.mdx
  website/docs/language/modules/syntax.mdx
  website/docs/language/providers/index.mdx
  website/docs/language/providers/requirements.mdx
  website/docs/language/resources/index.mdx
  website/docs/language/resources/provisioners/syntax.mdx
  website/docs/language/resources/syntax.mdx
  website/docs/language/settings/backends/configuration.mdx
  website/docs/language/settings/index.mdx
  website/docs/language/settings/terraform-cloud.mdx
  website/docs/language/values/locals.mdx
  website/docs/language/values/outputs.mdx
  website/docs/language/values/variables.mdx
  website/img/docs/concrete-plan.png
  website/img/docs/in-progress-apply.png
  website/img/docs/intro-terraform-workflow.png
  website/img/docs/plan-comments.png
Labels: 1.2-backport, 1.3-backport

#31797 Do not apply type defaults to null values
  internal/configs/named_values.go
  internal/configs/testdata/valid-files/object-optional-attrs.tf
  internal/terraform/context_apply_test.go
  internal/terraform/eval_variable.go
Labels: 1.3-backport

#31787 website: Terraform v1.3 upgrade guide
  website/docs/language/upgrade-guides/index.mdx
Labels: documentation

#31791 website: Tombstone callout for the v1.3 removed backends
  website/docs/language/settings/backends/configuration.mdx
Labels: documentation, 1.3-backport

#31812 Update taint.mdx
  website/docs/cli/commands/taint.mdx
Labels: documentation, 1.3-backport

#31818 Add internals overview page to navigation
  website/data/internals-nav-data.json
Labels: 1.2-backport, 1.3-backport

#31831 Remove unnecessary version note
  website/docs/language/expressions/type-constraints.mdx
Labels: 1.3-backport

#31598 insert missing infinitive particle
  website/docs/language/expressions/type-constraints.mdx
Labels: documentation, tw-reviewed

#31847 Upgrade hcl to fix crash with optional attributes
  go.mod
  go.sum
  internal/terraform/context_apply_test.go
Labels: 1.3-backport

#31813 redact sensitive output values in run logs
  internal/command/views/apply_test.go
  internal/command/views/json/output.go
  internal/command/views/json/output_test.go
  internal/command/views/json_view.go
  internal/command/views/refresh_test.go
Labels: enhancement

#31849 Update workspace documentation
  website/docs/cli/workspaces/index.mdx
  website/docs/language/state/workspaces.mdx
Labels: documentation, 1.3-backport

#31857 prevent cycles when connecting destroy nodes
  internal/terraform/context_apply2_test.go
  internal/terraform/transform_destroy_edge.go
Labels: 1.3-backport

#31858 prune unused nodes from a destroy plan graph
  internal/terraform/context_plan2_test.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/node_resource_plan.go
  internal/terraform/transform_destroy_edge.go
Labels: 1.3-backport

#31898 providercache: Improve installation error message
  internal/providercache/package_install.go
Labels: enhancement

#31907 website: Remove warning that yamlencode is experimental
  website/docs/language/functions/yamlencode.mdx
Labels: documentation
