Repository hashicorp/terraform, pull requests merged in 2022-11, with the labels that each got.

#32123 Apply optimizations for handling of condition checks
  internal/states/statefile/version4.go
  internal/terraform/context_apply.go
  internal/terraform/context_apply2_test.go
  internal/terraform/graph_builder_apply.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_apply_instance.go
  internal/terraform/node_resource_destroy.go
  internal/terraform/node_resource_destroy_deposed.go
  internal/terraform/transform_diff.go
  internal/terraform/transform_diff_test.go
  internal/terraform/transform_reference.go
Labels: 1.3-backport

#23965 S3 Backend : Bucket key should not contain trailing slash
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_test.go
Labels: backend/s3

#32027 Convert variable types before applying defaults
  go.mod
  go.sum
  internal/terraform/eval_variable.go
  internal/terraform/eval_variable_test.go
Labels: 1.3-backport

#32111 don't plan data source reads during refresh-only
  internal/terraform/context_refresh_test.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_plan_instance.go
Labels: 1.3-backport

#32115 don't lose checks from refresh-only plan
  internal/terraform/context_apply.go
Labels: 1.3-backport

#32141 ci: exclude .go-imports in goimports check
  scripts/goimportscheck.sh
Labels: 1.3-backport

#32135 Build with Go 1.19.3
  .go-version
Labels: bug, cli, 1.3-backport

#32125 fix broken links
  website/docs/language/functions/timeadd.mdx
  website/docs/language/functions/timecmp.mdx
Labels: documentation, 1.3-backport

#32004 fix: don't reveal nested attributes with sensitive schema
  internal/command/console_test.go
  internal/command/format/diff.go
  internal/command/format/diff_test.go
  internal/repl/format.go
  internal/repl/format_test.go
  website/docs/language/expressions/function-calls.mdx
  website/docs/language/expressions/references.mdx
  website/docs/language/functions/nonsensitive.mdx
  website/docs/language/functions/sensitive.mdx
  website/docs/language/values/outputs.mdx
  website/docs/language/values/variables.mdx
Labels: 1.3-backport

#31834 Looks like a copy-paste error
  website/docs/cli/commands/state/replace-provider.mdx
Labels: documentation, tw-reviewed, 1.3-backport

#31991 Document provider registry response property shasum
  website/docs/internals/provider-registry-protocol.mdx
Labels: documentation, tw-reviewed, 1.3-backport

#31274 Additional note on usage of single quotes for for_each resources
  website/docs/cli/commands/state/show.mdx
Labels: documentation, tw-reviewed, 1.3-backport

#32178 Update HCL and go-cty to fix optional and default attributes
  go.mod
  go.sum
  internal/terraform/eval_variable_test.go
Labels: 1.3-backport

#32231 docs: "How Terraform Uses Unicode" should mention HCL too
  docs/unicode.md
Labels: build

#31972 Fix typo
  website/docs/language/upgrade-guides/index.mdx
Labels: documentation

#32208 Make the pre-destroy refresh a full plan
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_plan.go
  internal/terraform/node_resource_plan_instance.go
Labels: 1.3-backport

#32207 Ensure destroy plan contains valid state values
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
Labels: 1.3-backport

#32249 Added a missing comma on backends.mdx
  website/docs/language/state/backends.mdx
Labels: documentation, 1.3-backport

#32250 Grammar and syntax fixes in import.mdx
  website/docs/language/state/import.mdx
Labels: documentation, 1.3-backport

#32241 Updating distro lists to be current as of 2022-11
  website/docs/cli/install/apt.mdx
  website/docs/cli/install/yum.mdx
Labels: documentation, 1.3-backport

#32203 go get cloud.google.com/go/storage@v1.28.0
  go.mod
  go.sum
  internal/plans/internal/planproto/planfile.pb.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: backend/gcs, config

#32256 Update index.mdx
  website/docs/cli/workspaces/index.mdx
Labels: documentation, 1.3-backport

#32261 fix: pre allocate for composite literal
  internal/backend/remote-state/gcs/backend.go
  internal/cloud/backend_plan.go
  internal/e2e/e2e.go
  internal/plugin6/convert/schema.go
Labels: waiting-response

#32246 A deleted orphan should have no planned change
  internal/terraform/node_resource_plan_orphan.go
  internal/terraform/node_resource_plan_orphan_test.go
Labels: 1.3-backport

#32236 check walkDestroy to help DestroyEdgeTransformer
  internal/terraform/graph_builder_apply.go
  internal/terraform/transform_destroy_edge.go
Labels: 1.3-backport

#31999 Update workspace delete command docs to reference RUM vs empty state
  internal/command/workspace_delete.go
  website/docs/cli/commands/workspace/delete.mdx
Labels: documentation, 1.3-backport

#32020 Remove future-facing language from docs (WIP)
  website/docs/cli/commands/index.mdx
  website/docs/cli/commands/validate.mdx
  website/docs/cli/import/importability.mdx
  website/docs/cli/import/index.mdx
  website/docs/cli/install/apt.mdx
  website/docs/cli/install/yum.mdx
  website/docs/cli/plugins/index.mdx
  website/docs/cli/plugins/signing.mdx
  website/docs/internals/credentials-helpers.mdx
  website/docs/internals/json-format.mdx
  website/docs/internals/login-protocol.mdx
  website/docs/internals/machine-readable-ui.mdx
  website/docs/internals/module-registry-protocol.mdx
  website/docs/internals/provider-network-mirror-protocol.mdx
  website/docs/internals/provider-registry-protocol.mdx
  website/docs/language/data-sources/index.mdx
  website/docs/language/expressions/for.mdx
  website/docs/language/expressions/type-constraints.mdx
  website/docs/language/meta-arguments/lifecycle.mdx
  website/docs/language/modules/syntax.mdx
  website/docs/language/modules/testing-experiment.mdx
  website/docs/language/providers/configuration.mdx
  website/docs/language/providers/requirements.mdx
  website/docs/language/resources/provisioners/syntax.mdx
  website/docs/language/settings/backends/remote.mdx
Labels: documentation, 1.3-backport

#32151 go get github.com/zclconf/go-cty-yaml@v1.0.3
  go.mod
  go.sum
  internal/lang/functions_test.go
Labels: bug, config, functions

#32307 don't re-set changes for refreshed outputs
  internal/terraform/node_output.go
Labels: 1.3-backport
