Repository hashicorp/terraform, pull requests merged in 2022-02, with the labels that each got.

#30431 Make -replace flag clearer
  website/docs/cli/commands/apply.mdx
  website/docs/cli/commands/plan.mdx
Labels: documentation, 1.1-backport

#30401 Preconditions and Postconditions
  internal/configs/checks.go
  internal/configs/experiments.go
  internal/configs/named_values.go
  internal/configs/parser_config.go
  internal/configs/parser_config_test.go
  internal/configs/resource.go
  internal/configs/testdata/error-files/precondition-postcondition-constant.tf
  internal/configs/testdata/invalid-files/data-reserved-lifecycle.tf
  internal/configs/testdata/invalid-files/data-resource-lifecycle.tf
  internal/configs/testdata/invalid-modules/preconditions-postconditions-experiment/preconditions-postconditions-experiment.tf
  internal/configs/testdata/warning-files/preconditions-postconditions-experiment.tf
  internal/experiments/experiment.go
  internal/lang/eval.go
  internal/terraform/context_apply2_test.go
  internal/terraform/context_plan2_test.go
  internal/terraform/eval_conditions.go
  internal/terraform/evaluate_valid.go
  internal/terraform/node_output.go
  internal/terraform/node_resource_abstract.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_apply_instance.go
  internal/terraform/node_resource_destroy.go
  internal/terraform/node_resource_destroy_deposed.go
  internal/terraform/node_resource_plan_instance.go
  internal/terraform/node_root_variable_test.go
  website/docs/language/expressions/preconditions-postconditions.html.mdx
Labels: core, experiment/preconditions_postconditions

#30462 configs: Validate pre/postcondition self-refs
  internal/configs/checks.go
  internal/configs/resource.go
  internal/configs/testdata/error-files/precondition-postcondition-selfref.tf
Labels: core, experiment/preconditions_postconditions

#30471 core: Remove unused PlanOpts.Validate
  internal/terraform/context_plan.go
  internal/terraform/context_validate.go
  internal/terraform/graph_builder_plan.go
Labels: core

#30017 Update go test commands in .github/CONTRIBUTING.md.
  .github/CONTRIBUTING.md
Labels: documentation

#30487 Update depends_on documentation
  website/docs/language/meta-arguments/depends_on.mdx
Labels: documentation

#30485 delete comma from single entry list
  website/docs/language/meta-arguments/depends_on.mdx
Labels: documentation

#30488 Update Console Command Documentation
  website/docs/cli/commands/console.mdx
Labels: 1.1-backport

#30503 Clarify workspace.name expression
  website/docs/language/settings/backends/remote.mdx
  website/docs/language/state/workspaces.mdx
Labels: core, documentation, 1.1-backport

#29839 Return exit code 1 when source address doesn't exist
  internal/command/state_mv.go
  internal/command/state_mv_test.go
Labels: cli, 1.1-backport

#30520 cli: Fix state mv exit code for missing resource (#29839)
  internal/command/state_mv.go
  internal/command/state_mv_test.go
Labels: cli

#30483 Adds documentation to `substr` function to cover when `length` exceeds input length
  website/docs/language/functions/substr.mdx
Labels: documentation, tw-reviewed

#30561 jsonplan: Improve performance for deep objects
  internal/command/jsonplan/plan.go
  internal/command/jsonplan/plan_test.go
Labels: cli, performance, 1.1-backport

#30574 [Docs] Added github.com commit reference example
  website/docs/language/modules/sources.mdx
Labels: documentation, tw-reviewed

#30580 Fix broken link on provisioners connection page
  website/docs/language/resources/provisioners/connection.mdx
Labels: core, 1.1-backport

#30141 Cloud run tasks (post-plan only) CLI integration
  go.mod
  go.sum
  internal/cloud/backend_common.go
  internal/cloud/backend_plan.go
  internal/cloud/backend_runTasks.go
  internal/cloud/backend_runTasks_test.go
  internal/cloud/cloud_integration.go
Labels: cloud
