Repository hashicorp/terraform, pull requests merged in 2022-01, with the labels that each got.

#30254 getmodules: Use go-getter v1.5.10 and return to upstream GitGetter
  go.mod
  go.sum
  internal/getmodules/getter.go
  internal/getmodules/git_getter.go
  internal/getmodules/git_getter_test.go
  website/docs/language/modules/sources.mdx
Labels: dependencies

#30067 lang/funcs: Redact sensitive values from function errors
  internal/lang/funcs/collection.go
  internal/lang/funcs/collection_test.go
  internal/lang/funcs/encoding.go
  internal/lang/funcs/encoding_test.go
  internal/lang/funcs/filesystem.go
  internal/lang/funcs/filesystem_test.go
  internal/lang/funcs/number.go
  internal/lang/funcs/number_test.go
  internal/lang/funcs/redact.go
  internal/lang/funcs/redact_test.go
  internal/lang/funcs/testdata/unreadable/foobar
Labels: functions, 1.1-backport

#30286 dag: minor cleanup
  internal/dag/dag.go
  internal/dag/dag_test.go
Labels: 1.1-backport

#30237 Store website nav files (main)
  website/data/cli-nav-data.json
  website/data/configuration-nav-data.json
  website/data/guides-nav-data.json
  website/data/internals-nav-data.json
  website/data/intro-nav-data.json
  website/data/language-nav-data.json
Labels: 1.1-backport

#30264 docs: Fix typo in docs/plugin-protocol/releasing-new-version.md
  docs/plugin-protocol/releasing-new-version.md
Labels: documentation

#30270 Update variables.mdx to fix typo
  website/docs/language/values/variables.mdx
Labels: documentation

#30297 website: Documentation of how provisioners upload files
  website/docs/language/resources/provisioners/connection.mdx
  website/docs/language/resources/provisioners/file.mdx
  website/docs/language/upgrade-guides/1-1.mdx
Labels: enhancement, documentation, 1.1-backport

#30300 build: CGO_ENABLED when building for macOS in our experimental new build workflow
  .github/workflows/build.yml
Labels: bug, build, 1.1-backport

#30280 Update local values definition
  website/docs/language/values/locals.mdx
Labels: documentation

#30226 Sort dependencies when encoding `ResourceInstanceObject`
  internal/states/instance_object.go
  internal/states/instance_object_test.go
Labels: 1.1-backport

#30327 core: Invalid for_each argument messaging improvements
  internal/terraform/eval_for_each.go
  internal/terraform/eval_for_each_test.go
Labels: enhancement, core

#30335 website: CLI state manipulation section de-emphasize old features
  website/docs/cli/state/index.mdx
  website/docs/cli/state/move.mdx
  website/docs/cli/state/taint.mdx
Labels: enhancement, documentation, cli, 1.1-backport

#30332 Fix broken links to external docs
  website/docs/language/resources/provisioners/salt-masterless.mdx
Labels: documentation, 1.1-backport

#30333 refactoring: Implied move statements can be cross-package
  internal/refactoring/move_validate.go
  internal/refactoring/move_validate_test.go
Labels: bug, config, 1.1-backport

#30334 lang/funcs: fileexists slightly better "not a file" error message
  internal/lang/funcs/filesystem.go
  internal/lang/funcs/filesystem_test.go
Labels: enhancement, build, config, 1.1-backport

#30344 cli: Refactor show command & migrate to command arguments and views
  internal/backend/backend.go
  internal/backend/local/backend_local.go
  internal/command/arguments/show.go
  internal/command/arguments/show_test.go
  internal/command/show.go
  internal/command/show_test.go
  internal/command/testdata/show-json-state/empty/terraform.tfstate
  internal/command/testdata/show-json-state/no-state/output.json
  internal/command/views/show.go
  internal/command/views/show_test.go
  internal/command/views/testdata/show/main.tf
Labels: cli, backend/local

#30375 Introduce Terraform Plugin Protocol 6.2 with legacy_type_system fields from Protocol 5
  docs/plugin-protocol/tfplugin6.2.proto
  internal/plugin6/grpc_provider.go
  internal/tfplugin6/tfplugin6.pb.go
  internal/tfplugin6/tfplugin6.proto
Labels: enhancement, 1.1-backport, providers/protocol

#30379 Backport of Introduce Terraform Plugin Protocol 6.2 with legacy_type_system fields from Protocol 5 into v1.1
  docs/plugin-protocol/tfplugin6.2.proto
  internal/plugin6/grpc_provider.go
  internal/tfplugin6/tfplugin6.pb.go
  internal/tfplugin6/tfplugin6.proto
Labels: enhancement, providers/protocol

#30363 Update aws-sdk-go dependency to support new region (Jakarta)
  go.mod
  go.sum
Labels: backend/s3, 1.1-backport

#30371 Typo in zipmap documentation
  website/docs/language/functions/zipmap.mdx
Labels: documentation

#30316 Fix autocomplete for workspace subcommands
  internal/command/autocomplete.go
  internal/command/workspace_delete.go
  internal/command/workspace_new.go
  internal/command/workspace_select.go
Labels: cli, 1.1-backport

#30296 Fix provisioners content
  website/data/language-nav-data.json
  website/docs/language/resources/index.mdx
  website/docs/language/resources/provisioners/chef.mdx
  website/docs/language/resources/provisioners/connection.mdx
  website/docs/language/resources/provisioners/file.mdx
  website/docs/language/resources/provisioners/habitat.mdx
  website/docs/language/resources/provisioners/index.mdx
  website/docs/language/resources/provisioners/local-exec.mdx
  website/docs/language/resources/provisioners/null_resource.mdx
  website/docs/language/resources/provisioners/puppet.mdx
  website/docs/language/resources/provisioners/remote-exec.mdx
  website/docs/language/resources/provisioners/salt-masterless.mdx
  website/docs/language/resources/syntax.mdx
Labels: documentation, 1.1-backport

#30402 build: Remove broken website link check job
  .circleci/config.yml
Labels: build

#30235 [WIP] Fix remaining remote backend references
  website/docs/cli/commands/import.mdx
  website/docs/cli/commands/push.mdx
  website/docs/cli/commands/state/mv.mdx
  website/docs/cli/commands/state/push.mdx
  website/docs/cli/commands/state/replace-provider.mdx
  website/docs/cli/commands/state/rm.mdx
  website/docs/cli/commands/taint.mdx
  website/docs/cli/commands/untaint.mdx
  website/docs/cli/commands/validate.mdx
  website/docs/cli/config/environment-variables.mdx
  website/docs/cli/import/index.mdx
  website/docs/language/modules/sources.mdx
  website/docs/language/state/remote-state-data.mdx
  website/intro/core-workflow.mdx
Labels: documentation, 1.1-backport

#30399 Revamp Into to Terraform
  website/data/intro-nav-data.json
  website/intro/index.mdx
  website/intro/terraform-editions.mdx
  website/intro/use-cases.mdx
  website/intro/vs/index.mdx
Labels: documentation, 1.1-backport

#30425 fix image references on intro page
  website/intro/index.mdx
Labels: documentation, 1.1-backport

#30409 Fix reference to child module in outputs docs
  website/docs/language/values/outputs.mdx
Labels: documentation, 1.1-backport

#30408 Add merged pull request reminder 📎
  .github/workflows/merged-pr.yml
Labels: build

#30421 core: Fix plan write/state write ordering bug
  internal/terraform/node_resource_plan_instance.go
Labels: core

#30428 Fixing some final typos and nits
  website/intro/index.mdx
  website/intro/use-cases.mdx
Labels: documentation, 1.1-backport

#30397 Improve the help.go docs: typo and a more explicit comment.
  help.go
Labels: documentation
