Repository hashicorp/terraform, pull requests merged in 2022-06, with the labels that each got.

#31184 Return early on GetProviderSchema RPC responses with error diagnostics
  internal/plugin/grpc_provider.go
  internal/plugin/grpc_provider_test.go
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
Labels: bug, providers, 1.2-backport

#31154 Add inline defaults to optional object attribute type constraints
  internal/configs/named_values.go
  internal/configs/testdata/warning-files/object-optional-attrs-experiment.tf
  internal/lang/funcs/defaults.go
  internal/lang/funcs/defaults_test.go
  internal/lang/functions.go
  internal/lang/functions_test.go
  internal/terraform/context_apply_test.go
  internal/terraform/eval_variable.go
  internal/typeexpr/defaults.go
  internal/typeexpr/defaults_test.go
  internal/typeexpr/get_type.go
  internal/typeexpr/get_type_test.go
  internal/typeexpr/public.go
  website/data/language-nav-data.json
  website/docs/language/expressions/type-constraints.mdx
  website/docs/language/functions/defaults.mdx
  website/layouts/language.erb
Labels: experiment/module_variable_optional_attrs

#31198 Add guidance about using the format function
  website/docs/language/expressions/custom-conditions.mdx
Labels: 1.2-backport

#31215 deprecate unmaintained remote state backends
  internal/backend/init/init.go
  internal/backend/init/init_test.go
Labels: 1.2-backport

#31191 docs: update depends_on.mdx meta-argument
  website/docs/language/meta-arguments/depends_on.mdx
Labels: documentation, 1.2-backport

#31213 Revise Backends Config Page
  website/data/language-nav-data.json
  website/docs/language/settings/backends/artifactory.mdx
  website/docs/language/settings/backends/azurerm.mdx
  website/docs/language/settings/backends/configuration.mdx
  website/docs/language/settings/backends/consul.mdx
  website/docs/language/settings/backends/cos.mdx
  website/docs/language/settings/backends/etcd.mdx
  website/docs/language/settings/backends/etcdv3.mdx
  website/docs/language/settings/backends/gcs.mdx
  website/docs/language/settings/backends/http.mdx
  website/docs/language/settings/backends/index.mdx
  website/docs/language/settings/backends/kubernetes.mdx
  website/docs/language/settings/backends/manta.mdx
  website/docs/language/settings/backends/oss.mdx
  website/docs/language/settings/backends/pg.mdx
  website/docs/language/settings/backends/remote.mdx
  website/docs/language/settings/backends/s3.mdx
  website/docs/language/settings/backends/swift.mdx
Labels: documentation, 1.2-backport

#31204 Update syntax.mdx
  website/docs/language/resources/syntax.mdx
Labels: documentation, 1.2-backport

#31237 update go-getter@v1.6.2
  go.mod
  go.sum
Labels: 1.2-backport

#31227 Fix a wrong usage of sudo in debian install doc
  website/docs/cli/install/apt.mdx
Labels: documentation

#31240 Add internals to the sidebar
  website/data/cli-nav-data.json
  website/data/internals-nav-data.json
  website/data/language-nav-data.json
Labels: documentation, 1.2-backport

#31223 Backend/COS: remove COS object lock tag either when unlock remote state
  internal/backend/remote-state/cos/client.go
Labels: enhancement, backend/cos, 1.2-backport

#31246 copy dependency values when sorting
  internal/terraform/node_resource_plan.go
  internal/terraform/node_resource_plan_instance.go
Labels: 1.2-backport

#31218 Validate duplicate provider local names in `required_providers`
  internal/configs/config_test.go
  internal/configs/provider_validation.go
  internal/configs/testdata/duplicate-local-name/main.tf
  internal/terraform/transform_provider.go
  internal/terraform/transform_provider_test.go
Labels: 1.2-backport

#30275 Update purpose.mdx
  website/docs/language/state/purpose.mdx
Labels: documentation, tw-reviewed, 1.2-backport

#31236 json-output: Fix unknowns for tuples and sets
  internal/command/jsonplan/plan.go
  internal/command/jsonplan/plan_test.go
Labels: bug, json-output

#31235 json-output: Extended detail for unknown outputs
  internal/command/jsonplan/plan.go
  internal/command/testdata/show-json/unknown-output/main.tf
  internal/command/testdata/show-json/unknown-output/output.json
Labels: json-output

#31263 states/remote: Check for LockError error type
  internal/states/remote/testing.go
Labels: 1.2-backport

#31210 Edit type constraints docs for style and flow
  internal/configs/experiments.go
  internal/configs/testdata/invalid-modules/object-optional-attrs-experiment/object-optional-attrs-experiment.tf
  internal/configs/testdata/valid-files/object-optional-attrs-experiment.tf
  internal/experiments/experiment.go
  internal/terraform/context_apply_test.go
  website/docs/language/expressions/type-constraints.mdx
Labels: documentation, experiment/module_variable_optional_attrs

#30948 Experiments supported only in alpha/dev builds
  commands.go
  experiments.go
  internal/command/meta.go
  internal/command/meta_config.go
  internal/configs/configload/loader.go
  internal/configs/experiments.go
  internal/configs/experiments_test.go
  internal/configs/parser.go
  internal/configs/parser_config.go
  internal/configs/testdata/valid-files/object-optional-attrs-experiment.tf
  internal/terraform/terraform_test.go
  main.go
Labels: enhancement, build

#31293 Performance: string builder speedup for Module.String()
  internal/addrs/module.go
  internal/addrs/module_test.go
Labels: performance, 1.2-backport

#31298 Clarify how the ~> version constraint operator works
  website/docs/language/providers/requirements.mdx
Labels: documentation, 1.2-backport

#31197 Update apply page for style, concision, and clarity
  website/docs/cli/commands/apply.mdx
  website/docs/cli/commands/plan.mdx
Labels: documentation, 1.2-backport

#29865 Update READMEs to help folks figure out how to successfully make docs
  README.md
  website/README.md
Labels: documentation

#31011 Added example with function argument expansion
  website/docs/language/functions/merge.mdx
Labels: documentation, 1.2-backport

#31331 Fail global required_version check if it contains any prerelease fields
  go.mod
  go.sum
  internal/terraform/context_test.go
  internal/terraform/version_required.go
Labels: 1.2-backport
