Repository hashicorp/terraform, pull requests merged in 2022-05, with the labels that each got.

#30975 Add note about lockfile's relationship to state
  website/docs/language/files/dependency-lock.mdx
Labels: documentation, 1.2-backport

#30979 check for cancellation before apply confirmation
  internal/backend/local/backend_apply.go
  internal/backend/local/backend_apply_test.go
Labels: 1.2-backport

#30984 communicator/ssh: Fix crash using SSH+HTTP proxy
  internal/communicator/ssh/communicator.go
Labels: crash, 1.2-backport

#30987 plugin: diagnostics must be checked on all schema calls
  internal/plugin/grpc_provider.go
  internal/plugin6/grpc_provider.go
Labels: 1.2-backport

#31008 Fix custom conditions Markdown typo
  website/docs/language/expressions/custom-conditions.mdx
Labels: documentation, 1.2-backport

#30969 Add warning about spaces in variable value assignment
  website/docs/cli/commands/plan.mdx
Labels: documentation

#31010 Add missing syntax highlighting for terraform snippets
  website/docs/language/values/variables.mdx
Labels: documentation

#31059 Change private to public in custom conditions example
  website/docs/language/expressions/custom-conditions.mdx
Labels: documentation

#31063 v1.2 upgrade guide
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/1-2.mdx
Labels: documentation, v1.2

#31049 `local-exec` documentation lacks on-destroy documentation
  website/docs/language/resources/provisioners/local-exec.mdx
Labels: documentation

#31091 configs: fix module for_each call bug
  internal/configs/provider_validation.go
Labels: 1.2-backport

#31092 update golang.org/x/crypto again
  go.mod
  go.sum
Labels: 1.2-backport

#29354 Fix CLI help text for output.
  internal/command/output.go
Labels: enhancement, documentation

#31097 configs: A test for the regression reported in #31081
  internal/configs/configload/loader_load_test.go
  internal/configs/configload/testdata/child-provider-child-count/.terraform/modules/modules.json
  internal/configs/configload/testdata/child-provider-child-count/child-provider-child-count.tf
  internal/configs/configload/testdata/child-provider-child-count/child/child-provider-child-count-child.tf
  internal/configs/configload/testdata/child-provider-child-count/grandchild/child-provider-child-count-grandchild.tf
  internal/configs/configload/testdata/child-provider-grandchild-count/.terraform/modules/modules.json
  internal/configs/configload/testdata/child-provider-grandchild-count/child-provider-grandchild-count.tf
  internal/configs/configload/testdata/child-provider-grandchild-count/child/child-provider-grandchild-count-child.tf
  internal/configs/configload/testdata/child-provider-grandchild-count/grandchild/child-provider-grandchild-count-grandchild.tf
Labels: 1.2-backport

#31060 configs: Fix module loader nil pointer panic
  internal/configs/configload/loader_load.go
  internal/configs/configload/loader_snapshot_test.go
  internal/configs/configload/loader_test.go
  internal/configs/configload/testdata/already-installed-now-invalid/.terraform/modules/modules.json
  internal/configs/configload/testdata/already-installed-now-invalid/foo/bar/main.tf
  internal/configs/configload/testdata/already-installed-now-invalid/foo/main.tf
  internal/configs/configload/testdata/already-installed-now-invalid/root.tf
Labels: config, 1.2-backport

#31124 update go-getter
  go.mod
  go.sum
Labels: 1.2-backport

#31129 Edit docs for replace_triggered_by lifecycle argument
  website/docs/language/meta-arguments/lifecycle.mdx
Labels: 1.2-backport

#30985 cli: Improved error for invalid -var "foo = bar"
  internal/command/meta_vars.go
  internal/command/plan_test.go
Labels: cli, 1.2-backport

#30552 Fixes #29156: Failing sensitive variables values are not logged
  internal/terraform/eval_variable.go
  internal/terraform/eval_variable_test.go
Labels: enhancement, 1.2-backport

#30993 add url to run task summary
  internal/cloud/backend_runTasks.go
Labels: 1.2-backport
