Repository hashicorp/terraform, pull requests merged in 2022-04, with the labels that each got.

#30352 internal/backend/remote-state/oss: fix dropped error
  internal/backend/remote-state/oss/backend_state.go
Labels: bug, backend/oss

#30766 command/format: Correctly quote diff object keys
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: 1.1-backport

#30752 core: Store condition block results in plan
  internal/addrs/check.go
  internal/addrs/checktype_string.go
  internal/addrs/output_value.go
  internal/addrs/output_value_test.go
  internal/addrs/resource.go
  internal/command/jsonplan/condition.go
  internal/command/jsonplan/plan.go
  internal/command/show_test.go
  internal/command/testdata/show-json/conditions/for-refresh.tfstate
  internal/command/testdata/show-json/conditions/main.tf
  internal/command/testdata/show-json/conditions/output-refresh-only.json
  internal/command/testdata/show-json/conditions/output.json
  internal/plans/conditions.go
  internal/plans/internal/planproto/planfile.pb.go
  internal/plans/internal/planproto/planfile.proto
  internal/plans/plan.go
  internal/plans/planfile/planfile_test.go
  internal/plans/planfile/tfplan.go
  internal/plans/planfile/tfplan_test.go
  internal/terraform/context_apply.go
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
  internal/terraform/context_walk.go
  internal/terraform/eval_conditions.go
  internal/terraform/eval_context.go
  internal/terraform/eval_context_builtin.go
  internal/terraform/eval_context_mock.go
  internal/terraform/graph_walk_context.go
  internal/terraform/node_output.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_apply_instance.go
  internal/terraform/node_resource_plan_instance.go
Labels: core, experiment/preconditions_postconditions

#30792 Conclude preconditions/postconditions experiment
  internal/command/testdata/show-json/conditions/main.tf
  internal/configs/experiments.go
  internal/configs/testdata/invalid-modules/preconditions-postconditions-experiment/preconditions-postconditions-experiment.tf
  internal/configs/testdata/valid-files/preconditions-postconditions.tf
  internal/experiments/experiment.go
  internal/terraform/context_apply2_test.go
  internal/terraform/context_plan2_test.go
  internal/terraform/context_validate_test.go
Labels: experiment/preconditions_postconditions

#30825 cli: Fix plan diff for sensitive nested attributes
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: crash, cli, 1.1-backport

#30855 cli: Fix double-quoted map keys in diff UI
  internal/command/format/diff.go
  internal/command/format/diff_test.go
Labels: cli, 1.1-backport

#30830 data schema changes may prevent state decoding
  internal/terraform/context_plan2_test.go
  internal/terraform/node_resource_abstract.go
  internal/terraform/node_resource_plan_instance.go
  internal/terraform/upgrade_resource_state.go
Labels: 1.1-backport

#30891 backend/remote-state/azure: defaulting the Azure Backend to use MSAL
  internal/backend/remote-state/azure/backend.go
  internal/backend/testing.go
  website/docs/language/settings/backends/azurerm.mdx
Labels: enhancement, documentation, backend/azure

#30879 lang/funcs: type conversion functions can convert null values
  internal/lang/funcs/conversion.go
  internal/lang/funcs/conversion_test.go
Labels: bug, config

#30884 fix typo in struct tag
  internal/states/statefile/version4.go
Labels: bug

#30915 change action to pull v1 instead of main
  .github/workflows/build.yml
Labels: v1.1

#30914 Bump mitchellh/cli from 1.1.2 to 1.1.3
  go.mod
  go.sum
Labels: 1.1-backport

#30920 build: go get github.com/hashicorp/hcl/v2@v2.12.0
  go.mod
  go.sum
Labels: enhancement, config

#30931 replace_triggered_by docs
  website/docs/language/meta-arguments/lifecycle.mdx
  website/docs/language/resources/behavior.mdx
Labels: documentation

#30932 Fix an example for urlencode.mdx
  website/docs/language/functions/urlencode.mdx
Labels: documentation

#30938 chore: Typo fix
  website/docs/language/functions/type.mdx
Labels: documentation

#30945 json-output: Add output type to JSON format
  internal/command/jsonplan/plan.go
  internal/command/jsonplan/values.go
  internal/command/jsonplan/values_test.go
  internal/command/jsonstate/state.go
  internal/command/jsonstate/state_test.go
  internal/command/testdata/show-json-sensitive/output.json
  internal/command/testdata/show-json-state/modules/output.json
  internal/command/testdata/show-json/basic-create/output.json
  internal/command/testdata/show-json/basic-delete/output.json
  internal/command/testdata/show-json/basic-update/output.json
  internal/command/testdata/show-json/conditions/output-refresh-only.json
  internal/command/testdata/show-json/modules/output.json
  internal/command/testdata/show-json/multi-resource-update/output.json
  internal/command/testdata/show-json/provider-version-no-config/output.json
  internal/command/testdata/show-json/provider-version/output.json
  internal/command/testdata/show-json/sensitive-values/output.json
  website/docs/internals/json-format.mdx
Labels: json-output, 1.1-backport

#30936 backend/remote-state/azure: support OIDC authentication
  go.mod
  go.sum
  internal/backend/remote-state/azure/arm_client.go
  internal/backend/remote-state/azure/backend.go
  internal/backend/remote-state/azure/backend_test.go
  internal/backend/remote-state/azure/helpers_test.go
  website/docs/language/settings/backends/azurerm.mdx
Labels: enhancement, documentation, backend/azure

#30274 communicator/ssh: Add support SSH over HTTP Proxy
  internal/communicator/shared/shared.go
  internal/communicator/ssh/communicator.go
  internal/communicator/ssh/http_proxy.go
  internal/communicator/ssh/provisioner.go
  internal/communicator/ssh/provisioner_test.go
  internal/terraform/node_resource_validate.go
  website/docs/language/resources/provisioners/connection.mdx
Labels: enhancement, provisioner/remote-exec

#30962 udpate x/crypto/ssh
  go.mod
  go.sum
Labels: 1.2-backport

#30956 Update apt.mdx
  website/docs/cli/install/apt.mdx
Labels: documentation
