Repository hashicorp/terraform, pull requests merged in 2023-01, with the labels that each got.

#32428 don't panic with a null list block value in config
  internal/plans/objchange/plan_valid.go
  internal/plans/objchange/plan_valid_test.go
Labels: 1.3-backport

#32464 Ensure we have all references for output preconditions
  internal/terraform/context_apply2_test.go
  internal/terraform/node_output.go
Labels: 1.3-backport

#32463 NestingSingle blocks can be null
  internal/plans/objchange/objchange.go
  internal/plans/objchange/objchange_test.go
Labels: 1.3-backport

#32514 removed double negation
  website/docs/cli/import/importability.mdx
Labels: documentation, 1.3-backport

#32547 fix the outputs of equivalence tests that were executed with the wrong version
  testing/equivalence-tests/outputs/data_read/plan
  testing/equivalence-tests/outputs/drift_relevant_attributes/plan
  testing/equivalence-tests/outputs/drift_relevant_attributes/plan.json
  testing/equivalence-tests/outputs/drift_relevant_attributes/state.json
  testing/equivalence-tests/tests/drift_relevant_attributes/terraform.resource/f6f74ca6-e8ef-e51f-522c-433b9ed5038f.json
Labels: 1.3-backport

#32549 Fix Examples ip_addrs
  website/docs/language/functions/templatefile.mdx
Labels: documentation, 1.3-backport

#32560 Fix the spelling of network within the setproducts function documentation.
  website/docs/language/functions/setproduct.mdx
Labels: documentation, 1.3-backport

#32566 Remove references to old linux signing key
  website/docs/cli/install/apt.mdx
Labels: documentation

#32494 cliconfig: Allow forcing use of the plugin cache despite the lock file
  commands.go
  internal/command/cliconfig/cliconfig.go
  internal/command/meta.go
  internal/command/meta_providers.go
  internal/providercache/installer.go
  internal/providercache/installer_test.go
  website/docs/cli/config/config-file.mdx
Labels: enhancement, cli

#32116 Added Quiet value
  internal/builtin/provisioners/local-exec/resource_provisioner.go
Labels: enhancement

#31699 [fixes 31700] Add mTLS support for http backend by way of client cert & key, as well as enterprise cacert.
  go.mod
  go.sum
  internal/backend/remote-state/http/backend.go
  internal/backend/remote-state/http/mock_server_test.go
  internal/backend/remote-state/http/server_test.go
  internal/backend/remote-state/http/testdata/certs/ca.cert.pem
  internal/backend/remote-state/http/testdata/certs/ca.key
  internal/backend/remote-state/http/testdata/certs/client.crt
  internal/backend/remote-state/http/testdata/certs/client.csr
  internal/backend/remote-state/http/testdata/certs/client.key
  internal/backend/remote-state/http/testdata/certs/server.crt
  internal/backend/remote-state/http/testdata/certs/server.csr
  internal/backend/remote-state/http/testdata/certs/server.key
  internal/backend/remote-state/http/testdata/gencerts.sh
  internal/command/apply_test.go
Labels: enhancement, backend/http

#32454 Reverse the order of conversion/defaults, and update HCL with more flexible defaults package
  go.mod
  go.sum
  internal/terraform/eval_variable.go
  internal/terraform/eval_variable_test.go
Labels: 1.3-backport

#32609 go get -u github.com/mitchellh/cli
  go.mod
  go.sum
Labels: dependencies
