Repository hashicorp/terraform, pull requests merged in 2023-05, with the labels that each got.

#33129 Link to plugin-framework tutorial
  website/docs/language/providers/index.mdx
Labels: documentation

#33149 Fix small typo in tf plan error
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
Labels: enhancement

#31920 update setsubtract examples to include toset notation
  website/docs/language/functions/setsubtract.mdx
Labels: documentation, tw-reviewed

#31977 Fix regex pattern for more alternatives
  website/docs/language/functions/regex.mdx
Labels: documentation, tw-reviewed

#33119 Change separating to grouping
  website/docs/language/syntax/style.mdx
Labels: documentation

#31992 [docs] Add warning about prefix loss when migrating
  website/docs/cli/cloud/migrating.mdx
Labels: documentation, tw-reviewed, cloud

#32058 tiny update to Resource Addressing: "value4"
  website/docs/cli/state/resource-addressing.mdx
Labels: documentation, tw-reviewed

#32073 Fixing s3.mdx on Delegating Access
  website/docs/language/settings/backends/s3.mdx
Labels: documentation, tw-reviewed

#33159 docs: Update command to match /cli/commands/taint -replace cmd
  website/docs/cli/state/taint.mdx
Labels: documentation, 1.4-backport

#33172 Update fmt.mdx to include missing period / full stop
  website/docs/cli/commands/fmt.mdx
Labels: documentation, 1.4-backport

#33180 website: Clarify what the "any" type constraint placeholder is for
  website/docs/language/expressions/type-constraints.mdx
Labels: enhancement, documentation

#32648 Update providers.mdx
  website/docs/language/modules/develop/providers.mdx
Labels: documentation

#32518 docs: provisioners: fix formatting on a note
  website/docs/language/resources/provisioners/syntax.mdx
Labels: documentation

#32539 DOC: Update supported options of command graph -type=...
  website/docs/cli/commands/graph.mdx
Labels: documentation

#33213 genconfig: do not generate null NestingSingle blocks
  internal/genconfig/generate_config.go
  internal/genconfig/generate_config_test.go
Labels: 1.5-backport

#33221 Fix an error message for import block with moved block
  internal/configs/module.go
Labels: 1.5-backport

#33238 plannable import: correct plumbing when using a plan output file
  internal/plans/planfile/tfplan.go
  internal/plans/planfile/tfplan_test.go
Labels: 1.5-backport

#33224 udpate go-cty
  go.mod
  go.sum
Labels: 1.5-backport

#33232 plannable import: safer config generation and schema filters
  internal/command/testdata/plan-import-config-gen/generated.tf.expected
  internal/configs/configschema/filter.go
  internal/configs/configschema/filter_test.go
  internal/genconfig/generate_config_write.go
  internal/terraform/context_plan2_test.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_plan_instance.go
Labels: 1.5-backport

#33235 Remove destroy-plan locals only referenced by root outputs
  internal/terraform/context_plan2_test.go
  internal/terraform/graph_builder_apply.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/node_output.go
  internal/terraform/transform_output.go
Labels: 1.5-backport

#33234 Refined Unknown Values, allowing some operations with unknown values to produce known results
  docs/plugin-protocol/object-wire-format.md
  go.mod
  go.sum
  internal/builtin/providers/terraform/resource_data.go
  internal/builtin/providers/terraform/resource_data_test.go
  internal/command/views/json/diagnostic.go
  internal/lang/funcs/cidr.go
  internal/lang/funcs/collection.go
  internal/lang/funcs/collection_test.go
  internal/lang/funcs/crypto.go
  internal/lang/funcs/datetime.go
  internal/lang/funcs/datetime_test.go
  internal/lang/funcs/encoding.go
  internal/lang/funcs/encoding_test.go
  internal/lang/funcs/filesystem.go
  internal/lang/funcs/number.go
  internal/lang/funcs/refinements.go
  internal/lang/funcs/string.go
  internal/lang/funcs/string_test.go
  internal/plans/objchange/compatible.go
  internal/plans/objchange/compatible_test.go
  internal/plans/objchange/objchange.go
  internal/plans/objchange/plan_valid.go
  internal/plans/objchange/plan_valid_test.go
Labels: enhancement, config

#33164 build: Generate copyright headers automatically
  copyright_headers.go
  go.mod
  go.sum
  internal/configs/configload/loader_snapshot.go
Labels: enhancement, build

#33286 remove deprecated set-output call in gha
  .github/actions/go-version/action.yml
Labels: enhancement, build, 1.4-backport, 1.5-backport

#33284 Build with Go 1.20.4
  .go-version
Labels: enhancement, build

#33294 go.mod: go get github.com/hashicorp/hcl/v2@v2.17.0
  go.mod
  go.sum
Labels: enhancement, config

#33278 plannable import: allow writing generated config when using the cloud integration
  go.mod
  go.sum
  internal/backend/local/backend_plan.go
  internal/backend/remote/backend_plan.go
  internal/backend/remote/backend_plan_test.go
  internal/cloud/backend_plan.go
  internal/cloud/backend_plan_test.go
  internal/cloud/testdata/plan-import-config-gen-exists/generated.tf
  internal/cloud/testdata/plan-import-config-gen-exists/main.tf
  internal/cloud/testdata/plan-import-config-gen-validation-error/generated.tf.expected
  internal/cloud/testdata/plan-import-config-gen-validation-error/main.tf
  internal/cloud/testdata/plan-import-config-gen-validation-error/plan-redacted.json
  internal/cloud/testdata/plan-import-config-gen-validation-error/plan.log
  internal/cloud/testdata/plan-import-config-gen/generated.tf.expected
  internal/cloud/testdata/plan-import-config-gen/main.tf
  internal/cloud/testdata/plan-import-config-gen/plan-redacted.json
  internal/cloud/testdata/plan-import-config-gen/plan.log
  internal/cloud/tfe_client_mock.go
  internal/genconfig/generate_config_write.go
Labels: 1.5-backport

#33293 terraform: expanded resources cannot genconfig
  internal/terraform/context_plan2_test.go
  internal/terraform/transform_config.go
Labels: 1.5-backport

#33279 command: help text for generate-config-out
  internal/command/plan.go
Labels: documentation, 1.5-backport

#33282 cloud: assert import block compatibility
  internal/cloud/backend_plan.go
  internal/command/init.go
Labels: 1.5-backport
