Repository hashicorp/terraform, pull requests merged in 2023-07, with the labels that each got.

#33475 Plan renderer: Support users indexing integer paths with stringified numbers
  internal/command/jsonformat/differ/differ_test.go
  internal/command/jsonformat/structured/attribute_path/matcher.go
Labels: 1.5-backport

#33484 go.mod: go get google.golang.org/grpc@v1.53.0
  go.mod
  go.sum
Labels: dependencies, security, 1.5-backport

#33462 always evaluate module outputs during destroy
  internal/terraform/context_apply_test.go
  internal/terraform/node_output.go
  internal/terraform/testdata/apply-destroy-provisider-refs/main.tf
  internal/terraform/testdata/apply-destroy-provisider-refs/mod/main.tf
Labels: 1.5-backport

#33448 fix typo in terraform/internal/command /init.go
  internal/command/init.go
Labels: documentation, 1.5-backport

#31995 [docs] Add example for using cloud-config in place of file provisioners
  website/docs/language/resources/provisioners/syntax.mdx
Labels: documentation, tw-reviewed, 1.5-backport

#33433 Remove PATH from GetCommand helpText
  internal/command/get.go
  website/docs/cli/commands/get.mdx
Labels: enhancement, documentation, 1.5-backport

#32074 docs: update splat expressions in directives
  website/docs/language/expressions/strings.mdx
Labels: documentation, tw-reviewed, 1.5-backport

#33432 Relocate localterraform.com aliasing to backend configurators
  internal/backend/backend.go
  internal/backend/local/backend.go
  internal/backend/remote/backend.go
  internal/backend/remote/backend_test.go
  internal/cloud/backend.go
  internal/cloud/backend_test.go
  internal/command/meta_backend.go
Labels: 1.5-backport

#32279 docs: create_before_destroy meta-attribute propagation
  website/docs/language/meta-arguments/lifecycle.mdx
Labels: documentation, tw-reviewed, 1.5-backport

#33578 Fix crash when nested data blocks are mixed with the import command
  internal/terraform/context_import_test.go
  internal/terraform/testdata/issue-33572/main.tf
  internal/terraform/transform_check.go
Labels: 1.5-backport

#33592 update go-getter to v1.7.2
  go.mod
  go.sum
Labels: enhancement

#33604 Update tostring.mdx for null value conversion
  website/docs/language/functions/tostring.mdx
Labels: documentation, 1.5-backport
