Repository hashicorp/terraform, pull requests merged in 2023-02, with the labels that each got.

#32451 Fix for no json output of state locking actions for --json flag
  internal/command/apply.go
  internal/command/console.go
  internal/command/graph.go
  internal/command/import.go
  internal/command/meta_backend.go
  internal/command/meta_backend_migrate.go
  internal/command/plan.go
  internal/command/providers_schema.go
  internal/command/refresh.go
  internal/command/state_show.go
  internal/command/views/state_locker.go
Labels: bug

#32557 Add a GCS backend specific env var for impersonation
  internal/backend/remote-state/gcs/backend.go
  website/docs/language/settings/backends/gcs.mdx
Labels: enhancement, backend/gcs

#32647 Begin cloud remote state with serial > 0
  internal/cloud/state.go
  internal/cloud/state_test.go
Labels: 1.4-backport

#32659 Use the latest equivalence testing version when executing equivalence tests
  .github/workflows/equivalence-test.yml
Labels: 1.4-backport

#32649 structured run output: impose canonical ordering on jsonstate and jsonplan packages
  internal/addrs/resource.go
  internal/command/jsonformat/diff.go
  internal/command/jsonformat/state.go
  internal/command/jsonplan/plan.go
  internal/command/jsonstate/state.go
  internal/command/testdata/show-json/provider-aliasing-conflict/output.json
  internal/command/testdata/show-json/provider-aliasing-default/output.json
  internal/command/testdata/show-json/provider-aliasing/output.json
Labels: 1.4-backport

#32663 Fix panic when planning orphaned deposed instances
  internal/terraform/node_resource_plan_orphan.go
  internal/terraform/node_resource_plan_orphan_test.go
Labels: 1.3-backport, 1.4-backport

#32664 Do not add orphan nodes for deposed instances
  internal/terraform/transform_orphan_count.go
  internal/terraform/transform_orphan_count_test.go
  internal/terraform/transform_orphan_resource.go
Labels: 1.3-backport, 1.4-backport

#32618 sort modules.json for stable order
  internal/modsdir/manifest.go
Labels: enhancement, 1.4-backport

#32487 Introduce `metadata functions` command
  commands.go
  internal/command/jsonfunction/function.go
  internal/command/jsonfunction/function_test.go
  internal/command/jsonfunction/parameter.go
  internal/command/jsonfunction/parameter_test.go
  internal/command/jsonfunction/return_type.go
  internal/command/metadata_command.go
  internal/command/metadata_functions.go
  internal/command/metadata_functions_test.go
  website/docs/cli/commands/index.mdx
Labels: 1.4-backport

#32679 initial terraform_data docs
  website/data/language-nav-data.json
  website/docs/language/meta-arguments/lifecycle.mdx
  website/docs/language/resources/provisioners/local-exec.mdx
  website/docs/language/resources/provisioners/null_resource.mdx
  website/docs/language/resources/terraform-data.mdx
  website/layouts/language.erb
Labels: documentation, 1.4-backport

#32492 docs: Explicitly mention Computed-only attribute behavior for Proposed New State
  docs/resource-instance-change-lifecycle.md
Labels: documentation

#32680 backend/local: Periodically persist intermediate state snapshots
  internal/backend/local/backend_apply.go
  internal/backend/local/hook_state.go
  internal/backend/local/hook_state_test.go
  internal/terraform/context.go
  internal/terraform/context_apply_test.go
  internal/terraform/hook.go
  internal/terraform/hook_mock.go
  internal/terraform/hook_stop.go
  internal/terraform/hook_test.go
  internal/terraform/testdata/apply-stop/apply-stop.tf
Labels: enhancement, backend/local

#32678 Update go-getter version
  go.mod
  go.sum
Labels: bug, 1.4-backport

#32683 allow terraform_data to import
  internal/builtin/providers/terraform/provider.go
  internal/builtin/providers/terraform/resource_data.go
Labels: 1.4-backport

#32688 build: Use Go 1.20.0
  .go-version
  go.mod
  go.sum
Labels: enhancement, build

#32710 Replace HTML entities in function descriptions
  internal/lang/funcs/descriptions.go
Labels: bug, 1.4-backport

#32701 Add website docs for `metadata functions -json` command
  website/data/internals-nav-data.json
  website/docs/internals/functions-meta.mdx
Labels: documentation, 1.4-backport

#32696 Handle provisioner log types when rendering structured logs
  internal/cloud/backend_apply_test.go
  internal/cloud/testdata/apply-json-with-provisioner-error/apply.log
  internal/cloud/testdata/apply-json-with-provisioner-error/main.tf
  internal/cloud/testdata/apply-json-with-provisioner-error/plan-redacted.json
  internal/cloud/testdata/apply-json-with-provisioner-error/plan.log
  internal/cloud/testdata/apply-json-with-provisioner/apply.log
  internal/cloud/testdata/apply-json-with-provisioner/main.tf
  internal/cloud/testdata/apply-json-with-provisioner/plan-redacted.json
  internal/cloud/testdata/apply-json-with-provisioner/plan.log
  internal/command/jsonformat/renderer.go
Labels: 1.4-backport

#32722 cliconfig: more err detail when provider_installation has invalid provider source
  internal/command/cliconfig/provider_installation.go
Labels: 1.4-backport

#32705 Remove docs bundle from build workflow
  .github/workflows/build.yml
Labels: 1.4-backport

#32666 Fix SRO authorization bug when token is fetched from cloud config
  internal/cloud/backend.go
  internal/cloud/backend_plan.go
Labels: 1.4-backport

#32695 keep errors friendly when init encounters syntax problems
  internal/command/init.go
  internal/command/init_test.go
  internal/command/testdata/init-syntax-invalid-backend-invalid/main.tf
  internal/command/testdata/init-syntax-invalid-no-backend/main.tf
  internal/command/testdata/init-syntax-invalid-with-backend/main.tf
Labels: 1.4-backport

#32708 Bug Fix where CLI exits if run is not confirmable.
  internal/cloud/backend_taskStages.go
  internal/cloud/backend_taskStages_test.go
Labels: 1.4-backport

#32726 cliconfig: Allow breaking the dependency lock file using the environment
  internal/command/cliconfig/cliconfig.go
  internal/command/cliconfig/cliconfig_test.go
Labels: enhancement, cli, 1.4-backport

#32742 bugfix: terraform providers mirror command should honor terraform lock file
  internal/command/e2etest/providers_mirror_test.go
  internal/command/e2etest/testdata/terraform-providers-mirror-with-lock-file/.terraform.lock.hcl
  internal/command/e2etest/testdata/terraform-providers-mirror-with-lock-file/terraform-providers-mirror.tf
  internal/command/providers_mirror.go
Labels: 1.4-backport

#32697 Adding provider constraint best practice statement
  website/docs/language/providers/index.mdx
Labels: documentation
