Repository hashicorp/terraform, pull requests merged in 2023-09, with the labels that each got.

#33781 Handle null outputs in Terraform test files
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/null-outputs/main.tf
  internal/command/testdata/test/null-outputs/main.tftest.hcl
  internal/terraform/evaluate.go
Labels: 1.6-backport

#33132 clarify types and link to Type Constraints pagedit types
  website/docs/language/expressions/types.mdx
Labels: documentation, tw-reviewed, 1.5-backport

#33815 statefile: Ignore unknown check results on decode
  internal/states/statefile/version4.go
Labels: 1.5-backport, 1.6-backport

#33805 backend/s3: add allowed/forbidden account ID parameters
  go.mod
  go.sum
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_complete_test.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/diags.go
  website/docs/language/settings/backends/s3.mdx
Labels: enhancement, backend/s3, 1.6-backport

#33821 re-clarify types documentation
  website/docs/language/expressions/types.mdx
Labels: 1.5-backport, 1.6-backport

#33820 cloud: state snapshots always enabled despite missing header x-terraform-snapshot-interval
  internal/cloud/state.go
  internal/cloud/state_test.go
Labels: 1.5-backport, 1.6-backport

#33792 Update index.mdx
  website/docs/language/checks/index.mdx
Labels: documentation

#33822 backend/s3: Adds tests for endpoint overrides and adds validation for parameters
  go.mod
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/validate.go
  internal/backend/remote-state/s3/validate_test.go
  website/docs/language/settings/backends/s3.mdx
Labels: enhancement, backend/s3, tests, 1.6-backport

#33825 backend/s3: Adds logging for `aws-sdk-go-base`
  internal/backend/remote-state/s3/backend.go
Labels: enhancement, backend/s3, 1.6-backport

#33839 backend/s3: Use Transfer Managers to speed up transfers of large state files
  go.mod
  go.sum
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/client_test.go
Labels: enhancement, backend/s3, 1.6-backport

#33842 Adds logging for `aws-sdk-go-base`
  internal/backend/remote-state/s3/backend.go
Labels: enhancement, backend/s3

#33840 Refactor file and run block feedback frequency
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/views/json/test.go
  internal/command/views/test.go
  internal/command/views/test_test.go
  internal/moduletest/progress.go
  internal/moduletest/progress_string.go
Labels: 1.6-backport

#33809 Make the test command fail if resources could not be cleaned up
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/destroy_fail/main.tf
  internal/command/testdata/test/destroy_fail/main.tftest.hcl
  internal/command/testing/test_provider.go
Labels: 1.6-backport

#33841 backend/s3: Adds tests for endpoint overrides and adds validation for parameters
  go.mod
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/validate.go
  internal/backend/remote-state/s3/validate_test.go
  website/docs/language/settings/backends/s3.mdx
Labels: enhancement, backend/s3

#33850 backend/s3: Restore HTTP request/response logging
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_state.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/logging.go
Labels: backend/s3, 1.6-backport

#33851 backend/s3: Improves bare error messages from API responses
  internal/backend/remote-state/s3/backend_state.go
  internal/backend/remote-state/s3/client.go
Labels: backend/s3, 1.6-backport

#33846 Reserve state and plan keywords in test files
  internal/addrs/parse_ref.go
Labels: 1.6-backport

#33836 Explicitely disallow duplicate run block names in test files
  internal/command/test_test.go
  internal/command/testdata/test/pass_with_variables/main.tftest.hcl
  internal/command/testdata/test/plan_then_apply/main.tftest.hcl
  internal/configs/parser_config_dir_test.go
  internal/configs/test_file.go
  internal/configs/testdata/invalid-modules/tests-duplicate-run-blocks/main.tf
  internal/configs/testdata/invalid-modules/tests-duplicate-run-blocks/main.tftest.hcl
Labels: 1.6-backport

#33830 build with Go 1.21.1
  .go-version
  go.mod
Labels: 1.6-backport

#29227 website: DynamoDB now supports fine-grain IAM policies
  website/docs/language/settings/backends/s3.mdx
Labels: documentation, backend/s3, tw-reviewed, 1.6-backport

#33871 Small rewrite of Contrib to better reflect current practices.
  .github/CONTRIBUTING.md
Labels: documentation

#33869 backend/s3: prevent keys containing double slashes
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/validate.go
  internal/backend/remote-state/s3/validate_test.go
Labels: enhancement, backend/s3, 1.6-backport

#29610 Improve error message when S3 state checksums don't line up
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/client_test.go
Labels: enhancement, provider/aws, backend/s3, 1.6-backport

#33881 backend/s3: Handles case when bucket is requested from wrong region
  internal/backend/remote-state/s3/backend_state.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/client_test.go
Labels: enhancement, backend/s3, 1.6-backport

#33872 backend/s3: Adds `singleNestedAttribute` to internal schema
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_complete_test.go
  internal/backend/remote-state/s3/backend_test.go
Labels: backend/s3, 1.6-backport

#33875 Add cloud-run documentation for testing framework
  website/docs/cli/commands/test.mdx
Labels: 1.6-backport

#33867 Apply defaults when processing variables for assertions
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/default_optional_values/main.tf
  internal/command/testdata/test/default_optional_values/main.tftest.hcl
Labels: 1.6-backport

#33868 Add warning when testing and combining expect_failures with apply operations
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/expected_failures_during_planning/check.tftest.hcl
  internal/command/testdata/test/expected_failures_during_planning/input.tftest.hcl
  internal/command/testdata/test/expected_failures_during_planning/main.tf
  internal/command/testdata/test/expected_failures_during_planning/output.tftest.hcl
  internal/command/testdata/test/expected_failures_during_planning/resource.tftest.hcl
  internal/moduletest/run.go
Labels: 1.6-backport

#33710 Implement TFC integration for private module registry test runs
  go.mod
  go.sum
  internal/cloud/backend.go
  internal/cloud/cloud_variables.go
  internal/cloud/test.go
  internal/cloud/test_test.go
  internal/cloud/testdata/test-cancel/main.tf
  internal/cloud/testdata/test-cancel/main.tftest.hcl
  internal/cloud/testdata/test-cancel/test.log
  internal/cloud/testdata/test-force-cancel/main.tf
  internal/cloud/testdata/test-force-cancel/main.tftest.hcl
  internal/cloud/testdata/test-force-cancel/test.log
  internal/cloud/testdata/test-verbose/main.tf
  internal/cloud/testdata/test-verbose/main.tftest.hcl
  internal/cloud/testdata/test-verbose/test.log
  internal/cloud/testdata/test/main.tf
  internal/cloud/testdata/test/main.tftest.hcl
  internal/cloud/testdata/test/test.log
  internal/cloud/tfe_client_mock.go
  internal/command/command_test.go
  internal/command/jsonformat/renderer.go
  internal/command/test.go
  internal/command/views/cloud.go
  internal/command/views/json/message_types.go
  internal/command/views/json/test.go
  internal/command/views/test.go
Labels: 1.6-backport

#33861 Add additional validation around unknown and null values in test variables
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/nested_unknown_values/main.tf
  internal/command/testdata/test/nested_unknown_values/main.tftest.hcl
  internal/command/testdata/test/null_value_in_assert/main.tf
  internal/command/testdata/test/null_value_in_assert/main.tftest.hcl
  internal/command/testdata/test/null_value_in_vars/fail.tftest.hcl
  internal/command/testdata/test/null_value_in_vars/main.tf
  internal/command/testdata/test/null_value_in_vars/pass.tftest.hcl
  internal/command/testdata/test/unknown_value_in_assert/main.tf
  internal/command/testdata/test/unknown_value_in_assert/main.tftest.hcl
  internal/command/testdata/test/unknown_value_in_vars/main.tf
  internal/command/testdata/test/unknown_value_in_vars/main.tftest.hcl
  internal/terraform/evaluate.go
Labels: 1.6-backport

#33892 Fix typo in login link from test command doc page
  website/docs/cli/commands/test.mdx
Labels: 1.6-backport

#33885 backend/s3: Add wrong bucket region handling to all of S3 client
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_state.go
  internal/backend/remote-state/s3/middleware.go
Labels: enhancement, 1.6-backport

#33897 import blocks are evaluated in the root module
  internal/terraform/eval_import.go
  internal/terraform/node_resource_abstract.go
  internal/terraform/node_resource_plan.go
  internal/terraform/testdata/import-id-variable/main.tf
  internal/terraform/testdata/import-id-variable/mod/main.tf
  internal/terraform/transform_reference.go
Labels: 1.6-backport

#33902 configschema: CoerceValue error for omitted attribute requirements
  internal/configs/configschema/coerce_value.go
  internal/configs/configschema/coerce_value_test.go
Labels: backend/s3, providers

#33901 backend/s3: set required or optional for single nested attributes
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_test.go
Labels: bug, backend/s3, 1.6-backport

#33912 Update requirements.mdx
  website/docs/language/providers/requirements.mdx
Labels: documentation

#33921 Fix mock provider ImportState data race
  internal/legacy/terraform/provider_mock.go
  internal/terraform/provider_mock.go
Labels: 1.6-backport

#33926 [Docs Fix] Add table for run block in testing docs and remove doubled notes
  website/docs/language/tests/index.mdx
Labels: 1.6-backport

#33899 backend/s3: Adds `source_identity` to `assume_role` block
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_complete_test.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/validate.go
  website/docs/language/settings/backends/s3.mdx
Labels: backend/s3, 1.6-backport

#33929 Fix panic when tests on TFC exit early
  internal/cloud/test.go
  internal/cloud/tfe_client_mock.go
Labels: 1.6-backport

#33930 Refactor cloud test run cancellation logic to always intercept signals
  internal/cloud/test.go
  internal/cloud/test_test.go
  internal/cloud/tfe_client_mock.go
Labels: 1.6-backport

#33940 backend/s3: Supports S3 buckets with Object Lock
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/client_test.go
Labels: bug, backend/s3, 1.6-backport

#33950 Test files should be marked as skipped if all their run blocks were skipped
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/with_interrupt_and_additional_file/main.tf
  internal/command/testdata/test/with_interrupt_and_additional_file/main.tftest.hcl
  internal/command/testdata/test/with_interrupt_and_additional_file/skip_me.tftest.hcl
Labels: 1.6-backport

#33951 Implement double cancel instead of force cancel for test cloud runs
  internal/cloud/test.go
  internal/cloud/test_test.go
  internal/cloud/tfe_client_mock.go
Labels: 1.6-backport

#33956 Increase timeout length after fatal interrupts for test cloud runs
  internal/command/test.go
Labels: 1.6-backport
