Repository hashicorp/terraform, pull requests merged in 2023-03, with the labels that each got.

#32766 Update documentation for compact function
  website/docs/language/functions/compact.mdx
Labels: documentation

#32782 10x faster cloud tests
  internal/cloud/backend_taskStage_policyEvaluation_test.go
  internal/cloud/backend_taskStage_taskResults_test.go
  internal/cloud/backend_test.go
  internal/cloud/testing.go
Labels: cloud, 1.4-backport

#32765 website: Document TF_PLUGIN_CACHE_MAY_BREAK_DEPENDENCY_LOCK_FILE env var
  website/docs/cli/config/config-file.mdx
  website/docs/cli/config/environment-variables.mdx
Labels: documentation, 1.4-backport

#32763 Update upgrade guide 1.4
  website/docs/language/upgrade-guides/index.mdx
Labels: 1.4-backport

#32796 Fixes overriding modules which have depends_on attribute set
  internal/configs/module_merge.go
  internal/configs/module_merge_test.go
  internal/configs/testdata/valid-modules/override-module/primary.tf
Labels: bug, 1.4-backport

#32775 Update HCL to handle type mismatches when applying defaults
  go.mod
  go.sum
  internal/lang/funcs/collection_test.go
  internal/terraform/eval_variable_test.go
Labels: 1.4-backport

#32801 1.4 upgrade change
  website/docs/language/upgrade-guides/index.mdx
Labels: 1.4-backport

#32820 Fix no-op outputs causing the plan renderer to skip the 'no changes' message
  internal/command/jsonformat/plan.go
  internal/command/jsonformat/plan_test.go
Labels: 1.4-backport

#32836 Add TFC to state doc
  website/docs/language/state/index.mdx
Labels: 1.4-backport

#32840 Prevent nil Colorize options when rendering state outputs
  internal/command/jsonformat/renderer.go
  internal/command/show_test.go
Labels: 1.4-backport

#32846 emit a warning msg if invalid CLI configuration file location
  internal/command/cliconfig/cliconfig.go
  internal/command/cliconfig/cliconfig_test.go
  internal/command/e2etest/init_test.go
Labels: 1.4-backport

#32855 Update index.mdx New PR for pinning providers
  website/docs/language/providers/index.mdx
Labels: documentation, 1.4-backport

#32771 add docs meta descriptions
  website/data/language-nav-data.json
  website/docs/cli/cloud/index.mdx
  website/docs/cli/cloud/migrating.mdx
  website/docs/cli/state/recover.mdx
  website/docs/configuration/expressions.mdx
  website/docs/configuration/index.mdx
  website/docs/configuration/modules.mdx
  website/docs/configuration/resources.mdx
  website/docs/language/modules/develop/providers.mdx
  website/docs/language/modules/develop/structure.mdx
  website/docs/language/modules/testing-experiment.mdx
  website/docs/language/settings/backends/configuration.mdx
Labels: documentation

#32854 core: Fix test flake in TestContext2Apply_stop
  internal/terraform/context_apply_test.go
Labels: bug, core

#32877 Update settings.mdx
  website/docs/cli/cloud/settings.mdx
Labels: documentation, 1.4-backport

#32883 trivial grammar fix in BUGPROCESS.md
  BUGPROCESS.md
Labels: documentation, tw-reviewed, 1.4-backport

#32882 Correct docs on Configuration Directory
  website/docs/cli/commands/init.mdx
Labels: documentation, 1.4-backport

#32884 Spelling update
  website/docs/cli/commands/plan.mdx
Labels: documentation, 1.4-backport

#32891 Store all sensitive marks for non-root module outputs in state
  internal/terraform/context_apply2_test.go
  internal/terraform/node_output.go
Labels: 1.4-backport

#32889 Feature/doc change
  website/docs/language/functions/join.mdx
Labels: documentation, 1.4-backport

#32916 v1.4: website: Minor fixes to Provisioners Without a Resource page
  website/docs/language/resources/provisioners/null_resource.mdx
Labels: documentation

#32797 Releng/migrate common release tooling
  .github/scripts/e2e_test_linux_darwin.sh
  .github/scripts/get_product_version.sh
  .github/workflows/build-terraform-oss.yml
  .github/workflows/build.yml
  .release/ci.hcl
  .release/security-scan.hcl
  version/VERSION
Labels: 1.4-backport

#32900 External changes report can fail with schema migrations and `-target`
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
Labels: 1.4-backport

#32876 Remove planned data source objects from state on error
  internal/terraform/context_plan.go
  internal/terraform/context_plan2_test.go
  internal/terraform/testdata/data-source-read-with-plan-error/main.tf
Labels: 1.4-backport
