Repository hashicorp/terraform, pull requests merged in 2023-04, with the labels that each got.

#32970 update apt install instructions
  website/docs/cli/install/apt.mdx
Labels: 1.4-backport

#32967 Fix templatefile argument type
  website/docs/language/functions/templatefile.mdx
Labels: documentation

#32526 Add support for PG_CONN_STR ENV var
  internal/backend/remote-state/pg/backend.go
  internal/backend/remote-state/pg/backend_test.go
  website/docs/language/settings/backends/pg.mdx
Labels: enhancement, backend/pg

#32988 the destroy plan should use correct type
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/provider_mock.go
Labels: 1.4-backport

#32990 ci: Smoke test docker builds
  .github/scripts/verify_docker
  .github/workflows/build.yml
Labels: 1.4-backport

#33000 metadata_host param for AzureRM backend documentation
  website/docs/language/settings/backends/azurerm.mdx
Labels: documentation, provider/azurerm, 1.4-backport

#33002 Backport of metadata_host param for AzureRM backend documentation into v1.4
  website/docs/language/settings/backends/azurerm.mdx
Labels: documentation, backend/azure

#33029 Fix rendering unknown values in map and null string primitives
  internal/command/jsonformat/computed/renderers/primitive.go
  internal/command/jsonformat/computed/renderers/renderer_test.go
  internal/command/jsonformat/computed/renderers/string.go
  internal/command/jsonformat/differ/change_test.go
  internal/command/jsonformat/differ/map.go
Labels: 1.4-backport

#33045 Improve environment variable support for the pg backend
  internal/backend/remote-state/pg/backend.go
  internal/backend/remote-state/pg/backend_test.go
  website/docs/language/settings/backends/pg.mdx
Labels: enhancement, backend/pg

#33054 Refactor of differ to make code reuse easier
  internal/command/jsonformat/computed/renderers/primitive.go
  internal/command/jsonformat/diff.go
  internal/command/jsonformat/differ/attribute.go
  internal/command/jsonformat/differ/block.go
  internal/command/jsonformat/differ/differ.go
  internal/command/jsonformat/differ/differ_test.go
  internal/command/jsonformat/differ/list.go
  internal/command/jsonformat/differ/map.go
  internal/command/jsonformat/differ/object.go
  internal/command/jsonformat/differ/output.go
  internal/command/jsonformat/differ/primitive.go
  internal/command/jsonformat/differ/sensitive.go
  internal/command/jsonformat/differ/set.go
  internal/command/jsonformat/differ/tuple.go
  internal/command/jsonformat/differ/unknown.go
  internal/command/jsonformat/jsondiff/diff.go
  internal/command/jsonformat/plan_test.go
  internal/command/jsonformat/renderer.go
  internal/command/jsonformat/state.go
  internal/command/jsonformat/structured/attribute_path/matcher.go
  internal/command/jsonformat/structured/attribute_path/matcher_test.go
  internal/command/jsonformat/structured/change.go
  internal/command/jsonformat/structured/doc.go
  internal/command/jsonformat/structured/map.go
  internal/command/jsonformat/structured/sensitive.go
  internal/command/jsonformat/structured/slice.go
  internal/command/jsonformat/structured/unknown.go
Labels: 1.4-backport

#33064 Remove incorrect space in doc
  website/docs/language/files/index.mdx
Labels: documentation, 1.4-backport

#33059 Include sensitive metadata from the schema when building the json state output
  internal/command/jsonstate/state.go
  internal/command/jsonstate/state_test.go
  internal/command/testdata/show-json/conditions/output-refresh-only.json
Labels: 1.4-backport

#33065 Make the unknown attribute renderer consider the force replacement metadata
  internal/command/jsonformat/computed/renderers/renderer_test.go
  internal/command/jsonformat/computed/renderers/unknown.go
Labels: 1.4-backport

#33092 Update README.md
  docs/README.md
Labels: documentation, 1.4-backport

#33101 Adding additional entry necessary to generate docs.
  website/data/language-nav-data.json
Labels: documentation, 1.4-backport
