Repository hashicorp/terraform, pull requests merged in 2023-06, with the labels that each got.

#33300 chore(docs): delete check-legacy-links-format.yml
  .github/workflows/check-legacy-links-format.yml
Labels: documentation

#33301 Ensure nested data blocks execute last of all Terraform resources
  internal/terraform/graph_builder_apply.go
  internal/terraform/graph_builder_apply_test.go
  internal/terraform/node_check.go
  internal/terraform/testdata/apply-with-checks/main.tf
  internal/terraform/transform_check.go
  internal/terraform/transform_check_starter.go
Labels: 1.5-backport

#33311 views: fix wordwrap bug
  internal/command/views/operation.go
Labels: 1.5-backport

#33241 Add documentation page for checks and assertions
  website/data/language-nav-data.json
  website/docs/language/checks/index.mdx
  website/docs/language/expressions/custom-conditions.mdx
Labels: documentation, 1.5-backport

#33291 Update variables.mdx
  website/docs/language/values/variables.mdx
Labels: documentation, 1.5-backport

#33328 Adding links to the Checks tutorial and fixing headers.
  website/docs/language/checks/index.mdx
  website/docs/language/expressions/custom-conditions.mdx
Labels: documentation, 1.5-backport

#33266 website: plannable import docs
  website/data/language-nav-data.json
  website/docs/cli/commands/plan.mdx
  website/docs/cli/import/index.mdx
  website/docs/language/import/generating-configuration.mdx
  website/docs/language/import/index.mdx
  website/docs/language/state/import.mdx
Labels: documentation, 1.5-backport

#33341 Add missing preposition to sentence
  website/docs/language/modules/develop/composition.mdx
Labels: documentation, 1.5-backport

#33338 Update templatefile.mdx
  website/docs/language/functions/templatefile.mdx
Labels: documentation, 1.5-backport

#33208 backend/oss: Removes the deprecated warning for configuration variable assume_role
  internal/backend/remote-state/oss/backend.go
Labels: enhancement, backend/oss, 1.5-backport

#33360 Fix broken link in Checks documentation
  website/docs/language/checks/index.mdx
Labels: documentation, 1.5-backport

#33346 Update environment-variables.mdx
  website/docs/cli/config/environment-variables.mdx
Labels: documentation, 1.5-backport

#33364 go.mod: go get github.com/hashicorp/terraform-svchost@v0.1.1
  go.mod
  go.sum
Labels: 1.5-backport

#33274 docs/backends/cos: add necessary permission list for using the backend
  website/docs/language/settings/backends/cos.mdx
Labels: documentation, backend/cos

#33372 `terraform show -json`: Add Errored field to output for plan
  internal/command/jsonplan/plan.go
  internal/command/show_test.go
  internal/command/testdata/show-json/plan-error/main.tf
  internal/command/testdata/show-json/plan-error/output.json
  website/docs/internals/json-format.mdx
Labels: enhancement

#33413 Reinstate the accidentally deleted experimental testing page
  website/data/language-nav-data.json
  website/docs/language/modules/testing-experiment.mdx
Labels: 1.5-backport

#33416 plans/objchange: Support nested unknowns in our unrefinedValue shim
  internal/plans/objchange/plan_valid.go
  internal/plans/objchange/plan_valid_test.go
Labels: bug, config

#33434 configs: remove import block duplicate id check
  internal/command/testdata/validate-invalid/duplicate_import_ids/main.tf
  internal/command/testdata/validate-invalid/duplicate_import_ids/output.json
  internal/command/validate_test.go
  internal/configs/module.go
Labels: 1.5-backport

#33441 docs: dissociate CV from preconditions and postconditions
  website/docs/language/expressions/custom-conditions.mdx
Labels: cloud

#33108 Return debuggable CAS errors on consul state put
  internal/backend/remote-state/consul/client.go
Labels: enhancement, backend/consul, 1.5-backport

#33459 use multierror.Append instead of `append`
  internal/backend/remote-state/consul/client.go
Labels: backend/consul
