Repository hashicorp/terraform, pull requests merged in 2024-05, with the labels that each got.

#35110 Don't evaluate providers within overridden modules
  internal/terraform/context_apply_overrides_test.go
  internal/terraform/graph.go
Labels: 1.8-backport

#35112 added reference page for block
  website/data/language-nav-data.json
  website/docs/language/moved.mdx
Labels: 1.3-backport, 1.4-backport, 1.5-backport, 1.6-backport, 1.7-backport, 1.8-backport

#35090 core: prevent panics with null objects in nested attrs
  internal/plans/objchange/plan_valid.go
  internal/plans/objchange/plan_valid_test.go
Labels: 1.8-backport

#35093 Config syntax docs update
  website/docs/language/syntax/configuration.mdx
Labels: documentation, tw-reviewed, 1.8-backport

#35092 Wrong reference
  website/docs/language/resources/provisioners/syntax.mdx
Labels: documentation, tw-reviewed, 1.8-backport

#35144 backend/local: Allow experiments when loading config from snapshot
  internal/backend/local/backend_local.go
  internal/configs/configload/loader.go
  internal/configs/parser.go
Labels: bug, cli, backend/local

#35157 Reduce redundant walks when resolving module `depends_on`
  internal/dag/dag.go
  internal/terraform/transform_reference.go
Labels: bug, 1.8-backport

#35164 remove extra state.DeepCopy from updateStateHook
  internal/terraform/hook.go
  internal/terraform/update_state_hook.go
Labels: bug

#35163 Support moving from null_resource to terraform_data
  internal/builtin/providers/terraform/provider.go
  internal/builtin/providers/terraform/provider_test.go
  internal/builtin/providers/terraform/resource_data.go
  internal/builtin/providers/terraform/resource_data_test.go
Labels: enhancement

#35153 stackeval: Improve coverage of namedPromiseReporter impls
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/component_config.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/diagnostics_test.go
  internal/stacks/stackruntime/internal/stackeval/input_variable.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/output_value.go
  internal/stacks/stackruntime/internal/stackeval/provider.go
  internal/stacks/stackruntime/internal/stackeval/provider_config.go
  internal/stacks/stackruntime/internal/stackeval/provider_instance.go
  internal/stacks/stackruntime/internal/stackeval/provider_type.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/named_promises/child/named_promises_child.tfstack.hcl
  internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/named_promises/named_promises.tf
  internal/stacks/stackruntime/internal/stackeval/testdata/sourcebundle/planning/named_promises/named_promises.tfstack.hcl
Labels: stacks

#35176 Add `TF_STATE_PERSIST_INTERVAL` environment variable.
  internal/backend/backendrun/operation.go
  internal/backend/local/backend_apply.go
  internal/command/apply.go
  internal/command/command.go
  internal/command/meta.go
  internal/command/meta_test.go
  website/docs/cli/config/environment-variables.mdx
Labels: enhancement

#35180 funcs: Don't panic if templatefile path is sensitive
  internal/lang/funcs/filesystem.go
  internal/lang/funcs/filesystem_test.go
Labels: bug, config, functions

#35220 import: only filter id attribute at root level when generating config
  internal/configs/configschema/filter.go
  internal/terraform/context_plan_import_test.go
Labels: 1.8-backport

#35185 broken link in architecture.md #35184
  docs/architecture.md
Labels: documentation

#35165 update golang.org/x/net, addressing CVE-2023-45288
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.mod
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.mod
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
  internal/legacy/go.mod
  internal/legacy/go.sum
Labels: 1.8-backport

#35228 Fix inconsistent `moved` snippets in docs
  website/docs/language/moved.mdx
Labels: documentation, 1.8-backport

#35172 Remove invalid warning during cleanup phase
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/invalid-cleanup-warnings/main.tf
  internal/command/testdata/test/invalid-cleanup-warnings/main.tftest.hcl
Labels: bug, 1.8-backport

#35251 [Docs] Migrate "Phases of Terraform Adoption" from tutorials to docs
  website/data/intro-nav-data.json
  website/docs/intro/phases/adopt.mdx
  website/docs/intro/phases/collaborate.mdx
  website/docs/intro/phases/govern.mdx
  website/docs/intro/phases/index.mdx
  website/docs/intro/phases/scale.mdx
  website/docs/language/style.mdx
Labels: documentation, 1.8-backport

#35262 Don't attempt to import during a destroy operation
  internal/terraform/context_plan_import_test.go
  internal/terraform/node_resource_plan_instance.go
Labels: 1.9-backport
