Repository hashicorp/terraform, pull requests merged in 2024-12, with the labels that each got.

#36139 Docs: Added necessary permission for `use_lockfile` at s3 backend
  website/docs/language/backend/s3.mdx
Labels: 1.10-backport

#36143 Update tfdeploy.mdx
  website/docs/language/stacks/reference/tfdeploy.mdx
Labels: 1.10-backport

#36120 s3: fix S3 Object Lock header issue for lock file writes
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/client_test.go
Labels: bug, backend/s3, 1.10-backport

#36102 Remove a broken link
  internal/copy/copy_file.go
Labels: enhancement

#36153 1.10 upgrade guide: sidebar update and -reconfigure callout
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/index.mdx
Labels: documentation, 1.10-backport

#36180 Don't validate apply variables from auto files
  internal/backend/local/backend_apply.go
  internal/command/apply_test.go
  internal/command/testdata/apply-vars-auto/main.tf
  internal/command/testdata/apply-vars-auto/terraform-test.tfvars
  internal/command/testdata/apply-vars-auto/terraform.tfvars
Labels: 1.10-backport

#36190 Add LLM info request to the bug report form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: documentation

#36204 missing ephemeral variable docs
  website/docs/language/values/variables.mdx
Labels: 1.10-backport

#36212 encoding of changes should always return a value
  internal/plans/changes.go
  internal/plans/changes_test.go
Labels: 1.10-backport

#36202 Document the `tfstacks fmt` command
  website/docs/cli/commands/fmt.mdx
  website/docs/language/stacks/reference/tfstacks-cli.mdx
Labels: 1.10-backport

#36211 Update sample bucket names on s3.mdx
  website/docs/language/backend/s3.mdx
Labels: documentation, 1.10-backport
