Repository hashicorp/terraform, pull requests merged in 2024-04, with the labels that each got.

#34916 docs: Fix anchor link to code formatting in style guide
  website/docs/cli/commands/fmt.mdx
  website/docs/language/syntax/index.mdx
Labels: 1.6-backport, 1.7-backport, 1.8-backport

#34873 Interpolate environment variables when configuring dev_overrides
  internal/command/cliconfig/provider_installation.go
Labels: enhancement

#34932 Fix validation condition
  website/docs/language/style.mdx
Labels: documentation, 1.1-backport, 1.2-backport, 1.3-backport, 1.4-backport, 1.5-backport, 1.6-backport, 1.7-backport, 1.8-backport

#34900 Always add all marks to plan and apply values, then compare marks from the values
  internal/providers/testing/provider_mock.go
  internal/terraform/context_apply2_test.go
  internal/terraform/context_plan2_test.go
  internal/terraform/marks.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_plan_partialexp.go
Labels: 1.8-backport

#34851 go.mod: Update OpenTelemetry dependencies to v1.24.0
  go.mod
  go.sum
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
Labels: dependencies

#34895 docs: Update 'Sensitive Data in State' page to describe encryption features of gcs backend
  website/docs/language/state/sensitive-data.mdx
Labels: documentation, backend/gcs

#34950 Update docs to clarify cross-type moves
  website/docs/language/modules/develop/refactoring.mdx
Labels: documentation, 1.8-backport

#34959 plan renderer: ensure JSON strings are completely JSON
  internal/command/jsonformat/computed/renderers/renderer_test.go
  internal/command/jsonformat/computed/renderers/string.go
  internal/command/jsonformat/structured/change.go
Labels: 1.8-backport

#34896 doc: Add and Improve Security Notices for `filemd5`, `md5`, and `filesha1` functions
  website/docs/language/functions/filemd5.mdx
  website/docs/language/functions/filesha1.mdx
  website/docs/language/functions/md5.mdx
Labels: documentation, 1.8-backport

#34918 Add a note about TERRAFORM_CONFIG to help with migration old configs.
  website/docs/cli/config/environment-variables.mdx
Labels: documentation, 1.8-backport

#34985 Fix panics due to missing graph edges on empty modules or invalid refs
  internal/terraform/context_apply2_test.go
  internal/terraform/context_plan2_test.go
  internal/terraform/node_module_expand.go
  internal/terraform/transform_reference.go
Labels: 1.8-backport

#34986 Move target may be in a module which does not exist
  internal/refactoring/move_statement.go
  internal/refactoring/testdata/move-statement-implied/move-statement-implied.tf
  internal/terraform/context_plan2_test.go
Labels: 1.8-backport

#34957 docs: fix typo in spelling of 'flag'
  website/docs/language/style.mdx
Labels: documentation, 1.8-backport

#34958 docs: fix typo in spelling of 'Sentinel'
  website/docs/language/style.mdx
Labels: documentation, 1.8-backport

#34996 Fix crash when generating config for a resource with complex sensitive attributes
  internal/genconfig/generate_config.go
  internal/genconfig/generate_config_test.go
  internal/terraform/context_plan_import_test.go
Labels: 1.8-backport

#34989 backend/gcs: Stop using legacy helper/schema
  internal/backend/remote-state/gcs/backend.go
  internal/backend/remote-state/gcs/backend_state.go
  internal/backend/remote-state/gcs/backend_test.go
  internal/backend/remote-state/gcs/client.go
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
Labels: backend/gcs

#35048 terraform apply: restore marks after unknown validation
  internal/terraform/context_apply2_test.go
  internal/terraform/node_resource_abstract_instance.go
Labels: 1.8-backport

#35014 terraform test: Push evaluation of variables to as late as possible
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/env-vars-in-module/main.tf
  internal/command/testdata/test/env-vars-in-module/main.tftest.hcl
  internal/command/testdata/test/env-vars-in-module/mod/main.tf
  internal/command/testdata/test/env-vars/main.tf
  internal/command/testdata/test/env-vars/main.tftest.hcl
  internal/moduletest/config/config.go
  internal/moduletest/config/config_test.go
  internal/moduletest/hcl/context.go
  internal/moduletest/hcl/provider.go
  internal/moduletest/hcl/provider_test.go
  internal/moduletest/hcl/variable_cache.go
  internal/moduletest/hcl/variable_cache_test.go
Labels: 1.8-backport

#34977 legal: Include license in release zip, Docker image and linux packages
  .github/workflows/build-Dockerfile
  .github/workflows/build-terraform-cli.yml
Labels: 1.8-backport

#35030 terraform test: move override evaluation into expander
  internal/command/validate_test.go
  internal/instances/expander.go
  internal/instances/expander_test.go
  internal/instances/set.go
  internal/instances/set_test.go
  internal/moduletest/mocking/overrides.go
  internal/moduletest/mocking/overrides_test.go
  internal/refactoring/move_validate.go
  internal/refactoring/move_validate_test.go
  internal/terraform/context_apply.go
  internal/terraform/context_apply_overrides_test.go
  internal/terraform/context_plan.go
  internal/terraform/context_walk.go
  internal/terraform/evaluate_test.go
  internal/terraform/graph.go
  internal/terraform/graph_builder_apply.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/instance_expanders.go
  internal/terraform/node_check.go
  internal/terraform/node_local.go
  internal/terraform/node_module_expand.go
  internal/terraform/node_module_expand_test.go
  internal/terraform/node_module_variable.go
  internal/terraform/node_output.go
  internal/terraform/node_resource_apply.go
  internal/terraform/node_resource_apply_test.go
  internal/terraform/node_resource_plan.go
  internal/terraform/node_resource_plan_orphan.go
  internal/terraform/node_resource_plan_orphan_test.go
  internal/terraform/node_variable_validation.go
  internal/terraform/transform_output.go
Labels: 1.8-backport

#35041 go get github.com/hashicorp/go-getter && go mod tidy
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.sum
  internal/legacy/go.sum
Labels: 1.8-backport

#35066 Optimize, then disable ResourceGraph during normal plans
  internal/terraform/context_walk.go
  internal/terraform/graph.go
Labels: 1.8-backport

#35034 Update index.mdx
  website/docs/cli/plugins/index.mdx
Labels: documentation, tw-reviewed, 1.8-backport

#35035 backendbase: Preserve unset arguments as null when not set by env
  internal/backend/backendbase/base.go
  internal/backend/backendbase/sdklike.go
  internal/backend/backendbase/sdklike_test.go
  internal/backend/remote-state/gcs/backend.go
  internal/backend/remote-state/gcs/backend_test.go
Labels: enhancement, backend/gcs, backend

#35088 Improve performance of AttachResourceConfigTransformer on big graphs
  internal/terraform/transform_attach_config_resource.go
Labels: enhancement
