Repository hashicorp/terraform, pull requests merged in 2024-10, with the labels that each got.

#35805 Bumped go-cty-yaml to v1.1.0
  go.mod
  go.sum
Labels: enhancement

#35808 docs: clarify map key quoting and formatting rules
  website/docs/language/expressions/type-constraints.mdx
Labels: documentation, tw-reviewed, 1.9-backport

#35797 docs: escape value for -generate-config-out arg
  website/docs/language/import/generating-configuration.mdx
Labels: documentation, 1.9-backport

#35666 Add additional validation to `secret_suffix` in Kubernetes backend
  internal/backend/remote-state/kubernetes/backend.go
  internal/backend/remote-state/kubernetes/backend_test.go
  internal/backend/remote-state/kubernetes/client.go
  website/docs/language/backend/kubernetes.mdx
Labels: bug, backend/k8s

#35661 Introduce S3-native state locking
  internal/backend/remote-state/s3/backend.go
  internal/backend/remote-state/s3/backend_state.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/client_test.go
  website/docs/language/backend/s3.mdx
Labels: enhancement, backend/s3

#35837 configgen: escape any invalid HCL syntax in map keys
  internal/genconfig/generate_config.go
  internal/genconfig/generate_config_test.go
Labels: 1.9-backport

#35839 init: detect and report invalid submodules
  internal/initwd/module_install.go
  internal/initwd/module_install_test.go
  internal/initwd/testdata/invalid-registry-modules/.gitignore
  internal/initwd/testdata/invalid-registry-modules/root.tf
Labels: 1.9-backport

#35842 provider meta: don't return providers with invalid names
  internal/configs/provider_meta.go
Labels: 1.9-backport

#35845 backend/s3: s3 native locking changelog entry
  CHANGELOG.md
Labels: backend/s3

#35856 Terraform core documentation for stacks
  website/data/language-nav-data.json
  website/docs/language/stacks/create/config.mdx
  website/docs/language/stacks/create/declare-providers.mdx
  website/docs/language/stacks/deploy/authenticate.mdx
  website/docs/language/stacks/deploy/conditions.mdx
  website/docs/language/stacks/deploy/config.mdx
  website/docs/language/stacks/design.mdx
  website/docs/language/stacks/index.mdx
  website/docs/language/stacks/reference/tfdeploy.mdx
  website/docs/language/stacks/reference/tfstack.mdx
  website/docs/language/stacks/reference/tfstacks-cli.mdx
  website/docs/language/stacks/use-cases.mdx
  website/img/docs/stacks-example.png
Labels: 1.9-backport

#35858 specify that stacks is hcp
  website/docs/language/stacks/index.mdx
Labels: 1.9-backport

#35864 plan: also validate provider requirements from state
  internal/configs/config.go
  internal/terraform/context.go
  internal/terraform/context_apply_checks_test.go
  internal/terraform/context_plan.go
  internal/terraform/context_test.go
Labels: 1.9-backport

#35812 states: check root output value changes in refresh-only mode
  internal/command/testdata/show-json/conditions/output-refresh-only.json
  internal/states/state.go
  internal/states/state_equal.go
  internal/states/state_test.go
  internal/terraform/context_plan.go
Labels: bug

#35896 Small stacks feedback
  website/docs/language/stacks/create/config.mdx
  website/docs/language/stacks/deploy/conditions.mdx
  website/docs/language/stacks/deploy/config.mdx
  website/docs/language/stacks/reference/tfdeploy.mdx
Labels: documentation, 1.9-backport

#35933 Specify Terraform version for stacks CLI
  website/docs/language/stacks/reference/tfstacks-cli.mdx
Labels: 1.9-backport, 1.10-backport
