Repository hashicorp/terraform, pull requests merged in 2025-08, with the labels that each got.

#37391 add more tests for failing actions
  internal/terraform/context_apply_action_test.go
Labels: no-changelog-needed

#37379 Append warning in CLI output when query result is empty
  internal/command/query_test.go
  internal/command/testdata/query/empty-result/main.tf
  internal/command/testdata/query/empty-result/query.tfquery.hcl
  internal/command/views/hook_json.go
  internal/command/views/hook_ui.go
  internal/command/views/json/message_types.go
  internal/command/views/query_operation.go
Labels: no-changelog-needed

#37398 Bump backport assistant to 0.5.8
  .github/workflows/backport.yml
Labels: no-changelog-needed

#37399 actions: add client capabilities across the board
  docs/plugin-protocol/tfplugin5.proto
  docs/plugin-protocol/tfplugin6.proto
  internal/grpcwrap/provider.go
  internal/grpcwrap/provider6.go
  internal/plugin/grpc_provider.go
  internal/plugin6/grpc_provider.go
  internal/providers/provider.go
  internal/terraform/node_action_apply.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: no-changelog-needed

#37403 add actions to the planfile config
  internal/command/jsonconfig/config.go
  internal/command/show_test.go
  internal/command/testdata/show-json-actions/main.tf
  internal/command/testdata/show-json-actions/output.json
Labels: no-changelog-needed

#37407 Prepare for 1.13.0-rc1 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#37385 Improve diagnostics around skip_cleanup conflicts
  internal/command/test_test.go
  internal/configs/parser_config_dir_test.go
  internal/configs/test_file.go
  internal/configs/testdata/invalid-test-files/skip_cleanup_after_backend.tftest.hcl
  internal/moduletest/graph/test_graph_builder.go
Labels: no-changelog-needed

#37411 Prepare for 1.14.0-alpha20250806 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#37415 Allow list resource RPC events with only warnings
  internal/plugin/grpc_provider.go
  internal/plugin/grpc_provider_test.go
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
Labels: no-changelog-needed

#37418 PSS: Implement first gRPC methods: config validation and usage, listing and deleting workspaces
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
Labels: no-changelog-needed

#37434 Prepare for 1.14.0-alpha20250813 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#37452 bump: go-getter to v1.7.9
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oci/go.sum
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.sum
Labels: bug, security, no-changelog-needed

#37457 actions: improve error messages and reenable error related tests
  internal/terraform/context_apply_action_test.go
  internal/terraform/context_plan_actions_test.go
  internal/terraform/node_action_trigger_apply.go
  internal/terraform/node_action_trigger_instance_plan.go
  internal/terraform/transform_action_diff.go
Labels: no-changelog-needed

#37474 Un-hardcode TF version in test
  internal/command/workdir/backend_state_test.go
Labels: no-changelog-needed

#37467 add SRO message for planned action invocation
  internal/command/views/json/change.go
  internal/command/views/json/message_types.go
  internal/command/views/json_view.go
  internal/command/views/operation.go
  internal/command/views/operation_test.go
Labels: no-changelog-needed

#37416 stacks migrate: make diagnostics more relevant to operation
  internal/stacks/stackmigrate/migrate_test.go
  internal/stacks/stackmigrate/resources.go
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/single-component/child/child.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/single-component/child/grandchild/main.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/single-component/single-component.tfcomponent.hcl
Labels: no-changelog-needed

#37460 add more test cases for invoking actions during apply
  internal/terraform/context_apply_action_test.go
Labels: no-changelog-needed

#37477 terraform test: fix regression when running with no tests (#37475)
  .changes/v1.13/BUG FIXES-20250821-091753.yaml
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/no-tests/main.tf
Labels: bug, 1.13-backport

#37484 test: don't panic when resolving references that haven't been evaluated
  .changes/v1.13/BUG FIXES-20250825-125018.yaml
  internal/command/test_test.go
  internal/command/testdata/test/expect-failures-assertions/child/main.tf
  internal/command/testdata/test/expect-failures-assertions/main.tf
  internal/command/testdata/test/expect-failures-assertions/main.tftest.hcl
  internal/instances/expander.go
  internal/terraform/evaluate.go
Labels: 1.13-backport

#37464 [WIP] - Testing ReadStateBytes and WriteStateBytes
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
  internal/plugin6/mock_proto/generate.go
  internal/plugin6/mock_proto/mock.go
Labels: no-changelog-needed

#37492 Add code comment to make in-progress migration from Ui to View more obvious
  internal/command/meta.go
Labels: no-changelog-needed

#37495 Exclude nested config block from list resource schemas
  internal/command/jsonformat/plan_test.go
  internal/command/jsonprovider/provider.go
  internal/command/jsonprovider/provider_test.go
Labels: no-changelog-needed

#37461 Update info for debugging why `TestInitProvidersLocalOnly` may fail
  internal/command/e2etest/init_test.go
Labels: no-changelog-needed

#37503 Prepare for 1.13.1 release
  .changes/1.13.1.md
  .changes/v1.13/BUG FIXES-20250821-091753.yaml
  .changes/v1.13/BUG FIXES-20250825-125018.yaml
  CHANGELOG.md
  version/VERSION
Labels: skip-changelog-check

#37508 Fix S3 backend test affected by making the Workspaces method return errors via diagnostics
  internal/backend/remote-state/s3/backend_test.go
Labels: backend/s3, no-changelog-needed

#37511 include experimental schemas for displaying the plan
  internal/command/jsonformat/plan_test.go
  internal/command/jsonprovider/provider.go
  internal/command/jsonprovider/provider_test.go
Labels: no-changelog-needed

#37521 actions: add invoke nodes to the graph
  internal/command/apply.go
  internal/command/arguments/extended.go
  internal/command/jsonplan/action_invocations.go
  internal/command/plan.go
  internal/command/views/hook_json_test.go
  internal/command/views/json/change.go
  internal/command/views/json/hook.go
  internal/command/views/operation_test.go
  internal/configs/action.go
  internal/configs/actiontriggerevent_string.go
  internal/plans/action_invocation.go
  internal/plans/changes_src.go
  internal/plans/deferring/deferred.go
  internal/plans/plan.go
  internal/plans/planfile/tfplan.go
  internal/plans/planfile/tfplan_test.go
  internal/plans/planproto/planfile.pb.go
  internal/plans/planproto/planfile.proto
  internal/terraform/context_apply.go
  internal/terraform/context_apply_action_test.go
  internal/terraform/context_plan.go
  internal/terraform/context_plan_actions_test.go
  internal/terraform/graph_builder_apply.go
  internal/terraform/graph_builder_plan.go
  internal/terraform/node_action.go
  internal/terraform/node_action_instance.go
  internal/terraform/node_action_invoke.go
  internal/terraform/node_action_trigger_instance_plan.go
  internal/terraform/transform_action_diff.go
  internal/terraform/transform_action_plan.go
  internal/terraform/transform_config.go
  internal/terraform/transform_targets.go
Labels: no-changelog-needed

#37527 actions: update JSON output to include invoked actions
  internal/command/views/hook_json_test.go
  internal/command/views/json/action_addr.go
  internal/command/views/json/change.go
  internal/command/views/json/hook.go
  internal/command/views/operation_test.go
Labels: no-changelog-needed

#37528 actions: detect cycle when before actions refer to the triggering resource
  internal/terraform/context_plan_actions_test.go
  internal/terraform/node_action_trigger_apply.go
Labels: no-changelog-needed

#37533 removing references to linked and lifecycle actions
  internal/terraform/node_action_validate.go
Labels: no-changelog-needed
