Repository hashicorp/terraform, pull requests merged in 2025-04, with the labels that each got.

#36778 stacks: provide stack and config on component creation
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/component_config.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/expression_refs.go
  internal/stacks/stackruntime/internal/stackeval/input_variable.go
  internal/stacks/stackruntime/internal/stackeval/input_variable_config.go
  internal/stacks/stackruntime/internal/stackeval/local_value.go
  internal/stacks/stackruntime/internal/stackeval/local_value_config.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/output_value.go
  internal/stacks/stackruntime/internal/stackeval/output_value_config.go
  internal/stacks/stackruntime/internal/stackeval/output_value_test.go
  internal/stacks/stackruntime/internal/stackeval/provider.go
  internal/stacks/stackruntime/internal/stackeval/provider_config.go
  internal/stacks/stackruntime/internal/stackeval/provider_config_test.go
  internal/stacks/stackruntime/internal/stackeval/provider_expressions.go
  internal/stacks/stackruntime/internal/stackeval/provider_instance.go
  internal/stacks/stackruntime/internal/stackeval/provider_instance_test.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_config.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
Labels: no-changelog-needed

#36782 stacks: rename Removed to RemovedComponent in stackeval
  internal/stacks/stackruntime/internal/stackeval/applying.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/removed_component.go
  internal/stacks/stackruntime/internal/stackeval/removed_component_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/internal/stackeval/walk_static.go
Labels: no-changelog-needed

#36792 Update URLs from `www.terraform.io` to `developer.hashicorp.com`
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  docs/README.md
  docs/architecture.md
  docs/planning-behaviors.md
  docs/plugin-protocol/README.md
  docs/plugin-protocol/object-wire-format.md
  internal/backend/remote-state/s3/backend.go
  internal/cloud/testdata/apply-json-with-outputs/plan-redacted.json
  internal/cloud/testdata/apply-json-with-provisioner-error/plan-redacted.json
  internal/cloud/testdata/apply-json-with-provisioner/plan-redacted.json
  internal/cloud/testdata/apply-json/plan-redacted.json
  internal/cloud/testdata/plan-json-basic-no-unredacted/plan-redacted.json
  internal/cloud/testdata/plan-json-basic/plan-redacted.json
  internal/cloud/testdata/plan-json-no-changes/plan-redacted.json
  internal/cloud/testdata/test-verbose/test.log
  internal/command/import.go
  internal/command/meta_backend_migrate.go
  internal/command/version.go
  internal/command/version_test.go
  internal/command/views/init.go
  internal/command/views/testdata/plans/redacted-plan.json
  internal/providercache/installer_test.go
  internal/providercache/package_install.go
  tools/terraform-bundle/README.md
  website/docs/cli/commands/version.mdx
Labels: no-changelog-needed

#36811 docs: Correct wording in CLI configuration page
  website/docs/cli/config/config-file.mdx
Labels: 1.11-backport, no-changelog-needed

#36800 Bump golang.org/x/net from 0.37.0 to 0.38.0 (fixes CVE-2025-22872)
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.mod
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.mod
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
  internal/legacy/go.mod
  internal/legacy/go.sum
Labels: no-changelog-needed

#36813 providers/testing: Remove unused `*TypeName` fields
  internal/providers/testing/provider_mock.go
Labels: no-changelog-needed

#36815 Add protocol 5 support in prototype branch
  docs/plugin-protocol/tfplugin5.10.proto
  internal/grpcwrap/provider.go
  internal/plugin/mock_proto/mock.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin5/tfplugin5.proto
Labels: no-changelog-needed

#36806 Fix `ImportResourceState` RPC response decoding for identity data
  internal/plugin/grpc_provider.go
  internal/plugin/grpc_provider_test.go
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
Labels: no-changelog-needed

#36793 Replace custom conditions article with Validate your configuration
  website/data/language-nav-data.json
  website/docs/cli/test/index.mdx
  website/docs/language/data-sources/index.mdx
  website/docs/language/expressions/conditionals.mdx
  website/docs/language/expressions/custom-conditions.mdx
  website/docs/language/functions/format.mdx
  website/docs/language/functions/plantimestamp.mdx
  website/docs/language/functions/timecmp.mdx
  website/docs/language/meta-arguments/lifecycle.mdx
  website/docs/language/modules/develop/composition.mdx
  website/docs/language/resources/syntax.mdx
  website/docs/language/test-and-validate/validate.mdx
  website/docs/language/tests/index.mdx
  website/docs/language/values/outputs.mdx
  website/docs/language/values/variables.mdx
  website/img/docs/validation-order-of-operations-dark.jpg
  website/img/docs/validation-order-of-operations-light.jpg
Labels: no-changelog-needed

#36702 stacks: emit state updates for unclaimed components
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
Labels: no-changelog-needed

#36703 Config-driven importing through identity (TF-23179)
  internal/command/import.go
  internal/command/views/hook_ui.go
  internal/configs/import.go
  internal/configs/import_test.go
  internal/plans/changes.go
  internal/plans/changes_src.go
  internal/states/instance_object.go
  internal/states/state_deepcopy.go
  internal/terraform/context_apply2_test.go
  internal/terraform/context_import.go
  internal/terraform/context_import_test.go
  internal/terraform/context_plan_import_test.go
  internal/terraform/eval_import.go
  internal/terraform/hook.go
  internal/terraform/hook_mock.go
  internal/terraform/hook_stop.go
  internal/terraform/hook_test.go
  internal/terraform/node_resource_abstract.go
  internal/terraform/node_resource_plan.go
  internal/terraform/node_resource_plan_instance.go
  internal/terraform/node_resource_validate.go
  internal/terraform/testdata/import-identity-module/child/main.tf
  internal/terraform/testdata/import-identity-module/main.tf
  internal/tfdiags/object.go
  internal/tfdiags/object_test.go
Labels: enhancement, no-changelog-needed

#36822 Turn main into 1.13 dev branch
  .changes/1.13.0.md
  .changes/previous-releases.md
  .changes/v1.11/BUG FIXES-20250205-095231.yaml
  .changes/v1.11/BUG FIXES-20250205-36435.yaml
  .changes/v1.11/BUG FIXES-20250206-145217.yaml
  .changes/v1.11/BUG FIXES-20250206-155025.yaml
  .changes/v1.11/BUG FIXES-20250225-083056.yaml
  .changes/v1.11/BUG FIXES-20250226-181429.yaml
  .changes/v1.11/BUG FIXES-20250303-125722.yaml
  .changes/v1.11/BUG FIXES-20250303-144020.yaml
  .changes/v1.11/BUG FIXES-20250311-104640.yaml
  .changes/v1.11/BUG FIXES-20250319-091234.yaml
  .changes/v1.11/ENHANCEMENTS-20250130-105700.yaml
  .changes/v1.11/ENHANCEMENTS-20250207-164803.yaml
  .changes/v1.11/ENHANCEMENTS-20250211-36486.yaml
  .changes/v1.11/ENHANCEMENTS-20250219-094101.yaml
  .changes/v1.11/NOTES-20250305-101858.yaml
  .changes/v1.12/BUG FIXES-20250123-135228.yaml
  .changes/v1.12/BUG FIXES-20250123-150746.yaml
  .changes/v1.12/BUG FIXES-20250210-163038.yaml
  .changes/v1.12/BUG FIXES-20250226-171815.yaml
  .changes/v1.12/BUG FIXES-20250331-150802.yaml
  .changes/v1.12/ENHANCEMENTS-20250123-101838.yaml
  .changes/v1.12/ENHANCEMENTS-20250203-170319.yaml
  .changes/v1.12/ENHANCEMENTS-20250204-182544.yaml
  .changes/v1.12/ENHANCEMENTS-20250205-104144.yaml
  .changes/v1.12/ENHANCEMENTS-20250206-34969.yaml
  .changes/v1.12/ENHANCEMENTS-20250220-120438.yaml
  .changes/v1.12/ENHANCEMENTS-20250303-151031.yaml
  .changes/v1.12/ENHANCEMENTS-20250318-001121.yaml
  .changes/v1.12/UPGRADE NOTES-20250212-36478.yaml
  .changes/v1.13/.gitkeep
  .changie.yaml
  .github/pull_request_template.md
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36821 Prepare for 1.12.0-beta1 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36824 write-only attributes: internal providers should set write-only attributes to null
  .changes/v1.11/BUG FIXES-20250402-143931.yaml
  internal/command/test_test.go
  internal/command/testdata/test/write-only-attributes-mocked/main.tf
  internal/command/testdata/test/write-only-attributes-mocked/main.tftest.hcl
  internal/command/testdata/test/write-only-attributes-overridden/main.tf
  internal/command/testdata/test/write-only-attributes-overridden/main.tftest.hcl
  internal/command/testdata/test/write-only-attributes/main.tf
  internal/command/testdata/test/write-only-attributes/main.tftest.hcl
  internal/command/testing/test_provider.go
  internal/lang/ephemeral/strip.go
  internal/lang/ephemeral/strip_test.go
  internal/lang/ephemeral/validate.go
  internal/lang/ephemeral/validate_test.go
  internal/providers/mock.go
  internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-write-only-attribute/with-write-only-attribute.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/with-write-only-attribute/with-write-only-attribute.tfstack.hcl
  internal/stacks/stackruntime/testing/provider.go
  internal/stacks/stackruntime/testing/resource.go
  internal/terraform/node_resource_abstract_instance.go
  internal/terraform/node_resource_plan_instance.go
Labels: 1.11-backport, 1.12-backport

#36798 Consolidate install pages
  website/data/cli-nav-data.json
  website/docs/cli/install/apt.mdx
  website/docs/cli/install/yum.mdx
Labels: documentation, no-changelog-needed, 1.12-backport

#36833 Fix non-user facing bugs where appended diags are not returned in `terraform` provider
  internal/builtin/providers/terraform/provider.go
Labels: no-changelog-needed

#36729 Terraform Test: Allow skipping cleanup of entire test file or individual run blocks
  internal/command/test_test.go
  internal/command/testdata/test/skip_cleanup/main.tf
  internal/command/testdata/test/skip_cleanup/main.tftest.hcl
  internal/command/testdata/test/skip_file_cleanup/main.tf
  internal/command/testdata/test/skip_file_cleanup/main.tftest.hcl
  internal/command/views/test.go
  internal/command/views/test_test.go
  internal/configs/test_file.go
  internal/moduletest/graph/node_state_cleanup.go
  internal/moduletest/graph/transform_state_cleanup.go
  internal/moduletest/graph/transform_test_run.go
  internal/moduletest/graph/wait.go
Labels: no-changelog-needed

#36787 stacks: allow removed blocks to target components in nested stacks
  internal/rpcapi/stacks.go
  internal/stacks/stackaddrs/removed.go
  internal/stacks/stackaddrs/removed_test.go
  internal/stacks/stackconfig/config.go
  internal/stacks/stackconfig/declarations.go
  internal/stacks/stackconfig/removed.go
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/hooks/component.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/expressions.go
  internal/stacks/stackruntime/internal/stackeval/hooks.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_component.go
  internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/internal/stackeval/walk_static.go
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-component-from-stack-dynamic/removed-component-from-stack-dynamic.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-component-from-stack/removed-component-from-stack.tfstack.hcl
Labels: no-changelog-needed

#36788 stacks: include existing components when deferring nested stacks
  internal/stacks/stackaddrs/in_stack.go
  internal/stacks/stackplan/plan.go
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/removed_component.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/deferred-embedded-stack-for-each/deferred-embedded-stack-for-each.tfstack.hcl
  internal/stacks/stackstate/state.go
Labels: no-changelog-needed

#36829 Backport #36818 into go 1.12
  internal/backend/local/backend_local.go
  internal/backend/local/test.go
  internal/backend/remote-state/kubernetes/client.go
  internal/command/cliconfig/cliconfig.go
  internal/command/format/diagnostic.go
  internal/command/jsonformat/state.go
  internal/command/jsonstate/state.go
  internal/command/junit/junit.go
  internal/command/junit/junit_internal_test.go
  internal/command/meta.go
  internal/configs/config.go
  internal/configs/config_build.go
  internal/configs/configload/loader_snapshot.go
  internal/dag/dot.go
  internal/dag/set.go
  internal/depsfile/locks.go
  internal/depsfile/locks_file.go
  internal/genconfig/generate_config.go
  internal/lang/eval.go
  internal/moduleref/resolver.go
  internal/moduletest/graph/eval_context.go
  internal/plans/planfile/config_snapshot.go
  internal/plans/planfile/tfplan.go
  internal/states/state_deepcopy.go
  internal/states/statefile/version3_upgrade.go
  internal/terraform/transform_ephemeral_resource_close.go
Labels: no-changelog-needed

#36840 Remove paragraph that logical operators do not short-circuit for 1.12
  website/docs/language/expressions/operators.mdx
Labels: no-changelog-needed, 1.12-backport

#36842 Remove unused test fixture "push-backend-new"
  internal/command/testdata/push-backend-new/main.tf
Labels: no-changelog-needed

#36814 stacks: update removed blocks to allow targeting of embedded stacks
  internal/rpcapi/stacks.go
  internal/stacks/stackaddrs/removed.go
  internal/stacks/stackaddrs/removed_test.go
  internal/stacks/stackconfig/config.go
  internal/stacks/stackconfig/declarations.go
  internal/stacks/stackconfig/embedded_stack.go
  internal/stacks/stackconfig/removed.go
  internal/stacks/stackplan/plan.go
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_component.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_config.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/internal/stackeval/walk_static.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-stack-instance-dynamic/removed-stack-instance-dynamic.tfstack.hcl
  internal/stacks/stackstate/state.go
Labels: no-changelog-needed

#36860 Fix for #36859 in mocking.mdx
  website/docs/language/tests/mocking.mdx
Labels: documentation, no-changelog-needed, 1.12-backport

#36856 Add comments about use of ResourceStores with TestProviders
  internal/command/testing/test_provider.go
Labels: no-changelog-needed

#36867 Prepare for 1.11.4 release
  .changes/1.11.4.md
  .changes/v1.11/BUG FIXES-20250327-094612.yaml
  .changes/v1.11/BUG FIXES-20250402-143931.yaml
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36870 Bump Go version to 1.24.2
  .go-version
  go.mod
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/cos/go.mod
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/pg/go.mod
  internal/backend/remote-state/s3/go.mod
  internal/legacy/go.mod
Labels: no-changelog-needed, 1.12-backport

#36873 Update sources.mdx
  website/docs/language/modules/sources.mdx
Labels: no-changelog-needed, 1.12-backport

#36868 remove bucket name from s3:prefix condition in IAM policy
  website/docs/language/backend/s3.mdx
Labels: documentation, backend/s3, no-changelog-needed

#36869 Replace sc with Set-Content
  website/docs/cli/commands/state/pull.mdx
  website/docs/cli/commands/state/push.mdx
Labels: documentation, no-changelog-needed, 1.12-backport

#36878 grpcwrap+provider-simple: Test ephemeral resource schemas in v5 protocol
  internal/command/e2etest/providers_schema_test.go
  internal/grpcwrap/provider.go
  internal/provider-simple/provider.go
Labels: no-changelog-needed

#36834 Update get provider schema to include state store information
  docs/plugin-protocol/tfplugin5.10.proto
  docs/plugin-protocol/tfplugin6.10.proto
  internal/builtin/providers/terraform/provider.go
  internal/command/testing/test_provider.go
  internal/grpcwrap/provider.go
  internal/grpcwrap/provider6.go
  internal/providers/provider.go
  internal/providers/testing/provider_mock.go
  internal/stacks/stackruntime/testing/provider.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: no-changelog-needed

#36852 Fix defects where `done` is called before the command's `Run` method is invoked
  internal/command/test_test.go
Labels: no-changelog-needed

#36857 Add validation to enforce skip_cleanup=false cannot be used with backends
  internal/command/test_test.go
  internal/command/testdata/test/backend-with-skip-cleanup/false/main.tf
  internal/command/testdata/test/backend-with-skip-cleanup/false/main.tftest.hcl
  internal/command/testdata/test/backend-with-skip-cleanup/true/main.tf
  internal/command/testdata/test/backend-with-skip-cleanup/true/main.tftest.hcl
  internal/configs/test_file.go
Labels: no-changelog-needed

#36876 CODEOWNERS: Set tf-core-cloud as owner of Cloud backend
  CODEOWNERS
Labels: no-changelog-needed

#36887 Fix import with optional identity attributes
  internal/configs/configschema/implied_type.go
  internal/terraform/context_plan_import_test.go
  internal/terraform/eval_import.go
  internal/terraform/node_resource_plan_instance.go
  internal/tfdiags/object.go
  internal/tfdiags/object_test.go
Labels: bug, no-changelog-needed, 1.12-backport

#36890 Prepare for 1.12.0-beta2 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36888 Upgrade guide for v1.11
  website/docs/language/upgrade-guides/index.mdx
Labels: no-changelog-needed

#36891 Update guide nav
  website/data/language-nav-data.json
  website/docs/language/upgrade-guides/index.mdx
Labels: no-changelog-needed

#36848 Integrate use of backend blocks in tests with skip_cleanup feature
  internal/command/test_test.go
  internal/command/testdata/test/valid-use-local-backend/main.tf
  internal/command/testdata/test/valid-use-local-backend/main.tftest.hcl
  internal/command/testdata/test/valid-use-local-backend/no-prior-state/main.tf
  internal/command/testdata/test/valid-use-local-backend/no-prior-state/main.tftest.hcl
  internal/command/testdata/test/valid-use-local-backend/with-prior-state/main.tf
  internal/command/testdata/test/valid-use-local-backend/with-prior-state/main.tftest.hcl
  internal/command/testdata/test/valid-use-local-backend/with-prior-state/terraform.tfstate
  internal/configs/test_file.go
  internal/moduletest/graph/apply.go
  internal/moduletest/graph/node_state_cleanup.go
  internal/moduletest/graph/transform_state.go
Labels: no-changelog-needed

#36832 Add documentation for using a `backend` block during `test`
  website/docs/language/tests/index.mdx
Labels: no-changelog-needed

#36838 More test documentation
  internal/command/test_test.go
  internal/command/testdata/test/skip_file_cleanup/main.tftest.hcl
  website/docs/cli/commands/test.mdx
  website/docs/language/tests/index.mdx
Labels: no-changelog-needed

#36850 stacks: refactor plan, state, and removed tracking for efficient lookups
  internal/rpcapi/resource_identity.go
  internal/stacks/stackaddrs/stack.go
  internal/stacks/stackconfig/declarations.go
  internal/stacks/stackplan/from_proto.go
  internal/stacks/stackplan/from_proto_test.go
  internal/stacks/stackplan/plan.go
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/helper_test.go
  internal/stacks/stackruntime/internal/stackeval/applying.go
  internal/stacks/stackruntime/internal/stackeval/applying_test.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/planning_test.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_component.go
  internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackstate/state.go
Labels: no-changelog-needed

#36847 Terraform Test: cleanup command
  commands.go
  internal/backend/local/test.go
  internal/command/arguments/test.go
  internal/command/test.go
  internal/command/test_cleanup.go
  internal/command/test_test.go
  internal/command/testdata/test/cleanup/main.tf
  internal/command/testdata/test/cleanup/main.tftest.hcl
  internal/command/views/test.go
  internal/moduletest/graph/eval_context.go
  internal/moduletest/graph/manifest.go
  internal/moduletest/graph/node_state_cleanup.go
  internal/moduletest/graph/test_graph_builder.go
  internal/moduletest/graph/transform_providers.go
  internal/moduletest/graph/transform_state.go
  internal/moduletest/graph/transform_state_cleanup.go
  internal/moduletest/suite.go
Labels: no-changelog-needed

#36913 backend/oci/deps: Pin flock to v0.10.0
  go.mod
  go.sum
  internal/backend/remote-state/oci/go.mod
  internal/backend/remote-state/oci/go.sum
Labels: no-changelog-needed

#36894 Remove protocol 5 support
  docs/plugin-protocol/tfplugin5.10.proto
  internal/grpcwrap/provider.go
  internal/plugin/mock_proto/mock.go
  internal/tfplugin5/tfplugin5.pb.go
Labels: no-changelog-needed

#36917 Prepare for 1.12.0-beta3 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36918 Cleanup after 1.12.0-beta3 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36901 stacks: removing embedded stacks should ignore stacks not in state
  internal/stacks/stackplan/plan.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackstate/state.go
Labels: no-changelog-needed

#36914 stacks: improve test coverage for removed blocks
  internal/stacks/stackconfig/config.go
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/input_variable.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_component.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/multiple-components/multiple-components.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/multiple-components/removed/removed.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/orphaned-component/orphaned-component.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-stack-from-embedded-stack/removed-stack-from-embedded-stack.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-stack-instance-dynamic/removed-stack-instance-dynamic.tfstack.hcl
Labels: no-changelog-needed

#36915 stacks: ensure consistent sources between removed blocks
  internal/stacks/stackconfig/config.go
  internal/stacks/stackconfig/config_test.go
  internal/stacks/stackconfig/testdata/basics-bundle/errored-sources/main.tf
  internal/stacks/stackconfig/testdata/basics-bundle/errored-sources/main.tfstack.hcl
  internal/stacks/stackconfig/testdata/basics-bundle/errored-sources/subdir/main.tfstack.hcl
  internal/stacks/stackconfig/testdata/basics-bundle/terraform-sources.json
Labels: no-changelog-needed

#36902 Allow cleanup of states that depend on prior runs outputs
  internal/backend/local/test.go
  internal/command/test_cleanup.go
  internal/command/test_test.go
  internal/command/testdata/test/skip_cleanup_with_run_deps/main.tf
  internal/command/testdata/test/skip_cleanup_with_run_deps/main.tftest.hcl
  internal/configs/parser_config_dir_test.go
  internal/configs/test_file.go
  internal/moduletest/graph/eval_context.go
  internal/moduletest/graph/manifest.go
  internal/moduletest/graph/node_state_cleanup.go
  internal/moduletest/graph/node_test_run.go
  internal/moduletest/graph/test_graph_builder.go
  internal/moduletest/graph/transform_state_cleanup.go
  internal/moduletest/graph/transform_test_run.go
Labels: no-changelog-needed

#36916 stacks: removed blocks should refresh during refresh plans
  internal/stacks/stackruntime/internal/stackeval/input_variable.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/removed_component_instance.go
  internal/stacks/stackruntime/internal/stackeval/removed_stack_call_instance.go
  internal/stacks/stackruntime/plan_refresh_test.go
Labels: no-changelog-needed

#36904 Validate identity to match identity schema
  internal/terraform/context_apply2_test.go
  internal/terraform/context_apply_identity_test.go
  internal/terraform/context_plan_identity_test.go
  internal/terraform/node_resource_abstract_instance.go
Labels: no-changelog-needed, 1.12-backport

#36893 Validate identity in import response
  internal/terraform/context_plan_import_test.go
  internal/terraform/node_resource_plan_instance.go
Labels: no-changelog-needed, 1.12-backport

#36934 Add the output reference page and align with the other block titles
  website/data/language-nav-data.json
  website/docs/cli/inspect/index.mdx
  website/docs/language/block/check.mdx
  website/docs/language/block/moved.mdx
  website/docs/language/block/output.mdx
  website/docs/language/block/terraform.mdx
  website/docs/language/expressions/function-calls.mdx
  website/docs/language/expressions/references.mdx
  website/docs/language/functions/ephemeralasnull.mdx
  website/docs/language/functions/terraform-applying.mdx
  website/docs/language/meta-arguments/for_each.mdx
  website/docs/language/modules/develop/index.mdx
  website/docs/language/modules/develop/structure.mdx
  website/docs/language/modules/syntax.mdx
  website/docs/language/resources/ephemeral/reference.mdx
  website/docs/language/resources/provisioners/connection.mdx
  website/docs/language/resources/provisioners/syntax.mdx
  website/docs/language/stacks/reference/tfstack.mdx
  website/docs/language/state/remote-state-data.mdx
  website/docs/language/state/remote.mdx
  website/docs/language/state/sensitive-data.mdx
  website/docs/language/test-and-validate/validate.mdx
  website/docs/language/v1-compatibility-promises.mdx
  website/docs/language/values/index.mdx
  website/docs/language/values/locals.mdx
  website/docs/language/values/outputs.mdx
  website/docs/language/values/variables.mdx
Labels: no-changelog-needed

#36905 Add changelog entries for resource identities
  .changes/v1.12/ENHANCEMENTS-20250417-182036.yaml
Labels: 1.12-backport

#36903 Add resource identities to plan file and JSON output
  internal/command/jsonplan/plan.go
  internal/command/jsonplan/resource.go
  internal/command/jsonplan/values.go
  internal/command/jsonplan/values_test.go
  internal/plans/changes.go
  internal/plans/changes_src.go
  internal/plans/planfile/tfplan.go
  internal/plans/planproto/planfile.pb.go
  internal/plans/planproto/planfile.proto
  internal/terraform/context_plan_import_test.go
Labels: no-changelog-needed, 1.12-backport

#36969 Prepare for 1.12.0-rc1 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36945 Fix remote-state backend name in CODEOWNERS
  CODEOWNERS
Labels: no-changelog-needed

#36944 Break dependency of stack migrate on command Meta to prevent import cycles
  internal/stacks/stackmigrate/load.go
  internal/stacks/stackmigrate/load_test.go
  internal/stacks/stackmigrate/meta.go
  internal/stacks/stackmigrate/meta_test.go
Labels: no-changelog-needed

#36971 Cleanup after 1.12.0-rc1 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36965 Add provider example to terraform applying
  website/docs/language/functions/terraform-applying.mdx
Labels: 1.10-backport, 1.11-backport, no-changelog-needed, 1.12-backport

#36962 Add documentation to refactor Terraform state
  website/data/language-nav-data.json
  website/docs/language/state/refactor.mdx
Labels: 1.7-backport, 1.8-backport, 1.9-backport, 1.10-backport, 1.11-backport, no-changelog-needed, 1.12-backport
