Repository hashicorp/terraform, pull requests merged in 2025-09, with the labels that each got.

#37540 actions: render invoked actions
  internal/backend/local/backend_apply.go
  internal/command/jsonformat/diff.go
  internal/command/jsonformat/plan.go
  internal/command/jsonformat/plan_test.go
Labels: no-changelog-needed

#37541 actions: allow skipping refresh when invoking actions
  internal/command/arguments/extended.go
  internal/terraform/context_apply_action_test.go
  internal/terraform/context_plan.go
  internal/terraform/context_plan_actions_test.go
Labels: no-changelog-needed

#37547 test fix: sort DeferredActionInvocations before making assertions
  internal/terraform/context_plan_actions_test.go
Labels: no-changelog-needed

#37529 Update proto file definition of Read/WriteStateBytes RPCs
  docs/plugin-protocol/tfplugin6.proto
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
  internal/plugin6/mock_proto/mock.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: no-changelog-needed

#37548 actions: add number of invoked actions to plan summary
  internal/command/jsonformat/plan.go
  internal/command/jsonformat/plan_test.go
Labels: no-changelog-needed

#37556 Add test helper to create mock provider that contains a state store
  internal/command/meta_backend_test.go
  internal/command/testdata/backend-to-state-store/main.tf
  internal/command/testdata/state-store-changed/.terraform/terraform.tfstate
  internal/command/testdata/state-store-changed/main.tf
  internal/command/testdata/state-store-new-vars-in-provider/main.tf
  internal/command/testdata/state-store-new-vars-in-store/main.tf
  internal/command/testdata/state-store-new/main.tf
  internal/command/testdata/state-store-reconfigure/.terraform/terraform.tfstate
  internal/command/testdata/state-store-reconfigure/main.tf
  internal/command/testdata/state-store-to-backend/.terraform/terraform.tfstate
  internal/command/testdata/state-store-unset/.terraform/terraform.tfstate
  internal/configs/testdata/invalid-modules/conflict-cloud-backend-statestore/main.tf
  internal/configs/testdata/invalid-modules/conflict-cloud-statestore-separate-files/state-store.tf
  internal/configs/testdata/invalid-modules/conflict-cloud-statestore/main.tf
  internal/configs/testdata/invalid-modules/conflict-statestore-backend-separate-files/state-store.tf
  internal/configs/testdata/invalid-modules/conflict-statestore-backend/main.tf
  internal/configs/testdata/invalid-modules/multiple-state-store/a.tf
  internal/configs/testdata/valid-modules/override-state-store-no-base/override.tf
  internal/configs/testdata/valid-modules/override-state-store/main.tf
Labels: no-changelog-needed

#37502 Update `remote.Client` interface's methods to return diagnostics instead of primitive errors
  internal/backend/remote-state/azure/client.go
  internal/backend/remote-state/azure/client_test.go
  internal/backend/remote-state/consul/client.go
  internal/backend/remote-state/consul/client_test.go
  internal/backend/remote-state/cos/client.go
  internal/backend/remote-state/gcs/client.go
  internal/backend/remote-state/http/client.go
  internal/backend/remote-state/inmem/client.go
  internal/backend/remote-state/kubernetes/client.go
  internal/backend/remote-state/oci/client.go
  internal/backend/remote-state/oss/client.go
  internal/backend/remote-state/oss/client_test.go
  internal/backend/remote-state/pg/client.go
  internal/backend/remote-state/s3/backend_test.go
  internal/backend/remote-state/s3/client.go
  internal/backend/remote-state/s3/client_test.go
  internal/backend/remote/backend_state.go
  internal/backend/remote/backend_state_test.go
  internal/states/remote/remote.go
  internal/states/remote/remote_grpc.go
  internal/states/remote/remote_grpc_test.go
  internal/states/remote/remote_test.go
  internal/states/remote/state.go
  internal/states/remote/testing.go
Labels: no-changelog-needed

#37559 actions: validate that action referenced in action_trigger exists in config during transform
  internal/terraform/context_plan_actions_test.go
  internal/terraform/transform_config.go
Labels: no-changelog-needed

#37585 Prepare for 1.13.2 release
  .changes/1.13.2.md
  .changes/v1.13/BUG FIXES-20250905-083104.yaml
  .changes/v1.13/BUG FIXES-20250910-095424.yaml
  CHANGELOG.md
  version/VERSION
Labels: skip-changelog-check

#37578 Allow duplicate list names for different types
  internal/configs/parser_config_dir_test.go
  internal/configs/query_file.go
  internal/configs/testdata/query-files/valid/mixed/main.tfquery.hcl
Labels: no-changelog-needed

#37589 modefuletest: fix error return
  internal/moduletest/graph/eval_context.go
Labels: no-changelog-needed

#37608 actions: ensure config is known during apply
  internal/terraform/context_apply_action_test.go
  internal/terraform/node_action_trigger_apply.go
Labels: no-changelog-needed

#37607 temporarily require manager approval for go.mod changes
  CODEOWNERS
Labels: no-changelog-needed

#37479 Add support for Terraform Search in the cloud backend (TF-25935)
  .github/workflows/checks.yml
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.mod
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/http/mock_server_test.go
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oci/go.mod
  internal/backend/remote-state/oci/go.sum
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.mod
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
  internal/cloud/backend.go
  internal/cloud/backend_apply.go
  internal/cloud/backend_common.go
  internal/cloud/backend_plan.go
  internal/cloud/backend_query.go
  internal/cloud/backend_query_test.go
  internal/cloud/cloud_run.go
  internal/cloud/testdata/query-json-basic/main.tf
  internal/cloud/testdata/query-json-basic/main.tfquery.hcl
  internal/cloud/testdata/query-json-basic/query.log
  internal/cloud/testdata/query/main.tf
  internal/cloud/testdata/query/main.tfquery.hcl
  internal/cloud/testdata/query/query.log
  internal/cloud/testing.go
  internal/cloud/tfe_client_mock.go
  internal/cloudplugin/mock_cloudproto1/mock.go
  internal/command/jsonformat/renderer.go
  internal/legacy/go.mod
  internal/legacy/go.sum
  internal/plugin/mock_proto/mock.go
  internal/plugin6/mock_proto/mock.go
  internal/stacksplugin/mock_stacksproto1/mock.go
  internal/tfdiags/object.go
Labels: no-changelog-needed

#37611 actions: preserve unknown metadata in the json plan
  internal/command/jsonformat/plan_test.go
  internal/command/jsonformat/structured/change.go
  internal/command/jsonplan/action_invocations.go
  internal/command/jsonplan/action_invocations_test.go
Labels: no-changelog-needed

#37597 Update calls to StateMgr method to use diagnostics more conventionally
  internal/backend/local/backend.go
  internal/backend/local/testing.go
  internal/backend/remote-state/cos/backend_test.go
  internal/backend/remote-state/gcs/backend_test.go
  internal/backend/remote-state/kubernetes/client_test.go
  internal/backend/remote-state/oss/client_test.go
  internal/backend/remote-state/s3/client_test.go
  internal/command/meta_backend.go
  internal/command/meta_backend_migrate.go
  internal/moduletest/graph/eval_context.go
  internal/moduletest/states/manifest.go
Labels: no-changelog-needed

#37612 query: add identity_version to list_resource_found json output
  internal/command/query_test.go
  internal/command/views/hook_json.go
  internal/command/views/hook_ui.go
  internal/command/views/json/query.go
  internal/terraform/hook.go
  internal/terraform/hook_mock.go
  internal/terraform/hook_stop.go
  internal/terraform/hook_test.go
  internal/terraform/node_resource_plan_instance_query.go
Labels: no-changelog-needed

#37618 tf query: disable depends_on for list blocks
  internal/configs/parser_config_dir_test.go
  internal/configs/query_file.go
  internal/configs/testdata/query-files/invalid/with-depends-on/main.tfquery.hcl
Labels: no-changelog-needed

#37616 actions: remove references to action types, linked resources
  internal/command/jsonformat/plan_test.go
  internal/command/jsonprovider/provider_test.go
  internal/command/show_test.go
  internal/command/views/operation_test.go
  internal/configs/action.go
  internal/configs/action_test.go
  internal/configs/module_merge.go
  internal/lang/eval.go
  internal/plans/changes_src.go
  internal/plans/planfile/tfplan_test.go
  internal/plans/planproto/planfile.pb.go
  internal/plans/planproto/planfile.proto
  internal/plugin/grpc_provider_test.go
  internal/plugin6/grpc_provider_test.go
  internal/terraform/context_apply_action_test.go
  internal/terraform/context_plan_actions_test.go
  internal/terraform/resource_provider_mock_test.go
Labels: no-changelog-needed

#37621 Prepare main branch for post-v1.14 development
  .changes/1.15.0.md
  .changes/previous-releases.md
  .changes/v1.13/BUG FIXES-20250804-162137.yaml
  .changes/v1.13/BUG FIXES-20250821-091753.yaml
  .changes/v1.13/BUG FIXES-20250825-125018.yaml
  .changes/v1.13/BUG FIXES-20250905-083104.yaml
  .changes/v1.13/BUG FIXES-20250910-095424.yaml
  .changes/v1.13/BUG FIXES-20250911-142038.yaml
  .changes/v1.14/BUG FIXES-20250714-135938.yaml
  .changes/v1.14/BUG FIXES-20250828-182746.yaml
  .changes/v1.14/ENHANCEMENTS-20250723-122922.yaml
  .changes/v1.14/ENHANCEMENTS-20250723-141420.yaml
  .changes/v1.14/NEW FEATURES-20250829-151946.yaml
  .changes/v1.14/NEW FEATURES-20250903-131921.yaml
  .changes/v1.14/UPGRADE NOTES-20250814-162650.yaml
  .changes/v1.14/UPGRADE NOTES-20250814-162752.yaml
  .changes/v1.15/.gitkeep
  .changie.yaml
  .github/pull_request_template.md
  CHANGELOG.md
  internal/command/query_test.go
  version/VERSION
Labels: skip-changelog-check

#37628 query: constrict query files parsing to tf query command only
  internal/command/meta.go
  internal/command/meta_config.go
  internal/command/plan_test.go
  internal/command/query.go
  internal/command/query_test.go
  internal/configs/config_build_test.go
  internal/configs/configload/loader.go
  internal/configs/configload/loader_load.go
  internal/configs/configload/loader_snapshot.go
  internal/configs/configload/testing.go
  internal/configs/parser_config_dir.go
  internal/configs/parser_config_dir_test.go
  internal/configs/parser_file_matcher.go
  internal/initwd/testing.go
  internal/terraform/terraform_test.go
Labels: no-changelog-needed

#37619 tf query: ready list blocks for beta
  commands.go
  internal/cloud/backend_query.go
  internal/cloud/backend_query_test.go
  internal/cloud/testdata/query-json-basic/main.tfquery.hcl
  internal/cloud/testdata/query/main.tfquery.hcl
  internal/command/e2etest/providers_schema_test.go
  internal/command/jsonformat/plan_test.go
  internal/command/jsonformat/state_test.go
  internal/command/jsonprovider/provider.go
  internal/command/jsonprovider/provider_test.go
  internal/command/meta.go
  internal/command/meta_config.go
  internal/command/plan_test.go
  internal/command/providers_schema.go
  internal/command/query.go
  internal/command/query_test.go
  internal/command/state_show.go
  internal/command/views/operation.go
  internal/command/views/show.go
  internal/command/views/test.go
  internal/configs/config_build_test.go
  internal/configs/configload/loader.go
  internal/configs/configload/loader_load.go
  internal/configs/configload/loader_snapshot.go
  internal/configs/configload/testing.go
  internal/configs/parser_config_dir.go
  internal/configs/parser_config_dir_test.go
  internal/configs/parser_file_matcher.go
  internal/initwd/testing.go
  internal/terraform/terraform_test.go
  internal/tfdiags/object.go
Labels: no-changelog-needed, 1.14-backport

#37631 Prepare for 1.13.3 release
  .changes/1.13.3.md
  .changes/v1.13/BUG FIXES-20250911-142038.yaml
  CHANGELOG.md
  version/VERSION
Labels: skip-changelog-check

#37653 actions: allow invoke only on local execution while TFC adds support
  internal/command/plan.go
Labels: no-changelog-needed, 1.14-backport

#37645 Handle `-help` usage in stacks plugin
  .changes/v1.14/ENHANCEMENTS-20250919-115253.yaml
  internal/command/stacks.go
Labels: 1.14-backport

#37620 list: send non-null "config" object to provider when not present in the list block
  internal/command/query_test.go
  internal/plugin/convert/schema.go
  internal/plugin/grpc_provider.go
  internal/plugin/grpc_provider_test.go
  internal/plugin6/convert/schema.go
  internal/plugin6/grpc_provider.go
  internal/plugin6/grpc_provider_test.go
  internal/providers/provider.go
  internal/providers/schemas.go
  internal/terraform/context_plan_query_test.go
  internal/terraform/evaluate_valid.go
  internal/terraform/node_resource_plan_instance_query.go
  internal/terraform/node_resource_validate.go
Labels: no-changelog-needed, 1.14-backport

#37663 evaluate: return diagnostics instead of unknown for uninitialised locals and resources
  .changes/v1.14/BUG FIXES-20250924-110416.yaml
  internal/command/test_test.go
  internal/command/testdata/test/invalid-reference-with-target/main.tf
  internal/command/testdata/test/invalid-reference-with-target/main.tftest.hcl
  internal/terraform/context_plan_actions_test.go
  internal/terraform/evaluate.go
Labels: 1.14-backport

#37668 Prepare for 1.14.0-beta2 release
  CHANGELOG.md
  version/VERSION
Labels: skip-changelog-check

#37674 Prepare for 1.14.0-beta2 release
  CHANGELOG.md
  version/VERSION
Labels: skip-changelog-check

#37677 Cleanup after 1.14.0-beta2 release
  CHANGELOG.md
  version/VERSION
Labels: skip-changelog-check

#37690 backport of actions: don't panic when resource change is nil - it might be a refresh (37687)
  internal/terraform/node_action_trigger_instance_plan.go
Labels: no-changelog-needed

#35461 build: Produce a Windows arm64 binary
  .changes/v1.15/NEW FEATURES-20250926-164134.yaml
  .github/workflows/build.yml
Labels: enhancement

#37685 Swap to using `google.golang.org/protobuf/cmd/protoc-gen-go` instead of `github.com/golang/protobuf/protoc-gen-go`
  go.mod
  go.sum
  internal/cloudplugin/cloudproto1/cloudproto1.pb.go
  internal/cloudplugin/cloudproto1/cloudproto1_grpc.pb.go
  internal/rpcapi/dynrpcserver/generator/main.go
  internal/rpcapi/terraform1/dependencies/dependencies.pb.go
  internal/rpcapi/terraform1/dependencies/dependencies_grpc.pb.go
  internal/rpcapi/terraform1/packages/packages.pb.go
  internal/rpcapi/terraform1/packages/packages_grpc.pb.go
  internal/rpcapi/terraform1/setup/setup.pb.go
  internal/rpcapi/terraform1/setup/setup_grpc.pb.go
  internal/rpcapi/terraform1/stacks/stacks.pb.go
  internal/rpcapi/terraform1/stacks/stacks_grpc.pb.go
  internal/stacksplugin/stacksproto1/stacksproto1.pb.go
  internal/stacksplugin/stacksproto1/stacksproto1_grpc.pb.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin5/tfplugin5_grpc.pb.go
  internal/tfplugin6/tfplugin6.pb.go
  internal/tfplugin6/tfplugin6_grpc.pb.go
  tools/protobuf-compile/protobuf-compile.go
Labels: no-changelog-needed
