Repository hashicorp/terraform, pull requests merged in 2025-03, with the labels that each got.

#36607 Update `hashicorp/cli` dependency
  go.mod
  go.sum
Labels: 1.11-backport, no-changelog-needed

#36601 diagnostics should not contain URLs
  internal/command/arguments/apply.go
  internal/command/arguments/plan.go
  internal/command/arguments/refresh.go
  internal/command/testdata/apply/output.jsonlog
Labels: no-changelog-needed

#36611 lang/funcs/transpose: Avoid crash due to map with `null` values
  .changes/v1.11/BUG FIXES-20250303-125722.yaml
  internal/lang/funcs/collection.go
  internal/lang/funcs/collection_test.go
Labels: 1.11-backport

#36605 docs: improve write-only attribute example
  website/docs/language/resources/ephemeral/index.mdx
  website/docs/language/resources/ephemeral/reference.mdx
  website/docs/language/resources/ephemeral/write-only.mdx
Labels: documentation, 1.11-backport, no-changelog-needed

#36591 build: always build on successful pushes rather than waiting for tests
  .github/workflows/build.yml
Labels: 1.11-backport, no-changelog-needed

#36627 build: always build on successful pushes rather than waiting for unit tests
  .github/workflows/build.yml
Labels: no-changelog-needed

#36621 Add feedback for write-only changes
  website/docs/language/resources/ephemeral/index.mdx
  website/docs/language/resources/ephemeral/reference.mdx
  website/docs/language/resources/ephemeral/write-only.mdx
Labels: 1.11-backport, no-changelog-needed

#36635 Add Brian feedback
  website/docs/language/resources/ephemeral/index.mdx
  website/docs/language/resources/ephemeral/write-only.mdx
Labels: 1.11-backport, no-changelog-needed

#36582 terraform test: fix crash when non-applyable plans are applied
  .changes/v1.11/BUG FIXES-20250226-140931.yaml
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/command/testdata/test/unapplyable-plan/main.tf
  internal/command/testdata/test/unapplyable-plan/main.tftest.hcl
Labels: 1.11-backport

#36583 Add test case to ensure no regression of already fixed crash
  internal/command/test_test.go
  internal/command/testdata/test/unapplyable-plan/main.tf
  internal/command/testdata/test/unapplyable-plan/main.tftest.hcl
Labels: no-changelog-needed

#36618 Enhance elapsed time display in UI Hook with minutes and seconds
  .changes/v1.12/ENHANCEMENTS-20250303-151031.yaml
  internal/command/views/hook_ui.go
  internal/command/views/hook_ui_test.go
Labels: enhancement

#36639 Prepare for 1.11.1 release
  .changes/1.11.1.md
  .changes/v1.11/BUG FIXES-20250225-083056.yaml
  .changes/v1.11/BUG FIXES-20250226-140931.yaml
  .changes/v1.11/BUG FIXES-20250226-181429.yaml
  .changes/v1.11/BUG FIXES-20250303-125722.yaml
  .changes/v1.11/BUG FIXES-20250303-144020.yaml
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36642 Cleanup after 1.11.1 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36625 fix: bump aws-sdk-go-base/v2 from v2.0.0-beta.58 to v2.0.0-beta.62
  .changes/v1.11/NOTES-20250305-101858.yaml
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
  internal/legacy/go.sum
Labels: upstream, backend/s3, 1.11-backport

#36662 Update identity related fields in protocol move request
  docs/plugin-protocol/tfplugin5.9.proto
  docs/plugin-protocol/tfplugin6.9.proto
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: no-changelog-needed

#36666 Remove irrelevant link to issue.
  website/docs/language/resources/provisioners/syntax.mdx
Labels: documentation, 1.11-backport, no-changelog-needed

#36668 Remove irrelevant link to github issue
  website/docs/language/meta-arguments/lifecycle.mdx
Labels: documentation, 1.11-backport, no-changelog-needed

#36664 Move changelog entry to v1.11
  .changes/v1.11/BUG FIXES-20250310-093153.yaml
Labels: 1.11-backport

#36675 Marshall resource identity schemas in `jsonprovider` (TF-23824)
  internal/command/jsonprovider/attribute.go
  internal/command/jsonprovider/attribute_test.go
  internal/command/jsonprovider/provider.go
  internal/command/jsonprovider/provider_test.go
  internal/command/jsonprovider/schema.go
Labels: no-changelog-needed

#36623 Backend/azure: `subscription_id` infer from Azure CLI & a way to skip *unnecessary* management plane API call
  .changes/v1.11/BUG FIXES-20250311-104640.yaml
  internal/backend/remote-state/azure/api_client.go
  internal/backend/remote-state/azure/backend.go
  internal/backend/remote-state/azure/backend_test.go
  internal/backend/remote-state/azure/storage_client_helpers.go
Labels: enhancement, backend/azure, 1.11-backport

#36673 stacks: fix errors processing index keys of removed blocks
  internal/stacks/stackconfig/config_test.go
  internal/stacks/stackconfig/removed.go
  internal/stacks/stackconfig/testdata/basics-bundle/errored/main.tfstack.hcl
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-component-instance-direct/removed-component-instance-direct.tfstack.hcl
Labels: no-changelog-needed

#36679 Fix broken build due to merge conflicts
  internal/stacks/stackruntime/apply_test.go
Labels: no-changelog-needed

#36681 Prepare for 1.11.2 release
  .changes/1.11.2.md
  .changes/v1.11/BUG FIXES-20250310-093153.yaml
  .changes/v1.11/BUG FIXES-20250311-104640.yaml
  .changes/v1.11/ENHANCEMENTS-20250207-164803.yaml
  .changes/v1.11/NOTES-20250305-101858.yaml
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36682 stacks: test resource identity
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackruntime/testdata/mainbundle/test/resource-identity/resource-identity.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/resource-identity/resource-identity.tfstack.hcl
  internal/stacks/stackruntime/testing/provider.go
  internal/stacks/stackruntime/testing/resource.go
Labels: no-changelog-needed

#36683 Cleanup after 1.11.2 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36684 Prepare for 1.12.0-alpha20250312 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36688 Cleanup after 1.12.0-alpha20250312 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36685 Prevent test run when leftover state data is present
  internal/backend/local/test.go
  internal/command/test_test.go
  internal/moduletest/graph/manifest.go
Labels: no-changelog-needed

#36691 Bump `golang.org/x/net` to v0.36.0
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.mod
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.mod
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
  internal/legacy/go.mod
  internal/legacy/go.sum
Labels: 1.11-backport, no-changelog-needed

#36646 `test`: Set the initial state for a state files from a backend, allow the run that defines a backend to write state to the backend
  internal/backend/local/test.go
  internal/command/test.go
  internal/command/test_test.go
  internal/command/testdata/test/valid-use-local-backend/main.tf
  internal/command/testdata/test/valid-use-local-backend/main.tftest.hcl
  internal/moduletest/graph/apply.go
  internal/moduletest/graph/eval_context.go
  internal/moduletest/graph/plan.go
  internal/moduletest/graph/test_graph_builder.go
  internal/moduletest/graph/transform_state.go
Labels: no-changelog-needed

#36636 Add Azure example
  website/docs/language/resources/ephemeral/write-only.mdx
Labels: 1.11-backport, no-changelog-needed

#36693 stacks: allow multiple removed blocks to target the same component
  internal/rpcapi/stacks.go
  internal/rpcapi/terraform1/stacks/stacks.pb.go
  internal/rpcapi/terraform1/stacks/stacks.proto
  internal/stacks/stackconfig/config.go
  internal/stacks/stackconfig/declarations.go
  internal/stacks/stackruntime/apply_test.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/internal/stackeval/walk_static.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-single-input/removed-component-duplicate/removed-component-duplicate.tfstack.hcl
Labels: no-changelog-needed

#36696 stacks: pre-destroy refresh should use a normal plan
  internal/stacks/stackruntime/apply_destroy_test.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/refresh_instance.go
  internal/stacks/stackruntime/plan_test.go
  internal/stacks/stackruntime/testdata/mainbundle/test/with-module/module/module.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/with-module/with-module.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/with-module/with-module.tfstack.hcl
Labels: no-changelog-needed

#36700 Backport of docs: azurerm backend updates for 1.11 release into v1.11
  website/docs/language/backend/azurerm.mdx
Labels: no-changelog-needed

#36705 CLI command for listing state identities
  commands.go
  internal/command/command_test.go
  internal/command/state_identities.go
  internal/command/state_identities_test.go
  internal/command/testdata/state-identities-backend-default/.terraform/terraform.tfstate
  internal/command/testdata/state-identities-backend-default/main.tf
  internal/command/testdata/state-identities-backend-default/terraform.tfstate
  internal/command/testdata/state-identities-nested-modules/terraform.tfstate
Labels: no-changelog-needed

#36709 Detect circular references during Validation
  internal/stacks/stackruntime/internal/stackeval/component_config.go
  internal/stacks/stackruntime/internal/stackeval/local_value_config.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/output_value_config.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_config.go
  internal/stacks/stackruntime/testdata/mainbundle/test/validate-cyclic-dependency/main.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/validate-cyclic-dependency/validate-cyclic-dependency.tfstack.hcl
  internal/stacks/stackruntime/validate_test.go
Labels: no-changelog-needed

#36482 migrate command for terraform stacks
  internal/collections/set.go
  internal/configs/source_bundle_parser.go
  internal/rpcapi/dynrpcserver/stacks.go
  internal/rpcapi/handles.go
  internal/rpcapi/plugin.go
  internal/rpcapi/stacks.go
  internal/rpcapi/stacks_test.go
  internal/rpcapi/terraform1/stacks/stacks.pb.go
  internal/rpcapi/terraform1/stacks/stacks.proto
  internal/rpcapi/testdata/sourcebundle/baz/main.tf
  internal/rpcapi/testdata/sourcebundle/baz/main.tfstack.hcl
  internal/rpcapi/testdata/sourcebundle/terraform-sources.json
  internal/stacks/stackaddrs/component.go
  internal/stacks/stackaddrs/in_component.go
  internal/stacks/stackaddrs/stack.go
  internal/stacks/stackaddrs/stack_test.go
  internal/stacks/stackconfig/component.go
  internal/stacks/stackconfig/config.go
  internal/stacks/stackconfig/parser/walker.go
  internal/stacks/stackmigrate/components.go
  internal/stacks/stackmigrate/load.go
  internal/stacks/stackmigrate/load_test.go
  internal/stacks/stackmigrate/migrate.go
  internal/stacks/stackmigrate/migrate_test.go
  internal/stacks/stackmigrate/resources.go
  internal/stacks/stackmigrate/testing.go
  internal/stacks/stackruntime/internal/stackeval/component_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_config.go
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-dependency/input-dependency/input-dependency.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-dependency/main.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-dependency/provider-dependency/provider-dependency.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-depends-on/depends-on.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-depends-on/main.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-depends-on/valid/valid.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-nested-module/child/main.tf
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-nested-module/input-dependency.tfstack.hcl
  internal/stacks/stackruntime/testdata/mainbundle/test/for-stacks-migrate/with-nested-module/main.tf
Labels: no-changelog-needed

#36721 Prepare for 1.12.0-alpha20250319 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36722 Cleanup after 1.12.0-alpha20250319 release
  CHANGELOG.md
  version/VERSION
Labels: no-changelog-needed

#36723 Update issensitive.mdx - Fixed function name typo
  website/docs/language/functions/issensitive.mdx
Labels: 1.8-backport, 1.9-backport, 1.10-backport, 1.11-backport, no-changelog-needed

#36726 Fix panic in proxyDialer
  internal/communicator/ssh/http_proxy.go
Labels: bug, provisioners

#36710 fix element function documentation
  website/docs/language/functions/element.mdx
Labels: waiting-response, documentation, 1.10-backport, 1.11-backport, no-changelog-needed

#36706 update legacy term: Terraform Cloud agent => HCP Terraform Agent
  .changes/v1.12/ENHANCEMENTS-20250318-001121.yaml
  internal/cloud/backend_plan.go
Labels: enhancement, documentation

#36747 Replace state get/set functions with existing helpers
  internal/command/test_test.go
Labels: no-changelog-needed

#36741 Update .github/workflows/checks.yml on v1.9 to roughly match main branch
  .github/workflows/checks.yml
Labels: no-changelog-needed

#36736 Update .github/workflows/checks.yml on v1.8 to roughly match main branch
  .github/workflows/checks.yml
Labels: no-changelog-needed

#36474 Migrate more testing helpers into tfdiags package
  internal/initwd/from_module_test.go
  internal/initwd/module_install_test.go
  internal/terraform/context_apply2_test.go
  internal/terraform/context_apply_checks_test.go
  internal/terraform/context_apply_deferred_test.go
  internal/terraform/context_apply_ephemeral_test.go
  internal/terraform/context_apply_identity_test.go
  internal/terraform/context_apply_test.go
  internal/terraform/context_eval_test.go
  internal/terraform/context_functions_test.go
  internal/terraform/context_input_test.go
  internal/terraform/context_plan2_test.go
  internal/terraform/context_plan_ephemeral_test.go
  internal/terraform/context_plan_identity_test.go
  internal/terraform/context_plan_test.go
  internal/terraform/context_refresh_test.go
  internal/terraform/context_test.go
  internal/terraform/context_validate_test.go
  internal/terraform/eval_for_each_test.go
  internal/terraform/transform_destroy_edge_test.go
  internal/terraform/transform_reference_test.go
  internal/tfdiags/testing.go
Labels: no-changelog-needed

#36750 Add test coverage for `local` backend's backend.Backend methods and behaviours
  internal/backend/local/backend_test.go
Labels: no-changelog-needed

#36752 Increase test coverage for local backend's PathsConflictWith and StatePaths methods
  internal/backend/local/backend.go
  internal/backend/local/backend_test.go
Labels: no-changelog-needed

#36755 Update Next.js dependency
  website/package-lock.json
  website/package.json
Labels: no-changelog-needed

#36759 remove unused interface
  internal/terraform/instance_expanders.go
  internal/terraform/node_check.go
  internal/terraform/node_local.go
  internal/terraform/node_module_expand.go
  internal/terraform/node_module_variable.go
  internal/terraform/node_output.go
  internal/terraform/node_resource_apply.go
  internal/terraform/node_resource_plan.go
Labels: no-changelog-needed

#36561 Update `hashicorp/go-plugin` dependency
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.sum
  internal/cloudplugin/cloudproto1/cloudproto1.pb.go
  internal/plans/planproto/planfile.pb.go
  internal/rpcapi/terraform1/dependencies/dependencies.pb.go
  internal/rpcapi/terraform1/packages/packages.pb.go
  internal/rpcapi/terraform1/setup/setup.pb.go
  internal/rpcapi/terraform1/stacks/stacks.pb.go
  internal/rpcapi/terraform1/terraform1.pb.go
  internal/stacks/tfstackdata1/tfstackdata1.pb.go
  internal/tfplugin5/tfplugin5.pb.go
  internal/tfplugin6/tfplugin6.pb.go
Labels: no-changelog-needed

#36749 stacks: make promises identify themselves
  internal/promising/once.go
  internal/promising/once_test.go
  internal/promising/promise.go
  internal/promising/public_test.go
  internal/stacks/stackaddrs/component.go
  internal/stacks/stackaddrs/provider_config.go
  internal/stacks/stackruntime/internal/stackeval/change_exec.go
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/component_config.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/diagnostics.go
  internal/stacks/stackruntime/internal/stackeval/diagnostics_test.go
  internal/stacks/stackruntime/internal/stackeval/input_variable.go
  internal/stacks/stackruntime/internal/stackeval/input_variable_config.go
  internal/stacks/stackruntime/internal/stackeval/local_value.go
  internal/stacks/stackruntime/internal/stackeval/local_value_config.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/main_inspect.go
  internal/stacks/stackruntime/internal/stackeval/main_plan.go
  internal/stacks/stackruntime/internal/stackeval/main_validate.go
  internal/stacks/stackruntime/internal/stackeval/output_value.go
  internal/stacks/stackruntime/internal/stackeval/output_value_config.go
  internal/stacks/stackruntime/internal/stackeval/provider.go
  internal/stacks/stackruntime/internal/stackeval/provider_config.go
  internal/stacks/stackruntime/internal/stackeval/provider_instance.go
  internal/stacks/stackruntime/internal/stackeval/provider_type.go
  internal/stacks/stackruntime/internal/stackeval/refresh_instance.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_config.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/validate_test.go
Labels: no-changelog-needed

#36762 stacks: remove all the unnecessary ctx function parameters
  internal/stacks/stackruntime/internal/stackeval/applying.go
  internal/stacks/stackruntime/internal/stackeval/component.go
  internal/stacks/stackruntime/internal/stackeval/component_config.go
  internal/stacks/stackruntime/internal/stackeval/component_instance.go
  internal/stacks/stackruntime/internal/stackeval/component_test.go
  internal/stacks/stackruntime/internal/stackeval/expression_refs.go
  internal/stacks/stackruntime/internal/stackeval/expressions.go
  internal/stacks/stackruntime/internal/stackeval/expressions_test.go
  internal/stacks/stackruntime/internal/stackeval/input_variable.go
  internal/stacks/stackruntime/internal/stackeval/input_variable_config.go
  internal/stacks/stackruntime/internal/stackeval/input_variable_test.go
  internal/stacks/stackruntime/internal/stackeval/local_value.go
  internal/stacks/stackruntime/internal/stackeval/local_value_config.go
  internal/stacks/stackruntime/internal/stackeval/local_value_test.go
  internal/stacks/stackruntime/internal/stackeval/main.go
  internal/stacks/stackruntime/internal/stackeval/main_apply.go
  internal/stacks/stackruntime/internal/stackeval/output_value.go
  internal/stacks/stackruntime/internal/stackeval/output_value_config.go
  internal/stacks/stackruntime/internal/stackeval/output_value_test.go
  internal/stacks/stackruntime/internal/stackeval/planning.go
  internal/stacks/stackruntime/internal/stackeval/planning_test.go
  internal/stacks/stackruntime/internal/stackeval/provider.go
  internal/stacks/stackruntime/internal/stackeval/provider_config.go
  internal/stacks/stackruntime/internal/stackeval/provider_config_test.go
  internal/stacks/stackruntime/internal/stackeval/provider_expressions.go
  internal/stacks/stackruntime/internal/stackeval/provider_factory.go
  internal/stacks/stackruntime/internal/stackeval/provider_instance.go
  internal/stacks/stackruntime/internal/stackeval/provider_instance_test.go
  internal/stacks/stackruntime/internal/stackeval/provider_test.go
  internal/stacks/stackruntime/internal/stackeval/refresh_instance.go
  internal/stacks/stackruntime/internal/stackeval/removed.go
  internal/stacks/stackruntime/internal/stackeval/removed_config.go
  internal/stacks/stackruntime/internal/stackeval/removed_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack.go
  internal/stacks/stackruntime/internal/stackeval/stack_call.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_config.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_instance.go
  internal/stacks/stackruntime/internal/stackeval/stack_call_test.go
  internal/stacks/stackruntime/internal/stackeval/stack_config.go
  internal/stacks/stackruntime/internal/stackeval/stubs/errored.go
  internal/stacks/stackruntime/internal/stackeval/stubs/offline.go
  internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go
  internal/stacks/stackruntime/internal/stackeval/test_only_global.go
  internal/stacks/stackruntime/internal/stackeval/test_only_global_test.go
  internal/stacks/stackruntime/internal/stackeval/validating.go
  internal/stacks/stackruntime/internal/stackeval/walk_dynamic.go
  internal/stacks/stackruntime/internal/stackeval/walk_static.go
Labels: no-changelog-needed

#36765 Cleanup after 1.11.3 release
  version/VERSION
Labels: no-changelog-needed

#36761 updated some of the boilerplate text
  website/docs/language/moved.mdx
Labels: 1.3-backport, 1.4-backport, 1.5-backport, 1.6-backport, 1.7-backport, 1.8-backport, 1.9-backport, 1.10-backport, 1.11-backport, no-changelog-needed

#36781 updates the terraform block ref to match new design doc
  website/docs/language/terraform.mdx
Labels: 1.9-backport, 1.10-backport, 1.11-backport, no-changelog-needed

#36757 Add TRACE logs when uploading to the cloud and remote backends
  internal/backend/remote/backend_plan.go
  internal/cloud/backend_plan.go
Labels: enhancement, no-changelog-needed

#36756 Fix protov6 crash when refreshing resource with identity
  internal/plugin/grpc_provider.go
  internal/plugin6/grpc_provider.go
Labels: no-changelog-needed

#31775 Update locking.mdx
  website/docs/language/state/locking.mdx
Labels: documentation

#36805 Update lower.mdx
  website/docs/language/functions/lower.mdx
Labels: documentation, no-changelog-needed

#36743 Replacing the `check` block with the content type page
  website/data/language-nav-data.json
  website/docs/cli/test/index.mdx
  website/docs/language/block/check.mdx
  website/docs/language/block/terraform.mdx
  website/docs/language/checks/index.mdx
Labels: no-changelog-needed
