Repository hashicorp/terraform, pull requests merged in 2025-10, with the labels that each got.

#37650 Improve tests in internal/states (ProviderAddrs, HasCurrent, Unlock)
  internal/states/resource_test.go
  internal/states/state_test.go
Labels: enhancement, no-changelog-needed

#37692 Added missing output for the terraform apply cli actions
  .changes/v1.14/BUGFIX-20250927-184134.yaml
  internal/command/views/apply.go
Labels: bug, 1.14-backport

#37711 PSS: Implement `LockState` & `UnlockState` provider methods
  docs/plugin-protocol/tfplugin6.proto
  internal/builtin/providers/terraform/provider.go
  internal/grpcwrap/provider6.go
  internal/plugin/grpc_provider.go
  internal/plugin6/grpc_provider.go
  internal/plugin6/mock_proto/mock.go
  internal/provider-simple-v6/provider.go
  internal/provider-simple/provider.go
  internal/providers/mock.go
  internal/providers/provider.go
  internal/providers/testing/provider_mock.go
  internal/refactoring/mock_provider.go
  internal/stacks/stackruntime/internal/stackeval/stubs/errored.go
  internal/stacks/stackruntime/internal/stackeval/stubs/offline.go
  internal/stacks/stackruntime/internal/stackeval/stubs/unknown.go
  internal/tfplugin6/tfplugin6.pb.go
  internal/tfplugin6/tfplugin6_grpc.pb.go
Labels: no-changelog-needed

#37717 PSS: Implement `Get` and `Put` methods on remote grpc state, using Read/WriteStateBytes RPCs
  internal/states/remote/remote_grpc.go
  internal/states/remote/remote_grpc_test.go
Labels: no-changelog-needed

#37728 Fix 1.14 changelog entry
  .changes/v1.14/BUG FIXES-20250927-184134.yaml
Labels: skip-changelog-check

#37727 Backport: search: Drop identity from state if no identity schema is present
  internal/states/instance_object_src.go
  internal/states/instance_object_test.go
  internal/terraform/context_plan_identity_test.go
Labels: no-changelog-needed

#37701 actions: enforce ephemeral into write-only attributes behaviour
  internal/terraform/context_plan_actions_test.go
  internal/terraform/node_action_instance.go
  internal/terraform/node_action_validate.go
Labels: no-changelog-needed, 1.14-backport

#37721 AWS European Sovereign Cloud support, bump aws-sdk-go-base
  .changes/v1.14/ENHANCEMENTS-20251002-172626.yaml
  go.mod
  go.sum
  internal/backend/remote-state/azure/go.mod
  internal/backend/remote-state/azure/go.sum
  internal/backend/remote-state/consul/go.mod
  internal/backend/remote-state/consul/go.sum
  internal/backend/remote-state/cos/go.mod
  internal/backend/remote-state/cos/go.sum
  internal/backend/remote-state/gcs/go.mod
  internal/backend/remote-state/gcs/go.sum
  internal/backend/remote-state/kubernetes/go.mod
  internal/backend/remote-state/kubernetes/go.sum
  internal/backend/remote-state/oci/go.mod
  internal/backend/remote-state/oci/go.sum
  internal/backend/remote-state/oss/go.mod
  internal/backend/remote-state/oss/go.sum
  internal/backend/remote-state/pg/go.mod
  internal/backend/remote-state/pg/go.sum
  internal/backend/remote-state/s3/go.mod
  internal/backend/remote-state/s3/go.sum
  internal/legacy/go.mod
  internal/legacy/go.sum
  internal/rpcapi/telemetry_test.go
Labels: 1.14-backport
